window.GARDINER_DATA=[
  ['A1','𓀀','','homem sentado','D','Determinativo de homem e de nomes próprios; pronome de 1ª pessoa do singular ỉ, wỉ, ỉnk, kwỉ ("eu", "me", "meu").'],
  ['A2','𓀁','','homem com mão na boca','D','Determinativo de comer, beber, falar, pensar.'],
  ['A3','𓀂','','homem sentado sobre o calcanhar','D','Determinativo de sentar.'],
  ['A4','𓀃','','homem sentado com as mãos erguidas','D','Determinativo de adoração; esconder-se.'],
  ['A5','𓀄','','homem agachado escondendo-se atrás de muro','D','Determinativo de esconder-se.'],
  ['A6','𓀆','','homem sentado sob vaso do qual escorre água','D','Determinativo de pureza, limpeza.'],
  ['A7','𓀉','','homem fatigado','D','Determinativo de cansado, fraco.'],
  ['A8','𓀊','','homem executando o rito hnw','D','Determinativo em hnw ("júbilo").'],
  ['A9','𓀋','','homem equilibrando cesto na cabeça','D','Determinativo em ꜣṯp ("carga"), fꜣỉ ("carregar"), kꜣt ("trabalho").'],
  ['A10','𓀌','','homem sentado segurando remo','D','Determinativo em sḳdw ("navegar").'],
  ['A11','𓀍','','homem sentado segurando cetro de autoridade e cajado de pastor','D','Determinativo de ḫnms ("amigo").'],
  ['A12','𓀎','','soldado com arco e aljava','D','Determinativo de mšꜥ ("exército"); soldado.'],
  ['A13','𓀏','','homem com os braços atados às costas','D','Determinativo de ḫfty ("inimigo").'],
  ['A14','𓀐','','homem caindo com sangue escorrendo da cabeça','D','Determinativo de mwt ("morrer"); inimigo.'],
  ['A15','𓀒','','homem caindo','D','Determinativo de ḫr ("cair"), sḫrt ("derrubar").'],
  ['A16','𓀓','','homem se curvando','D','Determinativo de ksỉ ("curvar-se").'],
  ['A17','𓀔','ẖrd','criança sentada com a mão na boca','ID','Determinativo de šrỉ ("jovem"). Logograma de ẖrd ("criança").'],
  ['A18','𓀖','','criança usando coroa vermelha','D','Determinativo de rei-criança.'],
  ['A19','𓀗','','homem curvado apoiado em cajado','D','Determinativo de ỉꜣw ("velho"), smsw ("mais velho"), wr ("grande, chefe").'],
  ['A20','𓀘','','homem apoiado em cajado bifurcado','D','Variante de A19.'],
  ['A21','𓀙','sr','homem segurando cajado com lenço','ID','Determinativo e logograma de sr ("oficial, nobre").'],
  ['A22','𓀚','','estátua de homem com cajado e cetro de autoridade','D','Determinativo de estátua.'],
  ['A23','𓀛','','rei com cajado e maça de cabeça arredondada','D','Determinativo de ỉty ("soberano").'],
  ['A24','𓀜','nḫt','homem golpeando com ambas as mãos','ID','Determinativo de ḥwỉ ("golpear"), nḥm ("tomar, arrebatar"). Logograma de nḫt ("forte").'],
  ['A25','𓀝','','homem golpeando, com o braço esquerdo pendendo às costas','D','Determinativo de hwỉ ("golpear").'],
  ['A26','𓀞','','homem com um braço apontado à frente','ID','Determinativo de nỉs ("chamar"). Logograma do vocativo ỉ ("ó!").'],
  ['A27','𓀟','ỉn','homem em passo acelerado','P','Fonograma ỉn ("por"), partícula de agente.'],
  ['A28','𓀠','','homem com as mãos erguidas de cada lado','D','Determinativo de ḳꜣ ("alto"), ḥꜥỉ ("regozijar-se").'],
  ['A29','𓀡','','homem de cabeça para baixo','D','Determinativo de cabeça para baixo.'],
  ['A30','𓀢','','homem com as mãos erguidas à frente','D','Determinativo de ỉꜣw ("louvor"), dwꜣ ("adoração").'],
  ['A31','𓀣','','homem com as mãos erguidas atrás','D','Determinativo de virar-se, dar as costas.'],
  ['A32','𓀤','','homem dançando com os braços para trás','D','Determinativo de dançar.'],
  ['A33','𓀦','','homem com vara e trouxa sobre o ombro','D','Determinativo de vagar; pastor.'],
  ['A34','𓀧','','homem pilando em almofariz','D','Determinativo de ḫwsỉ ("pilar, construir").'],
  ['A35','𓀨','ḳd','homem construindo muro','ID','Determinativo e logograma de ḳd ("construir").'],
  ['A36','𓀩','ꜥfty','homem amassando em vasilha','ID','Determinativo e logograma de ꜥfty ("cervejeiro").'],
  ['A37','𓀪','','homem dentro de vasilha','ID','Igual a A36.'],
  ['A38','𓀫','ḳỉs|ḳsỉ','homem segurando pelo pescoço dois animais emblemáticos com cabeças de pantera','I','Logograma de ḳỉs/ḳsỉ ("Cusae", cidade).'],
  ['A39','𓀬','','homem sobre duas girafas','I','Igual a A38.'],
  ['A40','𓀭','','deus sentado','D','Determinativo de deus. Substitui A1 como pronome de 1ª pessoa do singular quando um deus fala: ỉ, wỉ, ỉnk, kwỉ.'],
  ['A41','𓀯','','rei com uraeus','D','Determinativo de nsw ("rei"), ḥm ("majestade"), nb ("senhor").'],
  ['A42','𓀰','','rei com uraeus e flagelo','D','Igual a A41.'],
  ['A43','𓀲','','rei usando coroa branca','D','Determinativo de rei do Alto Egito.'],
  ['A44','𓀴','','rei usando coroa branca com flagelo','D','Igual a A43.'],
  ['A45','𓀵','bỉty','rei usando coroa vermelha','ID','Determinativo e logograma de bỉty ("rei do Baixo Egito").'],
  ['A46','𓀷','','rei usando coroa vermelha com flagelo','ID','Igual a A45.'],
  ['A47','𓀸','sꜣw','pastor sentado e envolto em manto, segurando vara','ID','Determinativo e logograma de sꜣw ("guarda"), mnỉw ("pastor").'],
  ['A48','𓀹','','homem sem barba sentado e segurando faca','D','Determinativo de ỉry ("relativo a").'],
  ['A49','𓀺','','sírio sentado segurando vara','D','Determinativo de estrangeiro; ꜥꜣmw ("asiáticos").'],
  ['A50','𓀻','','nobre em cadeira','D','Determinativo de pessoa venerável, falecido. Variante de A1 para o pronome de 1ª pessoa do singular.'],
  ['A51','𓀼','špsỉ','nobre em cadeira com flagelo','ID','Determinativo e logograma de špsỉ ("nobre").'],
  ['A52','𓀽','','nobre agachado com flagelo','D','Determinativo de pessoa venerável, falecido.'],
  ['A53','𓀾','','múmia de pé','D','Determinativo de múmia, estátua, imagem, forma.'],
  ['A54','𓀿','','múmia deitada','D','Determinativo de morto.'],
  ['A55','𓁀','','múmia sobre leito','D','Determinativo de sḏr ("deitar-se"); morto.'],
  ['A56','𓁁','','homem sentado segurando vara','',''],
  ['A57','𓁂','ḥtp-dỉ-nsw','homem segurando pão sobre esteira','',''],
  ['A58','𓁃','','homem aplicando enxada ao solo','',''],
  ['A59','𓁄','','homem ameaçando com vara','D','Determinativo de afugentar, repelir.'],
  ['A60','𓁅','stỉ','homem semeando','',''],
  ['A61','𓁆','','homem olhando por cima do ombro','',''],
  ['A62','𓁇','','asiático','',''],
  ['A63','𓁈','','rei no trono segurando cajado','',''],
  ['A64','𓁉','','homem sentado sobre os calcanhares segurando taça à frente','',''],
  ['A65','𓁊','','homem usando túnica com franjas e segurando maça','',''],
  ['A66','𓁋','ỉḥy|nṯr-ꜥꜣ','homem segurando sistro','',''],
  ['A67','𓁌','','anão','',''],
  ['A68','𓁍','msdmt','homem erguendo faca','',''],
  ['A69','𓁎','','homem sentado com o braço direito erguido e o esquerdo pendente','',''],
  ['A70','𓁏','ḥḥ','homem sentado com os braços erguidos','',''],
  ['B1','𓁐','','mulher sentada','D','Determinativo de mulher e de nomes próprios. Às vezes no lugar de A1 para o pronome de 1ª pessoa do singular ỉ.'],
  ['B2','𓁑','','mulher grávida','D','Determinativo de grávida.'],
  ['B3','𓁒','msỉ','mulher dando à luz','ID','Determinativo e logograma de msỉ ("dar à luz").'],
  ['B4','𓁓','','combinação de mulher dando à luz e três peles atadas','ID','Igual a B3.'],
  ['B5','𓁔','','mulher amamentando criança','D','Determinativo de mnꜥt ("ama, nutriz").'],
  ['B6','𓁖','','mulher em cadeira com criança no colo','D','Determinativo de rnn ("criar, amamentar").'],
  ['B7','𓁗','','rainha usando diadema e segurando flor','D','Determinativo de nomes de rainhas.'],
  ['B8','𓁘','','mulher segurando flor de lótus','',''],
  ['B9','𓁙','','mulher segurando sistro','',''],
  ['C1','𓁚','Rꜥ','deus com disco solar e uraeus','ID','Determinativo e logograma de Rꜥ ("Rá, deus-sol").'],
  ['C2','𓁛','Rꜥ','deus com cabeça de falcão e disco solar segurando ânkh','ID','Variante de C1. Determinativo e logograma de Rꜥ ("Rá, deus-sol").'],
  ['C3','𓁟','ḏḥwty','deus com cabeça de íbis','ID','Determinativo ou logograma de ḏḥwty ("Tot").'],
  ['C4','𓁠','ẖnmw','deus com cabeça de carneiro','ID','Determinativo ou logograma de ẖnmw ("Khnum").'],
  ['C5','𓁡','','deus com cabeça de carneiro segurando ânkh','ID','Igual a C4.'],
  ['C6','𓁢','ỉnpw','deus com cabeça de chacal','ID','Determinativo e logograma de ỉnpw ("Anúbis"), wp-wꜣwt ("Upuaut").'],
  ['C7','𓁣','Stḫ','deus com cabeça do animal de Set','ID','Determinativo e logograma de Stḫ ("Set").'],
  ['C8','𓁤','Mnw','deus itifálico com duas plumas, braço erguido e flagelo','ID','Determinativo e logograma de Mnw ("Min").'],
  ['C9','𓁥','','deusa com disco solar entre chifres','ID','Determinativo e logograma.'],
  ['C10','𓁦','Mꜣꜥt','deusa com pena','ID','Determinativo e logograma de Mꜣꜥt ("Maat").'],
  ['C11','𓁨','ḥḥ','deus com braços sustentando o céu e ramo de palmeira na cabeça','I','Logograma de ḥḥ ("milhão"); o deus Heh.'],
  ['C12','𓁩','Imn','deus com duas plumas e cetro','ID','Determinativo e logograma de Ỉmn ("Amon").'],
  ['C13','𓁪','ỉmn','C12 invertido','',''],
  ['C14','𓁫','ỉmn-ḥr-ḫpš.f','deus com duas plumas e cimitarra','',''],
  ['C15','𓁬','ỉmn-ḥr-ḫpš.f','C14 invertido','',''],
  ['C16','𓁭','ỉtmw','deus usando coroa vermelha com ânkh','',''],
  ['C17','𓁮','','deus com cabeça de falcão e duas plumas','ID','Determinativo e logograma de Mntw ("Montu").'],
  ['C18','𓁯','tꜣ-ṯnn','deus agachado','ID','Determinativo e logograma de tꜣ-ṯnn ("Tatenen").'],
  ['C19','𓁰','Ptḥ','deus em forma de múmia','ID','Determinativo e logograma de Ptḥ ("Ptah").'],
  ['C20','𓁱','','deus em forma de múmia em santuário','ID','Igual a C19.'],
  ['C21','𓁲','bs','Bes','',''],
  ['C22','𓁳','ḫnsw','deus com cabeça de falcão e lua','',''],
  ['C23','𓁴','sḫmt|mnḥyt|mḥyt|bꜣstt','deusa com cabeça felina e sol com uraeus','',''],
  ['C24','𓁵','ỉtmw','deus usando coroa vermelha com cetro','',''],
  ['D1','𓁶','tp','cabeça','PID','Fonograma tp. Determinativo ou logograma de tp ("cabeça"), tpy ("primeiro, chefe"). Determinativo de ḏꜣḏꜣ ("cabeça").'],
  ['D2','𓁷','ḥr','rosto','PI','Fonograma ḥr. Logograma de ḥr ("rosto").'],
  ['D3','𓁸','','cabelos','D','Determinativo de šny ("cabelo"), ỉwn ("tez, natureza"). Abreviatura de gm wš ("achado em falta").'],
  ['D4','𓁹','ỉrt','olho','PI','Fonograma ỉrỉ ("fazer"). Logograma de ỉrt ("olho").'],
  ['D5','𓁺','','olho com maquiagem','D','Determinativo de ações ou estados do olho: dgỉ ("olhar"), šp ("cego").'],
  ['D6','𓁻','','olho com pálpebra superior pintada','D','Igual a D5.'],
  ['D7','𓁼','','olho com pálpebra inferior pintada','D','Determinativo de adornar e em ꜥnw ("Anu", localidade).'],
  ['D8','𓁽','','olho circundado por trato arenoso','D','Determinativo de ꜥnw ("Turah"), ꜥn ("belo").'],
  ['D9','𓁿','rmỉ','olho com lágrimas escorrendo','ID','Determinativo ou logograma de rmỉ ("chorar").'],
  ['D10','𓂀','wꜣḏt','Olho de Hórus','ID','Determinativo ou logograma de wꜣḏt ("olho-udjat").'],
  ['D11','𓂁','','parte esquerda do Olho de Hórus','','Medida de ½ heqat de grão.'],
  ['D12','𓂂','','pupila','D','Determinativo de ḏfd ("pupila do olho").'],
  ['D13','𓂃','','sobrancelha','','Medida de ⅛ de heqat de grão.'],
  ['D14','𓂄','','parte direita do Olho de Hórus','','Medida de 1/16 de heqat de grão.'],
  ['D15','𓂅','','marcação diagonal do Olho de Hórus','','Medida de 1/32 de heqat de grão.'],
  ['D16','𓂆','','marcação vertical do Olho de Hórus','','Medida de 1/64 de heqat de grão.'],
  ['D17','𓂇','tỉt','marcações diagonal e vertical do Olho de Hórus','ID','Determinativo ou logograma de tỉt ("figura, imagem").'],
  ['D18','𓂈','msḏr','orelha','ID','Determinativo ou logograma de msḏr ("orelha").'],
  ['D19','𓂉','fnd','nariz, olho e bochecha','ID','Determinativo ou logograma de fnd ("nariz"). Determinativo de sn ("cheirar"), rš ("regozijar-se").'],
  ['D20','𓂊','','nariz, olho e bochecha (cursivo)','ID','Igual a D19.'],
  ['D21','𓂋','r','boca','','Igual a T31.'],
  ['D22','𓂌','rwy','boca com dois traços','I','Logograma de rwy ("2/3").'],
  ['D23','𓂍','ḫmt','boca com três traços','I','Logograma de ḫmt rw ("3/4").'],
  ['D24','𓂎','spt','lábio superior com dentes','ID','Determinativo ou logograma de spt ("lábio"). Usado por engano como F42.'],
  ['D25','𓂏','spty','lábios','ID','Determinativo ou logograma de spty ("lábios").'],
  ['D26','𓂐','','líquido saindo dos lábios','D','Determinativo de cuspir, vomitar: psg ("cuspir"), ḳꜥ ("vomitar").'],
  ['D27','𓂑','','seio pequeno','D','Determinativo de seio, amamentar: mnḏ ("seio").'],
  ['D28','𓂓','kꜣ','dois braços erguidos','PI','Fonograma kꜣ. Logograma de kꜣ ("ka").'],
  ['D29','𓂔','kꜣ','combinação dos hieróglifos D28 e R12','PI','Igual a D28.'],
  ['D30','𓂕','','dois braços erguidos com cauda','D','Determinativo de nḥb-kꜣw ("Unificador dos Atributos, Distribuidor dos Kas"), nome de uma divindade serpentina mítica.'],
  ['D31','𓂖','ḥm-kꜣ','braços abraçando clava','I','Logograma de ḥm-kꜣ ("servidor do ka").'],
  ['D32','𓂘','','braços se abraçando','D','Determinativo de abraçar, abrir: ỉnḳ ("envolver"), ḥpt ("abraçar").'],
  ['D33','𓂙','ẖn','braços remando','PI','Fonograma ẖn. Logograma de ẖnỉ ("remar").'],
  ['D34','𓂚','ꜥḥꜣ','braços com escudo e machado de guerra','I','Logograma de ꜥḥꜣ ("lutar").'],
  ['D35','𓂜','n','braços em gesto de negação','PID','Fonograma n. Logograma de n e nn ("não"). Determinativo de negação.'],
  ['D36','𓂝','ꜥ','antebraço (palma voltada para cima)','PI','Fonograma ꜥ. Logograma de ꜥ ("braço, mão").'],
  ['D37','𓂞','dỉ','antebraço com pão cônico','P','Fonograma dỉ em rdỉ ("dar").'],
  ['D38','𓂟','mỉ|m','antebraço com pão arredondado','PD','Fonograma mỉ ou m. Determinativo de ỉmỉ ("dar").'],
  ['D39','𓂠','','antebraço com tigela','D','Determinativo de oferecer, apresentar: ḥnk ("apresentar"), drp ("oferecer").'],
  ['D40','𓂡','hꜣỉ','antebraço com vara','ID','Determinativo de força, esforço: nḫt ("forte"). Logograma de hꜣỉ ("avaliar").'],
  ['D41','𓂢','nỉ','antebraço com palma voltada para baixo e braço superior dobrado','PD','Fonograma nỉ. Determinativo de braço: rmn ("braço, ombro").'],
  ['D42','𓂣','mḥ','antebraço com palma voltada para baixo e braço superior estendido','ID','Determinativo ou logograma de mḥ ("côvado").'],
  ['D43','𓂤','ḫw','antebraço com flagelo','PI','Fonograma ḫw. Logograma de ḫwỉ ("proteger").'],
  ['D44','𓂥','ḫrp','braço com cetro sekhem','ID','Determinativo e logograma de ḫrp ("controlar, dirigir, administrar").'],
  ['D45','𓂦','ḏsr','braço com varinha','ID','Determinativo e logograma de ḏsr ("abrir caminho; sagrado, santo").'],
  ['D46','𓂧','d','mão','PI','Fonograma d. Logograma de ḏrt ("mão").'],
  ['D47','𓂩','','mão com palma voltada para cima','PD','Determinativo de ḏrt ("mão") quando escrito com fonograma.'],
  ['D48','𓂪','šsp','mão sem polegar','I','Logograma de šsp ("palmo", medida).'],
  ['D49','𓂬','','punho fechado','D','Determinativo de agarrar: ꜣmm ("agarrar"), ḫfꜥ ("apoderar-se").'],
  ['D50','𓂭','ḏbꜥ','um dedo','ID','Logograma de ḏbꜥ ("dedo"), ḏbꜥ ("10.000"). Determinativo de exato, quando duplicado.'],
  ['D51','𓂷','','um dedo (horizontal)','D','Determinativo de ações ligadas a dedo, fruto, flor: ꜥnt ("unha"), ḫꜣỉ ("medir"), dḳr ("fruto").'],
  ['D52','𓂸','mt','falo','PID','Fonograma mt. Determinativo de macho: ꜥꜣ ("asno"), ṯꜣy ("macho"). Logograma de kꜣ ("touro").'],
  ['D53','𓂺','','falo com emissão','D','Determinativo de macho, pênis: m bꜣḥ ("na presença de"), ḏr bꜣḥ ("desde"), r bꜣḥ ("antes").'],
  ['D54','𓂻','ỉw','pernas caminhando','PD','Fonograma ỉw em ỉwỉ ("vir"). Determinativo de movimento.'],
  ['D55','𓂽','','pernas caminhando para trás','D','Determinativo de para trás: ꜥnn ("voltar"), ḫtḫt ("ser revertido").'],
  ['D56','𓂾','pd','perna','PD','Fonograma pd. Determinativo de perna, pé: rd ("perna"), pd ("joelho").'],
  ['D57','𓂿','','perna com faca','D','Determinativo de mutilar: ỉꜣṯ ("ser mutilado").'],
  ['D58','𓃀','b','pé','PI','Fonograma b. Logograma de bw ("lugar").'],
  ['D59','𓃁','ꜥb','pé e antebraço','P','Fonograma ꜥb.'],
  ['D60','𓃂','wꜥb','pé sob vaso do qual escorre água','I','Logograma de wꜥb ("puro, limpo").'],
  ['D61','𓃃','sꜣḥ','três dedos orientados para a esquerda','I','Logograma de sꜣḥ ("dedo do pé").'],
  ['D62','𓃄','','três dedos orientados para a direita','I','Igual a D61.'],
  ['D63','𓃅','','dois dedos orientados para a esquerda','I','Igual a D61.'],
  ['D64','𓃆','','mão com palma voltada para baixo','',''],
  ['D65','𓃇','ḥnsḳty','mecha de cabelo lateral','',''],
  ['D66','𓃈','spẖr','braço com cálamo de escrita','',''],
  ['D67','𓃉','','um ponto','',''],
  ['E1','𓃒','kꜣ','touro','ID','Determinativo de gado: ng ("touro"), mnmnt ("rebanho"). Logograma em kꜣ ("touro").'],
  ['E2','𓃓','kꜣ','touro em ataque','ID','Determinativo em smꜣ ("touro de combate"). Logograma em kꜣ nḫt ("touro vitorioso", epíteto do faraó).'],
  ['E3','𓃔','','bezerro','D','Determinativo em bḥs ("bezerro").'],
  ['E4','𓃕','','vaca sagrada','D','Determinativo em ḥsꜣt ("vaca sagrada").'],
  ['E5','𓃖','','vaca amamentando bezerro','D','Determinativo em ꜣms ("mostrar solicitude").'],
  ['E6','𓃗','','cavalo','ID','Logograma ou determinativo em ssmt ("cavalo"). Determinativo em ỉbr ("garanhão").'],
  ['E7','𓃘','','asno','D','Determinativo em ꜥꜣ ("asno").'],
  ['E8','𓃙','ỉb','cabrito','PD','Fonograma ỉb ("cabrito"). Determinativo em ꜥwt ("rebanhos").'],
  ['E9','𓃛','ỉw','búbalo recém-nascido','P','Fonograma ỉw. Em ỉwr ("conceber").'],
  ['E10','𓃝','','carneiro','D','Determinativo em bꜣ ("carneiro"), ẖnmw ("Khnum"), ꜥwt ḥḏt ("rebanhos brancos, ovelhas").'],
  ['E11','𓃞','','carneiro','D','Igual a E10.'],
  ['E12','𓃟','','porco','D','Determinativo em rrỉ ("porco").'],
  ['E13','𓃠','','gato','D','Determinativo em mỉw ("gato").'],
  ['E14','𓃡','','cão','D','Determinativo em ỉw ("cão"), ṯsm ("galgo").'],
  ['E15','𓃢','Inpw','canídeo deitado','ID','Determinativo ou logograma em Ỉnpw ("Anúbis").'],
  ['E16','𓃣','','canídeo deitado sobre santuário','ID','Igual a E15.'],
  ['E17','𓃥','sꜣb','chacal','ID','Determinativo ou logograma em sꜣb ("chacal" e "dignitário").'],
  ['E18','𓃧','Wp-wꜣwt','lobo sobre estandarte','ID','Determinativo ou logograma em Wp-wꜣwt ("Abridor de Caminhos, Upuaut").'],
  ['E19','𓃨','','lobo sobre estandarte com maça','ID','Igual a E18.'],
  ['E20','𓃩','stẖ','animal de Set','ID','Determinativo ou logograma em stẖ, stš ("Set"). Determinativo em ẖnnw ("tumulto"), shꜣ ("confusão").'],
  ['E21','𓃫','','animal de Set deitado','D','Determinativo em nšnỉ ("tempestade, fúria").'],
  ['E22','𓃬','mꜣỉ','leão','ID','Determinativo ou logograma em mꜣỉ ("leão").'],
  ['E23','𓃭','rw','leão deitado','PID','Fonograma rw. Determinativo ou logograma em rw ("leão").'],
  ['E24','𓃮','ꜣby','pantera','ID','Determinativo ou logograma em ꜣby ("pantera, leopardo").'],
  ['E25','𓃯','','hipopótamo','D','Determinativo em db, dỉb ("hipopótamo").'],
  ['E26','𓃰','ꜣbw','elefante','ID','Determinativo de ꜣbw ("elefante"). Logograma em ꜣbw ("Elefantina").'],
  ['E27','𓃱','','girafa','ID','Determinativo de sr ("predizer"). Determinativo ou logograma em mmỉ ("girafa").'],
  ['E28','𓃲','','órix','D','Determinativo em mꜣḥḏ ("órix").'],
  ['E29','𓃴','','gazela','D','Determinativo em gḥs ("gazela").'],
  ['E30','𓃵','','íbex','D','Determinativo em nꜣw, nrꜣw, nỉꜣ ("íbex").'],
  ['E31','𓃶','','cabra com coleira','D','Determinativo em sꜥḥ ("posto, privilégio").'],
  ['E32','𓃷','','babuíno','D','Determinativo em ỉꜥn ("babuíno"), ky ("macaco"), ḳnd ("furioso").'],
  ['E33','𓃸','','macaco','D','Determinativo de gf, gỉf ("macaco").'],
  ['E34','𓃹','wn','lebre','P','Fonograma wn. wnn ("ser, existir").'],
  ['E36','𓃻','ḏḥwty|nswt|nfr|sẖꜣ|sꜣ|ḏd','babuíno','',''],
  ['E37','𓃼','šbt','babuíno com recipiente e cesto','',''],
  ['E38','𓃽','kꜣ','touro de chifres longos','',''],
  ['F1','𓃾','kꜣ','cabeça de boi','I','Logograma em fórmulas de oferenda para kꜣ ("gado").'],
  ['F2','𓄀','','cabeça de boi em ataque','D','Determinativo em ḏnd ("fúria").'],
  ['F3','𓄁','ꜣt','cabeça de hipopótamo','PID','Fonograma ꜣt. Determinativo ou logograma em ("momento, ataque").'],
  ['F4','𓄂','ḥꜣt','parte dianteira de leão','I','Logograma em ḥꜣt ("frente"), ḥꜣty ("coração").'],
  ['F5','𓄃','šsꜣ','cabeça de búbalo','PID','Fonograma šsꜣ. Determinativo e logograma em šsꜣ ("hábil" e "oração").'],
  ['F6','𓄄','šsꜣ','parte dianteira de búbalo','PID','Igual a F5.'],
  ['F7','𓄅','šfyt','cabeça de carneiro','ID','Determinativo em šft ("cabeça de carneiro"). Determinativo ou logograma em šfyt ("valor, dignidade").'],
  ['F8','𓄆','','parte dianteira de carneiro','ID','Igual a F7.'],
  ['F9','𓄇','pḥty','cabeça de leopardo','ID','Determinativo ou logograma em pḥty ("força").'],
  ['F10','𓄈','','cabeça e pescoço de animal','D','Determinativo em ḫḫ ("garganta"), ꜥm ("engolir").'],
  ['F11','𓄉','','cabeça e pescoço de animal','D','Igual a F10.'],
  ['F12','𓄊','wsr','cabeça e pescoço de animal','PI','Fonograma wsr. Logograma em wsrt ("pescoço"). Em wsr ("poderoso").'],
  ['F13','𓄋','wp','chifres','PI','Fonograma wp. Logograma em wpt ("fronte, começo").'],
  ['F14','𓄍','wpt-rnpt','chifres com ramo de palmeira','I','Logograma de wpt-rnpt ("Abertura do Ano").'],
  ['F15','𓄎','','chifres com ramo de palmeira e sol','I','Igual a F14.'],
  ['F16','𓄏','ꜥb','chifre','PID','Fonograma ꜥb. Determinativo ou logograma em db ("chifre"), ꜥb ("chifre"). Em m-ꜥb ("junto com").'],
  ['F17','𓄐','ꜥbw','chifre e vaso do qual escorre água','ID','Determinativo ou logograma em ꜥbw ("purificação").'],
  ['F18','𓄑','bḥ|ḥw','presa','PID','Fonograma bḥ, ḥw. Determinativo e logograma em ỉbḥ ("dente"). Determinativo em sbḥ ("gritar").'],
  ['F19','𓄒','','mandíbula inferior de boi','D','Determinativo em ꜥrt ("mandíbula").'],
  ['F20','𓄓','ns','língua','PI','Fonograma ns. Em ns ("língua"). Logograma em ỉmy-r ("supervisor").'],
  ['F21','𓄔','sḏm|ỉdn','orelha de bovino','PID','Fonograma sḏm, ỉdn. Determinativo ou logograma em msḏr ("orelha"). Logograma de sḏm ("ouvir").'],
  ['F22','𓄖','pḥwy','quartos traseiros de leão','PI','Fonograma pḥ em ("alcançar"), pḥty ("força"). Logograma de pḥwy ("fim, traseira").'],
  ['F23','𓄗','ḫpš','pata dianteira de boi','ID','Determinativo ou logograma em ḫpš ("braço forte, perna").'],
  ['F24','𓄘','','F23 invertido','ID','Igual a F23.'],
  ['F25','𓄙','wḥm','pata traseira de boi','P','Fonograma wḥm em ("casco", "repetir").'],
  ['F26','𓄚','ẖn','pele de cabra','P','Fonograma ẖn. Em ẖnw ("interior"), ẖn ("aproximar-se").'],
  ['F27','𓄛','','pele de vaca com cauda dobrada','D','Determinativo em dḥr ("couro"), mskꜣ ("pele").'],
  ['F28','𓄜','sꜣb','pele de vaca com cauda reta','P','Fonograma sꜣb.'],
  ['F29','𓄝','st','pele de vaca trespassada por flecha','PID','Fonograma st. Determinativo e logograma de stỉ ("perfurar, atirar").'],
  ['F30','𓄞','šd','odre de água','P','Fonograma šd. Em šdỉ ("retirar"), šdw ("odre").'],
  ['F31','𓄟','ms','três peles atadas','P','Fonograma ms. Em msỉ ("dar à luz").'],
  ['F32','𓄡','ẖ','ventre de animal','PI','Fonograma ẖ. Logograma em ẖt ("ventre, corpo").'],
  ['F33','𓄢','sd','cauda','PID','Fonograma sd. Determinativo e logograma em sd ("cauda").'],
  ['F34','𓄣','ỉb','coração','','Igual a W21.'],
  ['F35','𓄤','nfr','coração e traqueia','P','Fonograma nfr. Em nfr ("bom, belo").'],
  ['F36','𓄥','smꜣ','pulmão e traqueia','','Igual a P8.'],
  ['F37','𓄦','ỉꜣt','coluna vertebral com costelas e medula espinhal','ID','Determinativo ou logograma em ỉꜣt ("costas, dorso"). Determinativo em psd ("costas").'],
  ['F38','𓄨','','coluna vertebral com costelas','D','Determinativo em psd ("costas").'],
  ['F39','𓄪','ỉmꜣḫ','coluna vertebral com medula espinhal','ID','Determinativo e logograma em ỉmꜣḫ ("espinha dorsal" e "veneração").'],
  ['F40','𓄫','ꜣw','coluna vertebral com medulas espinhais','P','Fonograma ꜣw.'],
  ['F41','𓄬','','vértebras','D','Determinativo em psd ("costas").'],
  ['F42','𓄭','spr','costela','','Igual a D13.'],
  ['F43','𓄮','','costelas','D','Determinativo em sḥpt ("costelas").'],
  ['F44','𓄯','ỉwꜥ|ỉsw','osso com carne','P','Fonograma ỉwꜥ, ỉsw. Em ỉwꜥ ("herdar"), sỉw ("trocar").'],
  ['F45','𓄰','dỉt','útero','ID','Determinativo ou logograma em dỉt ("vulva, vaca").'],
  ['F46','𓄲','ḳꜣb','intestino','','Igual a F49.'],
  ['F47','𓄴','','intestino','','Igual a F46.'],
  ['F48','𓄶','','intestino','','Igual a F46.'],
  ['F49','𓄷','','intestino','','Igual a F46.'],
  ['F50','𓄸','spḫr','combinação de F46 e S29','P','Fonograma spḫr ("escrever, copiar").'],
  ['F51','𓄹','ỉs|ỉst|ws','pedaço de carne','PD','Fonograma ỉs, ỉst, ws. Determinativo de ḥꜥ ("carne, corpo"), ỉwf ("carne").'],
  ['F52','𓄽','','excremento','D','Determinativo em ḥs ("excremento").'],
  ['F53','𓄾','mt','vara divina com cabeça de carneiro','',''],
  ['G1','𓄿','ꜣ','abutre egípcio','P','Fonograma ꜣ. Em ꜣ ("abutre").'],
  ['G2','𓅀','ꜣꜣ','dois abutres egípcios','P','Fonograma ꜣꜣ. Em mꜣꜣ ("ver").'],
  ['G3','𓅁','mꜣ','combinação de abutre egípcio e foice','P','Fonograma mꜣ. Em smꜣwy ("renovar").'],
  ['G4','𓅂','tyw','urubu','P','Fonograma tyw.'],
  ['G5','𓅃','ḥrw','falcão','I','Logograma de ḥrw ("Hórus").'],
  ['G6','𓅄','','combinação de falcão e flagelo','','Determinativo em bỉk ("falcão").'],
  ['G7','𓅆','','falcão sobre estandarte','D','Determinativo de ỉmn ("Amon"), nsw ("rei"); divino. Pronome de 1ª pessoa do singular ỉ, wỉ, com falante divino.'],
  ['G8','𓅉','Ḥr|bỉk','falcão sobre colar de contas','I','Logograma de ḥr/bỉk nbw ("Hórus de Ouro / falcão dourado").'],
  ['G9','𓅊','rꜥ-ḥrw-ꜣḫty','falcão com sol na cabeça','I','Logograma em rꜥ-ḥrw-ꜣḫty ("Rá-Horakhty").'],
  ['G10','𓅋','','falcão na barca de Sokar','D','Determinativo em skr ("Sokar"), ḥnw ("barca de Sokar").'],
  ['G11','𓅌','','imagem de falcão','D','Determinativo em ꜥšm, ꜥẖm, ꜥḫm ("imagem divina"), šnbt ("peito").'],
  ['G12','𓅎','','combinação de imagem de falcão e flagelo','D','Igual a G11.'],
  ['G13','𓅏','ḥrw','imagem de falcão com duas plumas','ID','Logograma de ḥrw nḫny ("Hórus de Hieracômpolis"). Determinativo em spdw ("Sopdu").'],
  ['G14','𓅐','mwt|mt','abutre','P','Fonograma mwt, mt. Em mwt ("mãe").'],
  ['G15','𓅑','','combinação de abutre e flagelo','D','Determinativo em mwt ("Mut").'],
  ['G16','𓅒','nbty','abutre e cobra, cada um sobre cesto','I','Logograma em nbty ("Duas Senhoras", título do faraó).'],
  ['G17','𓅓','m','coruja','P','Fonograma m.'],
  ['G18','𓅔','mm','duas corujas','P','Fonograma mm.'],
  ['G19','𓅕','mỉ|m','combinação de coruja e antebraço com pão cônico','P','Fonograma mỉ, m.'],
  ['G20','𓅖','mỉ|m','combinação de coruja e antebraço','P','Igual a G19.'],
  ['G21','𓅘','nḥ','galinha-d\'angola','P','Fonograma nḥ. Em nḥḥ ("eternidade").'],
  ['G22','𓅙','ḏb|ḏbt','poupa','P','Fonograma ḏb/ḏbt.'],
  ['G23','𓅚','rḫyt','aiveca','ID','Determinativo e logograma em rḫyt ("plebeus").'],
  ['G24','𓅛','','aiveca com asas retorcidas','ID','Igual a G23.'],
  ['G25','𓅜','ꜣḫ','íbis-calva-do-norte','P','Fonograma ꜣḫ. Em ("espírito").'],
  ['G26','𓅝','','íbis sagrado sobre estandarte','D','Determinativo em ḏḥwty ("Tot").'],
  ['G27','𓅟','dšr','flamingo','P','Fonograma dšr. Em dšr ("vermelho", "flamingo").'],
  ['G28','𓅠','gm','íbis-de-face-brilhante','P','Fonograma gm. Em gmỉ ("encontrar").'],
  ['G29','𓅡','bꜣ','cegonha-bico-de-sela','P','Fonograma bꜣ. Em ("ba, alma").'],
  ['G30','𓅢','bꜣw','três cegonhas-bico-de-sela','I','Logograma em bꜣw ("almas, poder").'],
  ['G31','𓅣','','garça','D','Determinativo em šnty ("garça").'],
  ['G32','𓅤','bꜥḫỉ','garça sobre poleiro','ID','Determinativo ou logograma em bꜥḫỉ ("inundado").'],
  ['G33','𓅥','','garça-boieira','D','Determinativo de sdꜣ ("tremer").'],
  ['G34','𓅦','','avestruz','D','Determinativo em nỉw ("avestruz").'],
  ['G35','𓅧','ꜥḳ','cormorão','P','Fonograma ꜥḳ. Em ꜥḳ ("entrar").'],
  ['G36','𓅨','wr','andorinha','P','Fonograma wr. Em wr ("grande").'],
  ['G37','𓅪','','pardal','D','Determinativo em nḏs ("pequeno"), bỉn ("mau").'],
  ['G38','𓅬','gb','ganso','PD','Fonograma gb. Em gb ("Geb"). Determinativo em wfꜣ ("falar"), wsf ("ocioso"), ḥtm ("perecer").'],
  ['G39','𓅭','sꜣ','pato-de-cauda-pontiaguda','PD','Fonograma sꜣ. Em sꜣ ("filho"). Determinativo em sỉ ("pato").'],
  ['G40','𓅮','pꜣ','pato-de-cauda-pontiaguda em voo','P','Fonograma pꜣ. Em pꜣ ("o, a", "voar").'],
  ['G41','𓅯','ḫn','pato-de-cauda-pontiaguda pousando','P','Fonograma ḫn. Em ḫnỉ ("pousar, deter-se"), ḫn ("fala"), ḳmꜣ ("lançar", "criar").'],
  ['G42','𓅰','wšꜣ','marreco','ID','Determinativo e logograma em wšꜣ ("engordar"), ḏfꜣw ("provisões").'],
  ['G43','𓅱','w','codorniz jovem','P','Fonograma w.'],
  ['G44','𓅳','ww','duas codornizes jovens','P','Fonograma ww. Em pḥww ("fim, terras finais").'],
  ['G45','𓅴','wꜥ','combinação de codorniz jovem e antebraço','P','Fonograma wꜥ. Em wꜥw ("soldado").'],
  ['G46','𓅶','mꜣw','combinação de codorniz jovem e foice','P','Fonograma mꜣw.'],
  ['G47','𓅷','ṯꜣ','patinho','P','Fonograma ṯꜣ. Em ṯꜣy ("macho").'],
  ['G48','𓅸','sš','três patinhos em ninho','I','Logograma em sš ("ninho").'],
  ['G49','𓅹','sš','três patinhos em lago','ID','Determinativo ou logograma em sš ("ninho").'],
  ['G50','𓅺','rḫty','dois pernaltas','I','Logograma de rḫty ("lavadeiro").'],
  ['G51','𓅻','','ave bicando peixe','D','Determinativo em ḥꜣm ("pescar").'],
  ['G52','𓅼','','ganso apanhando grão','D','Determinativo em snm ("alimentar").'],
  ['G53','𓅽','bꜣ','ave de cabeça humana com tigela com fumaça','I','Logograma em bꜣ ("ba, alma").'],
  ['G54','𓅾','snḏ','ave depenada','P','Fonograma snḏ. Em snḏ ("temer").'],
  ['H1','𓅿','ꜣpd','cabeça de pato-de-cauda-pontiaguda','ID','Logograma em ꜣpd ("ave"). Determinativo em wšn ("torcer o pescoço de aves").'],
  ['H2','𓆀','mꜣꜥ|wšm|pꜣḳ','cabeça de garça','PD','Fonograma mꜣꜥ, wšm, pꜣḳ. Determinativo em mꜣꜥ ("têmpora da cabeça", "verdadeiro").'],
  ['H3','𓆁','pꜣḳ','cabeça de colhereiro','P','Fonograma pꜣḳ.'],
  ['H4','𓆂','nr','cabeça de abutre','PD','Fonograma nr. Determinativo em nrt ("abutre").'],
  ['H5','𓆃','','asa','D','Determinativo em ḏnḥ ("asa").'],
  ['H6','𓆄','šw','pena','PID','Fonograma šw. Logograma em šwt ("pena"). Determinativo e logograma em mꜣꜥt ("verdade").'],
  ['H7','𓆆','šꜣ|šꜣt','pata de ave','P','Fonograma šꜣ, šꜣt. Em šꜣt ("Shat", localidade).'],
  ['H8','𓆇','sꜣ','ovo','ID','Logograma em sꜣ ("filho"). Determinativo de sḥwt ("ovo").'],
  ['I1','𓆈','ꜥšꜣ','lagartixa','PD','Fonograma ꜥšꜣ. Determinativo de lagarto: ꜥšꜣ ("lagarto") e ꜥšꜣ ("muitos, numeroso").'],
  ['I2','𓆉','štyw','tartaruga','ID','Determinativo ou logograma de štyw ("tartaruga").'],
  ['I3','𓆊','','crocodilo','ID','Determinativo ou logograma de crocodilo: msḥ ("crocodilo"), ꜣd ("agressivo"). Logograma de ỉty ("soberano"), quando reduplicado.'],
  ['I4','𓆋','','crocodilo sobre santuário','D','Determinativo de sbk ("Sobek").'],
  ['I5','𓆌','','crocodilo com cauda curvada','D','Determinativo em sꜣḳ ("juntar, reunir").'],
  ['I6','𓆎','km','escamas de crocodilo','','Igual a Aa4.'],
  ['I7','𓆏','wḥm','rã','ID','Determinativo em ḥḳt ("Heket"). Logograma de wḥm ꜥnḫ ("repetição da vida").'],
  ['I8','𓆐','ḥfn','girino','ID','Determinativo de ḥfnr ("girino"). Logograma de ḥfn ("100.000").'],
  ['I9','𓆑','f','víbora cornuda','PD','Fonograma f. Determinativo em ỉt ("pai").'],
  ['I10','𓆓','ḏ','cobra em repouso','P','Fonograma ḏ.'],
  ['I11','𓆕','ḏḏ','duas cobras','P','Fonograma ḏḏ.'],
  ['I12','𓆗','','cobra ereta como na testa do faraó','D','Determinativo em ꜥỉrt ("uraeus"). Determinativo de deusas.'],
  ['I13','𓆘','','cobra ereta sobre cesto','D','Determinativo em wꜣḏt ("Uadjet").'],
  ['I14','𓆙','','serpente','D','Determinativo de ḥfꜣw ("cobra, serpente").'],
  ['I15','𓆚','','serpente','D','Igual a I14.'],
  ['K1','𓆛','ỉn','tilápia','P','Fonograma ỉn. Em ỉnt ("peixe bulti").'],
  ['K2','𓆜','bw','barbo','P','Fonograma bw. Em bwt ("abominação").'],
  ['K3','𓆝','ꜥḏ','taininha','P','Fonograma ꜥḏ. Em ꜥḏ-mr ("administrador de distrito").'],
  ['K4','𓆞','ẖꜣ','peixe-elefante','P','Fonograma ẖꜣ. Em ẖꜣt ("oxirrinco").'],
  ['K5','𓆟','bs','Petrocephalus bane','PD','Fonograma bs. Determinativo em bsỉ ("introduzir").'],
  ['K6','𓆠','nšmt','escama de peixe','ID','Determinativo e logograma em nšmt ("escama de peixe").'],
  ['K7','𓆡','','baiacu','D','Determinativo de špt ("descontente").'],
  ['K8','𓆢','nꜥr','bagre','',''],
  ['L1','𓆣','ḫpr','escaravelho-rola-bosta','P','Fonograma ḫpr. Em ḫpr ("ser, existir, tornar-se").'],
  ['L2','𓆤','bỉty','abelha','I','Logograma de bỉty ("rei do Baixo Egito").'],
  ['L3','𓆦','','mosca','D','Determinativo em ꜥff ("mosca").'],
  ['L4','𓆧','','gafanhoto','D','Determinativo em snḥm ("gafanhoto").'],
  ['L5','𓆨','','centopeia','D','Determinativo de spꜣ ("centopeia").'],
  ['L6','𓆩','','concha','','Igual a N33.'],
  ['L7','𓆫','srḳt','escorpião','ID','Determinativo e logograma em srḳt ("Serket").'],
  ['L8','𓆬','','','',''],
  ['M1','𓆭','ỉmꜣ','árvore','PD','Fonograma ỉmꜣ. Determinativo de nhwt, mnw ("árvores").'],
  ['M2','𓆰','ḥn','planta','PD','Fonograma ḥn. Em ḥnỉ ("junco"), ḥnw ("vaso"). Determinativo em ỉs ("tumba").'],
  ['M3','𓆱','ḫt','galho','P','Fonograma ḫt. Em ḫt ("madeira"), ḫtyw ("terraço"), nḫt ("forte").'],
  ['M4','𓆳','rnpt','ramo de palmeira','ID','Logograma em rnpt ("ano"), ḥsbt ("ano de reinado"). Determinativo em tr ("tempo").'],
  ['M5','𓆴','tr','combinação de ramo de palmeira e pão achatado','ID','Determinativo ou logograma em tr ("tempo, estação").'],
  ['M6','𓆵','tr','combinação de ramo de palmeira e boca','ID','Determinativo ou logograma em tr ("tempo, estação").'],
  ['M7','𓆶','rnpỉ','combinação de ramo de palmeira e banquinho','ID','Determinativo ou logograma em rnpỉ ("jovem").'],
  ['M8','𓆷','ꜣḫt','lago com flores de lótus','PI','Fonograma šꜣ. Em šꜣ ("pântano"). Logograma de ꜣḫt ("Inundação", estação).'],
  ['M9','𓆸','','flor de lótus','ID','Determinativo ou logograma em sšn ("lírio").'],
  ['M10','𓆹','','botão de lótus com haste reta','D','Determinativo em nḥbt ("botão de lírio").'],
  ['M11','𓆻','wdn','flor em haste longa e retorcida','ID','Determinativo ou logograma em wdn ("oferecer").'],
  ['M12','𓆼','ḫꜣ','uma planta de lótus','P','Fonograma ḫꜣ. Em ḫꜣw nw sšn ("plantas de lírio"), ḫꜣ ("1.000"), sḫꜣ ("lembrar").'],
  ['M13','𓇅','wꜣḏ|wḏ','haste de papiro','P','Fonograma wꜣḏ, wḏ.'],
  ['M14','𓇆','wꜣḏ','combinação de papiro e cobra','P','Fonograma wꜣḏ. Em wꜣḏ wr ("o mar, o Grande Verde").'],
  ['M15','𓇇','ꜣḫ','touceira de papiro com botões','PD','Fonograma ꜣḫ. Em ꜣḫ-bỉt ("Quêmis"). Determinativo de papiro.'],
  ['M16','𓇉','ḥꜣ','touceira de papiro','PD','Fonograma ḥꜣ. Em ḥꜣḳ ("capturar"). Determinativo em ("o Delta").'],
  ['M17','𓇋','ỉ','junco','P','Fonograma ỉ. Fonograma y, quando duplicado.'],
  ['M18','𓇍','ỉ','combinação de junco e pernas caminhando','P','Fonograma ỉ. Em ỉỉ ("vir").'],
  ['M19','𓇎','ꜥꜣbt','bolos cônicos empilhados entre junco e clava','ID','Determinativo e logograma em ꜥꜣbt ("oferenda").'],
  ['M20','𓇏','','campo de juncos','D','Determinativo de sḫt ("brejo"), sm ("ocupação").'],
  ['M21','𓇐','','juncos com raiz','D','Determinativo em sm ("planta", "ajudar").'],
  ['M22','𓇑','nḫb','junco','P','Fonograma nḫb. Fonograma nn, quando duplicado. Em nḫbt ("germinação", "Nekhbet").'],
  ['M23','𓇓','sw','sedge','PI','Fonograma sw. Logograma de nswt ("rei").'],
  ['M24','𓇔','rsw','combinação de sedge e boca','I','Logograma de rsw ("sul").'],
  ['M25','𓇖','','combinação de sedge em flor e boca','I','Igual a M24.'],
  ['M26','𓇗','šmꜥ','sedge em flor','PI','Fonograma šmꜥ. Logograma de šmꜥw ("Alto Egito").'],
  ['M27','𓇘','šmꜥ','combinação de sedge em flor e antebraço','P','Fonograma šmꜥ.'],
  ['M28','𓇙','','combinação de sedge em flor e cabresto','I','Logograma no título wr mḏw šmꜥw ("O Maior das Dezenas do Alto Egito").'],
  ['M29','𓇛','nḏm','vagem de alfarroba','P','Fonograma nḏm. Em nḏm ("doce").'],
  ['M30','𓇜','bnr','raiz','ID','Determinativo ou logograma de bnr ("doce").'],
  ['M31','𓇝','','rizoma','D','Determinativo em rd ("crescer").'],
  ['M32','𓇟','','rizoma','D','Igual a M31.'],
  ['M33','𓇠','','3 grãos na horizontal','I','Logograma em ỉt ("cevada, grão").'],
  ['M34','𓇣','btỉ','espiga de trigo emmer','ID','Determinativo ou logograma em btỉ ("trigo emmer").'],
  ['M35','𓇤','','monte de grãos','','Igual a X1.'],
  ['M36','𓇥','ḏr','feixe de linho','','Igual a U30.'],
  ['M37','𓇦','ḏr','feixe de linho','P','Fonograma ḏr.'],
  ['M38','𓇧','','feixe largo de linho','D','Determinativo em mḥꜥ ("linho"), dmꜣ ("atar junto").'],
  ['M39','𓇨','','cesto de frutas ou grãos','D','Determinativo em rnpt ("legumes, vegetais").'],
  ['M40','𓇩','','feixe de juncos','','Igual a P11.'],
  ['M41','𓇫','','pedaço de madeira','D','Determinativo em ꜥš ("cedro").'],
  ['M42','𓇬','wn','flor','P','Fonograma wn. Em wnm ("comer"), ḥwn ("ser jovem").'],
  ['M43','𓇭','ỉrp','videira em latada','ID','Determinativo ou logograma em ỉrp ("vinho").'],
  ['M44','𓇮','','espinho','D','Determinativo de spd ("afiado").'],
  ['N1','𓇯','pt','céu','','Igual a N39.'],
  ['N2','𓇰','grḥ','céu com cetro','ID','Determinativo ou logograma de grḥ ("noite").'],
  ['N3','𓇱','','céu com cetro','ID','Igual a N2.'],
  ['N4','𓇲','šnyt','céu com chuva','ID','Determinativo ou logograma de šnyt ("chuva"), ỉꜣdt ("orvalho").'],
  ['N5','𓇳','rꜥ','sol','','Igual a Aa1.'],
  ['N6','𓇴','','sol com uraeus','ID','Determinativo ou logograma em rꜥ ("sol, Rá").'],
  ['N7','𓇵','','combinação de sol e tronco de açougueiro','D','Determinativo de ẖrt-hrw ("curso do dia").'],
  ['N8','𓇶','wbn','raios de sol','PID','Fonograma wbn. Determinativo ou logograma de ꜣḫw ("luz do sol"), psḏ ("brilhar"), wbn ("nascer, surgir").'],
  ['N9','𓇷','psḏ','lua com metade inferior encoberta','P','Fonograma psḏ. Em psḏt ("Enéade").'],
  ['N10','𓇸','psḏ','lua com seção inferior encoberta','P','Igual a N9.'],
  ['N11','𓇹','ꜣbd','lua crescente','ID','Logograma de ꜣbd ("mês"). Determinativo de ỉꜥḥ ("lua").'],
  ['N12','𓇺','','lua crescente','D','Determinativo de ỉꜥḥ ("lua").'],
  ['N13','𓇻','mḏdỉwnt','combinação de lua crescente e estrela','I','Logograma de mḏdỉwnt ("festa da quinzena").'],
  ['N14','𓇼','sbꜣ|dwꜣ','estrela','PI','Fonograma sbꜣ, dwꜣ. Em sbꜣ ("estrela"), dwꜣ ("manhã"). Logograma de wnwt ("hora").'],
  ['N15','𓇽','dwꜣt','estrela em círculo','I','Logograma em dwꜣt ("Duat, mundo inferior").'],
  ['N16','𓇾','tꜣ','terra com grãos','PD','Fonograma tꜣ. Em tꜣ ("terra"). Determinativo em ḏt ("eternidade").'],
  ['N17','𓇿','tꜣ','terra','PD','Igual a N16.'],
  ['N18','𓈀','ỉw','trato arenoso','I','Logograma em ỉw ("ilha").'],
  ['N19','𓈃','ꜣḫt','dois tratos arenosos','I','Logograma em ꜣḫt ("horizonte"), ḥrw-ꜣḫty ("Horakhty").'],
  ['N20','𓈄','wḏb','língua de terra','PD','Fonograma wḏb. Em wḏb ("margem"). Determinativo em ḥꜣb-sd ("Festa Sed").'],
  ['N21','𓈅','ỉdb','língua de terra curta','I','Logograma em ỉdb ("margem"), ỉdbwy ("as duas margens").'],
  ['N22','𓈆','','língua de terra larga','D','Determinativo em ꜥḥt ("campo"), sḫt ("campo").'],
  ['N23','𓈇','','canal de irrigação','','Igual a O45.'],
  ['N24','𓈈','spꜣt','sistema de canais de irrigação','ID','Determinativo ou logograma em spꜣt ("nomo", província).'],
  ['N25','𓈉','ḫꜣst','três colinas','I','Logograma em ḫꜣst ("terra estrangeira, região montanhosa").'],
  ['N26','𓈋','ḏw','duas colinas','P','Fonograma ḏw ("montanha").'],
  ['N27','𓈌','ꜣḫt','sol sobre montanha','I','Logograma em ꜣḫt ("horizonte").'],
  ['N28','𓈍','ḫꜥ','raios de sol sobre colina','P','Fonograma ḫꜥ. Em ḫꜥ ("surgir, aparecer em glória").'],
  ['N29','𓈎','ḳ','encosta de colina','P','Fonograma ḳ.'],
  ['N30','𓈏','ỉꜣt','montículo de terra','ID','Determinativo ou logograma em ỉꜣt ("monte, elevação").'],
  ['N31','𓈐','wꜣt','caminho com arbustos','ID','Determinativo e logograma em wꜣt ("caminho, estrada").'],
  ['N32','𓈑','','torrão de argila','D','Determinativo em sỉn ("argila").'],
  ['N33','𓈒','','grão','D','Determinativo em nbw ("ouro").'],
  ['N34','𓈔','bỉꜣ','lingote de metal','I','Logograma em bỉꜣ, ḥmt ("cobre").'],
  ['N35','𓈖','n','ondulação de água','P','Fonograma n.'],
  ['N36','𓈘','mr','canal','P','Fonograma mr. Em mr ("canal").'],
  ['N37','𓈙','š','lago','P','Fonograma š. Em š ("lago, tanque").'],
  ['N38','𓈛','š','lago profundo','P','Igual a N37.'],
  ['N39','𓈜','š','lago com água','P','Igual a N37.'],
  ['N40','𓈝','šm','lago com pernas','P','Fonograma šm. Em šm ("ir").'],
  ['N41','𓈞','ḥm','poço com ondulação de água','PD','Fonograma ḥm. Em ḥmt ("esposa"). Determinativo em bỉꜣ ("cobre").'],
  ['N42','𓈟','ḥm','poço com fio de água','PD','Igual a N41.'],
  ['O1','𓉐','pr','casa','P','Fonograma pr. Em pr ("casa"), prỉ ("sair").'],
  ['O2','𓉒','pr-ḥḏ','combinação de casa e maça de cabeça arredondada','I','Logograma em pr-ḥḏ ("tesouro, casa branca").'],
  ['O3','𓉓','prt-ḫrw','combinação de casa, remo, pão alto e jarra de cerveja','I','Logograma em prt-ḫrw ("oferenda invocatória").'],
  ['O4','𓉔','h','abrigo','P','Fonograma h.'],
  ['O5','𓉕','nm','muro sinuoso a partir do canto superior esquerdo','P','Fonograma nm. Em nmỉ ("atravessar").'],
  ['O6','𓉗','ḥwt','recinto','I','Logograma em ḥwt ("templo, tumba, recinto").'],
  ['O7','𓉞','','combinação de recinto e pão achatado','I','Igual a O6.'],
  ['O8','𓉟','ḥwt-ꜥꜣ','combinação de recinto, pão achatado e coluna de madeira','I','Logograma em ḥwt-ꜥꜣ ("grande templo, recinto").'],
  ['O9','𓉠','nbt-ḥyt','combinação de recinto, pão achatado e cesto','I','Logograma em nbt-ḥyt ("Néftis").'],
  ['O10','𓉡','ḥwt-ḥrw','combinação de recinto e falcão','I','Logograma em ḥwt-ḥrw ("Hathor").'],
  ['O11','𓉥','ꜥḥ','palácio','',''],
  ['O12','𓉦','ꜥḥ','combinação de palácio e antebraço','I','Logograma em ꜥḥ ("palácio").'],
  ['O13','𓉧','','recinto ameado','D','Determinativo em sbḫ ("cercar"), sbḫt ("portal").'],
  ['O14','𓉨','','parte de recinto ameado','D','Igual a O13.'],
  ['O15','𓉩','wsḫt','recinto com taça e pão achatado','I','Logograma em wsḫt ("salão, sala hipostila").'],
  ['O16','𓉪','tꜣyt','portal com serpentes','ID','Determinativo ou logograma em tꜣyt ("cortina"), tꜣyty ("o da cortina", título de vizir).'],
  ['O17','𓉫','','portal aberto com serpentes','ID','Igual a O16.'],
  ['O18','𓉬','kꜣr','santuário de perfil','ID','Determinativo ou logograma em kꜣr ("santuário, capela").'],
  ['O19','𓉭','','santuário com cerca','D','Determinativo em pr-wr ("Grande Casa").'],
  ['O20','𓉯','','santuário','D','Determinativo em ỉtrt ("fileira de santuários"), ḫm ("santuário").'],
  ['O21','𓉱','sḥ-nṯr','fachada de santuário','ID','Determinativo ou logograma em sḥ-nṯr ("santuário divino").'],
  ['O22','𓉲','sḥ','barraca com mastro','ID','Determinativo ou logograma em sḥ ("conselho", "cabana, pavilhão").'],
  ['O23','𓉳','ḥꜣb-sd','plataforma dupla','I','Logograma em ḥꜣb-sd ("Festa Sed").'],
  ['O24','𓉴','','pirâmide','D','Determinativo em mr ("pirâmide").'],
  ['O25','𓉶','tḫn','obelisco','ID','Determinativo ou logograma em tḫn ("obelisco").'],
  ['O26','𓉸','wḏ','estela','ID','Determinativo ou logograma em wḏ ("estela").'],
  ['O27','𓉹','','salão de colunas','D','Determinativo em ḫꜣ ("repartição"), ḫꜣwy ("noite").'],
  ['O28','𓉺','ỉwn','coluna','P','Fonograma ỉwn. Em ỉwnw ("Heliópolis"), ỉwn ("coluna").'],
  ['O29','𓉻','ꜥꜣ','coluna de madeira horizontal','P','Fonograma ꜥꜣ. Em ꜥꜣ ("grande").'],
  ['O30','𓉽','sḫnt','suporte','','Igual a F45.'],
  ['O31','𓉿','','porta','D','Determinativo em ꜥꜣ ("porta"), sn, wn ("abrir").'],
  ['O32','𓊀','','portal','D','Determinativo em sbꜣ ("porta"), sbḫt ("portal").'],
  ['O33','𓊁','','fachada de palácio','D','Determinativo em srḫ ("serekh, fachada de palácio").'],
  ['O34','𓊃','s','ferrolho de porta','P','Fonograma s. Em s ("tranca").'],
  ['O35','𓊄','s','combinação de ferrolho e pernas','P','Fonograma s. Em sbỉ ("ir", "perecer"), ms ("trazer").'],
  ['O36','𓊅','ỉnb','muro','','Igual a V29.'],
  ['O37','𓊊','','muro caindo','D','Determinativo em whn ("derrubar"), gsꜣ ("inclinar").'],
  ['O38','𓊋','ḳnbt','canto de muro','I','Logograma em ḳnbt ("tribunal, canto, magistrados").'],
  ['O39','𓊌','','pedra','D','Determinativo em ỉnr ("pedra"), dbnỉ ("deben", peso), ḏbt ("tijolo").'],
  ['O40','𓊍','','degrau simples','D','Determinativo em rwd ("escadaria"), ḫtyw ("terraço").'],
  ['O41','𓊎','','escadaria dupla','D','Determinativo em ḳꜣy ("lugar alto"), ỉꜥr ("subir").'],
  ['O42','𓊏','šsp','cerca','',''],
  ['O43','𓊐','','cerca baixa','','Igual a O42.'],
  ['O44','𓊑','ỉꜣt','emblema de Min','I','Logograma em ỉꜣt ("posto, cargo").'],
  ['O45','𓊒','ỉpt','edifício de cúpula','ID','Determinativo ou logograma em ỉpt ("harém").'],
  ['O46','𓊓','','edifício de cúpula','ID','Igual a O45.'],
  ['O47','𓊔','nḫn','montículo cercado','I','Logograma em nḫn ("Hieracômpolis").'],
  ['O48','𓊕','','montículo cercado','','Igual a S10.'],
  ['O49','𓊖','nỉwt','aldeia','I','Logograma em nỉwt ("cidade").'],
  ['O50','𓊗','sp','eira','P','Fonograma sp. Em sp ("ocasião, vez, evento"), sp sn ("duas vezes").'],
  ['O51','𓊚','šnwt','monte de grãos','ID','Determinativo ou logograma em šnwt ("celeiro").'],
  ['P1','𓊛','','','D','Determinativo de barcos. Em dpt ("navio"), ḥꜥw ("navios"), ḫdỉ ("navegar rio abaixo").'],
  ['P2','𓊝','','navio a vela','D','Determinativo em ḫntỉ ("navegar rio acima").'],
  ['P3','𓊞','','barca sagrada','D','Determinativo de wỉꜣ ("barca sagrada"), ḏꜣỉ ("atravessar").'],
  ['P4','𓊠','wḥꜥ','barco com rede','P','Fonograma wḥꜥ. Em wḥꜥ ("pescador").'],
  ['P5','𓊡','ṯꜣw','vela','ID','Determinativo ou logograma em ṯꜣw ("vento, sopro"). Determinativo de mḥyt ("vento norte").'],
  ['P6','𓊢','ꜥḥꜥ','mastro','P','Fonograma ꜥḥꜥ. Em ꜥḥꜥ ("ficar de pé").'],
  ['P7','𓊣','ꜥḥꜥ','combinação de mastro e antebraço','P','Igual a P6.'],
  ['P8','𓊤','ḫrw','remo','P','Fonograma ḫrw. Em mꜣꜥ ḫrw ("justo de voz"), ḫrw ("voz"), ḫrwy ("inimigo").'],
  ['P9','𓊥','','combinação de remo e víbora cornuda','I','Logograma de ḫr.fy ("diz, disse").'],
  ['P10','𓊦','','leme','D','Determinativo em ḥmw ("remo de governo"), ḥmy ("timoneiro").'],
  ['P11','𓊧','','poste de amarração','D','Determinativo em mnỉt ("poste de amarração").'],
  ['Q1','𓊨','st|ws','trono','P','Fonograma st, ws. Em st ("assento, lugar"), wsỉr ("Osíris"), ḥtm ("perecer").'],
  ['Q2','𓊩','ws','cadeirinha de mãos','P','Fonograma ws. Em wsỉr ("Osíris").'],
  ['Q3','𓊪','p','banquinho','','Igual a O47.'],
  ['Q4','𓊫','','apoio de cabeça','D','Determinativo em wrs ("apoio de cabeça").'],
  ['Q5','𓊬','','caixa','D','Determinativo em hn ("caixa"), ꜥfdt ("arca").'],
  ['Q6','𓊭','ḳrs','sarcófago','ID','Determinativo ou logograma em ḳrs ("sepultar"), ḳrsw ("sarcófago").'],
  ['Q7','𓊮','','braseiro','D','Determinativo de fogo. Em ḫt ("fogo"), sḏt ("chama"), srf ("temperatura").'],
  ['R1','𓊯','ḫꜣt','mesa alta com oferendas','ID','Determinativo ou logograma em ḫꜣt, ḫꜣwt ("mesa de oferendas").'],
  ['R2','𓊰','','mesa com fatias de pão','ID','Igual a R1.'],
  ['R3','𓊲','wḥḏw','mesa baixa com oferendas','ID','Determinativo ou logograma em wḥḏw ("mesa de oferendas").'],
  ['R4','𓊵','ḥtp','pão sobre esteira','P','Fonograma ḥtp. Em ḥtp ("altar, repousar, estar satisfeito").'],
  ['R5','𓊶','kꜣp','incensário estreito','ID','Determinativo ou logograma em kꜣp ("defumar").'],
  ['R6','𓊷','','incensário largo','ID','Igual a R5.'],
  ['R7','𓊸','sntr','tigela com fumaça','ID','Determinativo ou logograma em sntr ("incenso").'],
  ['R8','𓊹','nṯr','tecido sobre mastro','','Igual a T3.'],
  ['R9','𓊺','bd','combinação de tecido sobre mastro e bolsa','ID','Determinativo ou logograma em bd ("incenso").'],
  ['R10','𓊻','ẖrt-nṯr','combinação de tecido sobre mastro, tronco de açougueiro e encosta de colina','I','Logograma em ẖrt-nṯr ("necrópole").'],
  ['R11','𓊽','ḏd','coluna djed','P','Fonograma ḏd. Em ḏd ("estável"), ḏdw ("Busíris").'],
  ['R12','𓊾','','estandarte','D','Determinativo em ỉꜣt ("estandarte").'],
  ['R13','𓊿','ỉmnt','falcão e pena sobre estandarte','I','Logograma em ỉmnt ("Oeste"), wnmỉ ("direita").'],
  ['R14','𓋀','ỉmnt','Emblema do Oeste','I','Logograma em ỉmnt ("Oeste"), wnmỉ ("direita").'],
  ['R15','𓋁','ỉꜣbt','lança, Emblema do Leste','I','Logograma em ỉꜣbt ("Leste"), ỉꜣby ("esquerda").'],
  ['R16','𓋂','','cetro com penas e cordão','ID','Determinativo ou logograma em wḫ ("emblema de Qus").'],
  ['R17','𓋄','tꜣ-wr','peruca sobre mastro','ID','Determinativo ou logograma em tꜣ-wr ("Tinis", nomo de Abidos).'],
  ['R18','𓋅','','combinação de peruca sobre mastro e sistema de canais de irrigação','ID','Igual a R17.'],
  ['R19','𓋆','','cetro com pena','D','Determinativo em wꜣst ("Tebas").'],
  ['R20','𓋇','sšt','flor com chifres','I','Logograma em sšt ("Seshat").'],
  ['R21','𓋈','','flor com chifres','I','Igual a R20.'],
  ['R22','𓋉','ḫm','dois belemnites estreitos','PI','Fonograma ḫm. Em ḫm ("santuário"). Com o estandarte, logograma em mnw ("Min").'],
  ['R23','𓋊','ḫm','dois belemnites largos','PI','Igual a R22.'],
  ['R24','𓋋','','dois arcos atados na horizontal','D','Determinativo em nỉt ("Neit").'],
  ['R25','𓋌','','dois arcos atados na vertical','D','Igual a R24.'],
  ['R26','𓋍','smꜣ-tꜣwy','combinação de terra, pulmão e traqueia, lírio e papiro','',''],
  ['R27','𓋎','nt','duas flechas cruzadas sobre escudo','',''],
  ['R28','𓋏','bꜣt','Bat','',''],
  ['R29','𓋐','ỉtrt|ỉtrty','nicho com serpente','',''],
  ['S1','𓋑','ḥḏt','coroa branca','ID','Determinativo ou logograma em ḥḏt ("coroa branca").'],
  ['S2','𓋒','ḥḏt','combinação de coroa branca e cesto','ID','Determinativo ou logograma em ḥḏt ("coroa branca").'],
  ['S3','𓋔','n','coroa vermelha','PID','Fonograma n. Determinativo ou logograma em dšrt ("coroa vermelha").'],
  ['S4','𓋕','n','combinação de coroa vermelha e cesto','PID','Igual a S3.'],
  ['S5','𓋖','sḫmty','coroa pschent','ID','Determinativo ou logograma em sḫmty ("dupla coroa").'],
  ['S6','𓋗','','combinação de coroa pschent e cesto','ID','Igual a S5.'],
  ['S7','𓋙','ḫprš','coroa azul','ID','Determinativo ou logograma em ḫprš ("coroa azul").'],
  ['S8','𓋚','ꜣtf','coroa atef','ID','Determinativo ou logograma em ꜣtf ("coroa atef").'],
  ['S9','𓋛','šwty','coroa shuty (duas penas de falcão)','ID','Determinativo ou logograma em šwty ("dupla pluma").'],
  ['S10','𓋜','mḏḥ','faixa de cabeça','P','Fonograma mḏḥ. Em mḏḥ ("faixa, fita de cabeça").'],
  ['S11','𓋝','wsḫ','colar largo','','Igual a F38.'],
  ['S12','𓋞','nbw','colar de contas','ID','Determinativo ou logograma em nbw ("ouro"), ḥḏ ("prata").'],
  ['S13','𓋟','nb','combinação de colar de contas e pé','P','Fonograma nb.'],
  ['S14','𓋠','ḥḏ','combinação de colar de contas e maça de cabeça arredondada','I','Logograma em ḥḏ ("prata").'],
  ['S15','𓋣','ṯḥn','peitoral','ID','Determinativo ou logograma em ṯḥn ("cintilar"), ṯḥnt ("faiança").'],
  ['S16','𓋤','','','ID','Igual a S15.'],
  ['S17','𓋥','','peitoral','ID','Igual a S15.'],
  ['S18','𓋧','mnỉt','colar menat com contrapeso','ID','Determinativo ou logograma em mnỉt ("colar de contas, menat").'],
  ['S19','𓋨','sḏꜣwty','selo com colar','ID','Logograma em sḏꜣwty ("tesoureiro"), sḏꜣw ("precioso"). Determinativo ou logograma em ḫtm ("selo").'],
  ['S20','𓋩','ḫtm','colar com selo','I','Logograma em ḫtm ("selo").'],
  ['S21','𓋪','','anel','D','Determinativo em ỉwꜥw, ꜥꜥw, sšw ("anel").'],
  ['S22','𓋫','sṯ','nó de ombro','PID','Fonograma sṯ. Determinativo ou logograma em tꜣ-wr ("bombordo").'],
  ['S23','𓋬','dmḏ','dois chicotes com anel shen','P','Fonograma dmḏ. Em dmḏ ("unir").'],
  ['S24','𓋭','ṯs','nó de cinturão','','Igual a T11.'],
  ['S25','𓋮','ỉꜥꜣw','veste com tiras','I','Logograma em ỉꜥꜣw ("guia").'],
  ['S26','𓋯','šndyt','avental','ID','Determinativo ou logograma em šndyt ("avental, saiote").'],
  ['S27','𓋲','mnḫt','pano com dois fios','ID','Determinativo ou logograma em mnḫt ("vestimenta").'],
  ['S28','𓋳','','pano com franja no topo e tecido dobrado','D','Determinativo em ḥbs ("vestimenta"), ḥꜣp ("ocultar"), kfỉ ("descobrir").'],
  ['S29','𓋴','s','tecido dobrado','P','Fonograma s. Em ꜥnḫ(.w) (w)ḏꜣ snb ("que ele viva, prospere e tenha saúde", v.p.s.).'],
  ['S30','𓋵','sf','combinação de tecido dobrado e víbora cornuda','P','Fonograma sf. Em sf ("ontem").'],
  ['S31','𓋶','smꜣ','combinação de tecido dobrado e foice','P','Fonograma smꜣ. Em smꜣ ("touro de combate").'],
  ['S32','𓋷','sỉꜣ','pano com franja na lateral','P','Fonograma sỉꜣ. Em sỉꜣt ("tecido franjado").'],
  ['S33','𓋸','ṯbt','sandália','I','Logograma em ṯbt ("sandália"), ṯbw ("sandaleiro").'],
  ['S34','𓋹','ꜥnḫ','ânkh, possivelmente representando tira de sandália','P','Fonograma ꜥnḫ. Em ꜥnḫ ("viver"), ꜥnḫ ("correia de sandália").'],
  ['S35','𓋺','šwt','sombrinha','I','Logograma em šwt ("sombra").'],
  ['S36','𓋼','','sombrinha','I','Igual a S35.'],
  ['S37','𓋽','ḫw','leque','','Igual a R16.'],
  ['S38','𓋾','ḥḳꜣ','cajado heqa','','Igual a T15.'],
  ['S39','𓋿','ꜥwt','cajado de pastor','P','Fonograma ꜥwt. Em ꜥwt ("rebanho").'],
  ['S40','𓌀','wꜣs','cetro uás','','Igual a F10.'],
  ['S41','𓌁','ḏꜥm','cetro','P','Fonograma ḏꜥm. Em ḏꜥm ("ouro fino, electro").'],
  ['S42','𓌂','sḫm','cetro sekhem','PID','Fonograma sḫm. Em sḫm ("ter poder"), sḫm ("cetro"). Determinativo ou logograma em ḫrp ("dirigir, estar à frente").'],
  ['S43','𓌃','md','bengala','P','Fonograma md. Em mdw ("falar").'],
  ['S44','𓌄','ꜣms','bengala com flagelo','ID','Determinativo ou logograma em ꜣms ("bastão, cetro").'],
  ['S45','𓌅','nḫꜣḫꜣw','flagelo','ID','Determinativo ou logograma em nḫꜣḫꜣw ("flagelo, mangual").'],
  ['S46','𓌆','k','cobertura para cabeça e pescoço','',''],
  ['T1','𓌇','mn','maça de cabeça plana','P','Fonograma mn. Em mnw ("maça").'],
  ['T2','𓌈','','maça de cabeça arredondada','D','Determinativo em sḳr, sḳrỉ ("golpear, abater").'],
  ['T3','𓌉','ḥḏ','maça de cabeça arredondada','P','Fonograma ḥḏ. Em ḥḏ ("maça"), ḥḏ ("branco, brilhante"), ḥḏỉ ("danificar").'],
  ['T4','𓌋','ḥḏ','maça com alça','P','Igual a T3.'],
  ['T5','𓌌','ḥḏ','combinação de maça de cabeça arredondada e cobra','P','Fonograma ḥḏ.'],
  ['T6','𓌍','ḥḏḏ','combinação de maça de cabeça arredondada e duas cobras','P','Fonograma ḥḏḏ.'],
  ['T7','𓌎','','machado','D','Determinativo em mỉbt, mỉnb ("machado"), mdḥ ("desbastar, talhar").'],
  ['T8','𓌐','tp','adaga','P','Fonograma tp. Em tpy ("primeiro, chefe, sobre").'],
  ['T9','𓌒','pd|pḏ','arco','','Igual a F32.'],
  ['T10','𓌔','','arco composto','','Igual a T9.'],
  ['T11','𓌕','swn','flecha','P','Fonograma swn. Em swn ("perecer"), swnt ("médico").'],
  ['T12','𓌗','rwd|rwḏ','corda de arco','PI','Fonograma rwd/rwḏ. Em rwd ("duro, firme"). Logograma em dꜣr ("subjugar").'],
  ['T13','𓌘','rs','peças de madeira unidas','P','Fonograma rs. Em rs ("desperto, vigilante").'],
  ['T14','𓌙','ꜥꜣm','bumerangue na vertical','ID','Determinativo de "estrangeiro". Logograma em ꜥꜣm ("asiáticos"), ṯḥnw ("Líbia"). Determinativo em ḳmꜣ, ḳmꜣỉ ("criar").'],
  ['T15','𓌚','','bumerangue inclinado','ID','Igual a T14.'],
  ['T16','𓌛','','cimitarra','D','Determinativo em ḫpš ("cimitarra").'],
  ['T17','𓌝','wrrt','carro de guerra','ID','Determinativo ou logograma em wrrt ("carro de guerra").'],
  ['T18','𓌞','šms','cajado com embrulho','P','Fonograma šms. Em šms ("seguir, acompanhar").'],
  ['T19','𓌟','ḳs','ponta de arpão','','Igual a R11.'],
  ['T20','𓌠','','ponta de arpão','','Igual a T19.'],
  ['T21','𓌡','','arpão','','Igual a U21.'],
  ['T22','𓌢','sn','ponta de flecha','P','Fonograma sn. Em sn ("irmão"), sn ("cheirar").'],
  ['T23','𓌣','sn','ponta de flecha','P','Igual a T22.'],
  ['T24','𓌤','ꜥḥ|ỉḥ','rede de pesca','P','Fonograma ꜥḥ/ỉḥ. Em ỉḥ ("rede").'],
  ['T25','𓌥','dbꜣ|ḏbꜣ','bóia','P','Fonograma dbꜣ/ḏbꜣ. Em ḏbꜣ ("adornar"), dbꜣ ("substituir").'],
  ['T26','𓌦','sḫt','armadilha para aves','ID','Determinativo ou logograma em sḫt ("armadilha, laço").'],
  ['T27','𓌧','','armadilha','ID','Igual a T26.'],
  ['T28','𓌨','ẖr','tronco de açougueiro','P','Fonograma ẖr. Em ẖr ("sob, debaixo de"), ẖrt ("porção").'],
  ['T29','𓌩','nmt','tronco de açougueiro com faca','I','Logograma em nmt ("local de abate").'],
  ['T30','𓌪','dmt','faca','ID','Logograma de dmt ("faca"). Determinativo em dm ("ser afiado").'],
  ['T31','𓌫','sšm','afiador de faca','P','Fonograma sšm. Em sšm ("guiar, conduzir").'],
  ['T32','𓌬','sšm','combinação de afiador de faca e pernas','P','Fonograma sšm. Em sšm ("guiar, conduzir").'],
  ['T33','𓌮','sšm','afiador de faca de açougueiro','I','Logograma em sšm ("açougueiro").'],
  ['T34','𓌰','nm','faca de açougueiro','P','Fonograma nm. Em nm ("faca"), ḫnms ("amigo").'],
  ['T35','𓌱','','faca de açougueiro','','Igual a U32.'],
  ['T36','𓌲','','escudo','',''],
  ['U1','𓌳','mꜣ','foice','P','Fonograma mꜣ. Em mꜣꜣ ("ver"), ꜣsḫ ("ceifar").'],
  ['U2','𓌴','mꜣ','foice','P','Igual a U1.'],
  ['U3','𓌵','mꜣ','','P','Fonograma mꜣ. Em mꜣꜣ ("ver").'],
  ['U4','𓌶','mꜣꜥ','mꜣꜥ','P','Fonograma mꜣꜥ. Em mꜣꜥ ("verdadeiro").'],
  ['U5','𓌷','mꜣꜥ','','P','Igual a U4.'],
  ['U6','𓌸','mr','','P','Fonograma mr. Em mrỉ ("amar").'],
  ['U7','𓌻','mr','enxada','P','Igual a U6.'],
  ['U8','𓌼','ḥn','','P','Fonograma ḥn. Em ḥn ("enxada").'],
  ['U9','𓌽','','','D','Determinativo em bdt ("trigo emmer"), ḫꜣỉ ("medir"), ḥḳꜣt ("medida heqat").'],
  ['U10','𓌾','','medida de grão (com plural, para grãos)','I','Logograma em ỉt ("cevada").'],
  ['U11','𓌿','ḥḳꜣt','','I','Logograma em ḥḳꜣt ("medida heqat").'],
  ['U12','𓍀','ḥḳꜣt','','I','Logograma em ḥḳꜣt ("medida heqat").'],
  ['U13','𓍁','šnꜥ','','P','Fonograma šnꜥ. Em šnꜥ ("repelir"). Fonograma hb. Em hb ("arar").'],
  ['U14','𓍂','šnꜥ','','P','Fonograma šnꜥ. Em šnꜥ ("repelir").'],
  ['U15','𓍃','tm','trenó','P','Fonograma tm. Em tm ("estar completo"), ḥtm ("perecer").'],
  ['U16','𓍄','','trenó com cabeça de chacal','','Igual a O31.'],
  ['U17','𓍅','grg','picareta, abrindo a terra','P','Fonograma grg. Em grg ("estabelecer; armar laço"), grg ("falsidade, mentira").'],
  ['U18','𓍆','','','','Igual a F18.'],
  ['U19','𓍇','nw','','P','Fonograma nw. Em nw ("este").'],
  ['U20','𓍈','nw','','P','Igual a U19.'],
  ['U21','𓍉','stp|sṯp','formão sobre bloco','P','Fonograma stp/sṯp. Em stp ("escolher").'],
  ['U22','𓍊','','badalo de sino / instrumento em forquilha, etc.','D','Determinativo em mnḫ ("eficiente"), mnḫ ("entalhar").'],
  ['U23','𓍋','mr','cinzel','P','Fonograma mr. Em mr ("doente"), smr ("amigo, cortesão"). Fonograma ꜣb. Em ꜣbỉ ("desejar").'],
  ['U24','𓍍','ḥmt','berbequim manual','I','Logograma em ḥmt ("ofício, arte").'],
  ['U25','𓍎','','variante de U24 (berbequim manual)','I','Igual a U24.'],
  ['U26','𓍏','wbꜣ','','','Igual a U25.'],
  ['U27','𓍐','','','','Igual a U26.'],
  ['U28','𓍑','ḏꜣ','broca de fogo','P','Fonograma ḏꜣ. Em ꜥnḫ(.w) (w)ḏꜣ snb ("que ele viva, prospere e tenha saúde", v.p.s.).'],
  ['U29','𓍒','ḏꜣ','','P','Igual a U28.'],
  ['U30','𓍔','tꜣ','forno','P','Fonograma tꜣ. Em štꜣ ("misterioso"), tꜣ ("quente").'],
  ['U31','𓍕','rtḥty','','ID','Determinativo ou logograma em rtḥty ("padeiro"), rtḥ ("conter, refrear").'],
  ['U32','𓍖','','','D','Determinativo em smn ("pressionar"), smn ("estabelecer").'],
  ['U33','𓍘','tỉ','pilão (topo curvo)','P','Fonograma tỉ.'],
  ['U34','𓍙','ḫsf','','P','Fonograma ḫsf. Em ḫsf ("repelir").'],
  ['U35','𓍚','ḫsf','','P','Fonograma ḫsf.'],
  ['U36','𓍛','ḥm','mão de pilão','','Igual a M13.'],
  ['U37','𓍜','','','D','Determinativo em ẖꜥḳ ("barbear, rapar").'],
  ['U38','𓍝','mḫꜣt','balança','ID','Determinativo ou logograma em mḫꜣt ("balança").'],
  ['U39','𓍞','','','D','Determinativo em wsṯt ("poste"), wṯs, ṯsỉ ("erguer, levantar").'],
  ['U40','𓍟','','suporte (para erguer)','D','Igual a U39.'],
  ['U41','𓍠','','prumo','D','Determinativo em tḫ ("prumo").'],
  ['U42','𓍡','','forcado','',''],
  ['V1','𓍢','šn','','P','Fonograma šn. Em šnt ("disputa"), šnỉ ("litigar"), št ("cem").'],
  ['V2','𓍬','sṯꜣt','','ID','Determinativo em stꜣ ("arrastar"). Logograma em sṯꜣt ("aroura", medida de área).'],
  ['V3','𓍮','r-sṯꜣw','','I','Logograma em r-sṯꜣw ("Rosetau, necrópole").'],
  ['V4','𓍯','wꜣ','laço','P','Fonograma wꜣ. Em wꜣḥ ("perdurar").'],
  ['V5','𓍰','snṯ','','ID','Determinativo ou logograma em snṯ ("planejar, traçar").'],
  ['V6','𓍱','šs|šsr','corda (forma)','P','Fonograma šs, šsr.'],
  ['V7','𓍲','šn','corda (forma)','P','Fonograma šn.'],
  ['V8','𓍵','šn','','P','Igual a V7.'],
  ['V9','𓍶','','anel shen','D','Determinativo em šnw ("cartucho").'],
  ['V10','𓍷','','cartucho','D','Determinativo em šnw ("cartucho"), rn ("nome").'],
  ['V11','𓍸','','cartucho (dividido)','D','Determinativo em dnỉ ("conter, represar"), pḫꜣ ("dividir, rachar").'],
  ['V12','𓍼','','','D','Determinativo em sšd ("faixa de cabeça"), fḫ ("soltar"), fḫnw ("fenícios").'],
  ['V13','𓍿','ṯ','corda de amarração','P','Fonograma ṯ.'],
  ['V14','𓎀','','','','Igual a V13.'],
  ['V15','𓎁','ỉṯ','corda de amarração com pernas caminhando','P','Fonograma ỉṯ. Em ỉṯỉ ("tomar, apoderar-se").'],
  ['V16','𓎂','sꜣ','cabresto de gado (bil.)','P','Fonograma sꜣ. Em sꜣ ("proteção").'],
  ['V17','𓎃','sꜣ','boia salva-vidas','','Igual a V39.'],
  ['V18','𓎄','','','','Igual a V17.'],
  ['V19','𓎅','','','','Igual a Aa3.'],
  ['V20','𓎆','mḏ','"cabresto de gado"','P','Fonograma mḏ. Em mḏwt ("estábulos"), mḏ ("10").'],
  ['V21','𓎓','mḏ','Grilhão + Cobra','P','Fonograma mḏ.'],
  ['V22','𓎔','mḥ','chicote','P','Fonograma mḥ. Em mḥ ("encher").'],
  ['V23','𓎕','','','','Igual a O34.'],
  ['V24','𓎗','wḏ','"bastão de comando" (pode ser circular)','P','Fonograma wḏ. Em wḏ ("ordenar, decreto").'],
  ['V25','𓎘','','variante de V24 (pode ser circular)','','Igual a U34.'],
  ['V26','𓎙','ꜥd|ꜥḏ','','P','Fonograma ꜥd/ꜥḏ. Em ꜥd ("bom estado").'],
  ['V27','𓎚','ꜥd|ꜥḏ','','P','Igual a V26.'],
  ['V28','𓎛','ḥ','pavio torcido','P','Fonograma ḥ.'],
  ['V29','𓎝','wꜣḥ|sk','esfregão (de fibra / vassoura de palha)','P','Fonograma wꜣḥ, sk.'],
  ['V30','𓎟','nb','cesto','','Igual a W3.'],
  ['V31','𓎡','k','cesto com alça','P','Fonograma k.'],
  ['V32','𓎣','msn','','','Igual a R4.'],
  ['V33','𓎤','','','','Igual a V8.'],
  ['V34','𓎦','','','','Igual a V33.'],
  ['V35','𓎧','','','','Igual a F51.'],
  ['V36','𓎨','ḥn','recipiente duplo (ou glifos acrescidos) — grafias diversas','P','Fonograma ḥn. Em ḥnt ("ocupação").'],
  ['V37','𓎩','ỉdr','','ID','Determinativo ou logograma em ỉdr ("atadura, atar"), ỉdr ("rebanho").'],
  ['V38','𓎫','','','D','Determinativo em wt ("atadura").'],
  ['V39','𓎬','tỉt','ânkh estilizado (de Ísis) (?)','I','Logograma em tỉt ("nó de Ísis, tíet").'],
  ['V40','𓎭','','','',''],
  ['W1','𓎯','','jarra de óleo','D','Determinativo em mḏt ("unguento"), mrḥt ("óleo").'],
  ['W2','𓎰','bꜣs','jarra de óleo sem ataduras','P','Fonograma bꜣs. Em bꜣstt ("Bastet"), bꜣs ("jarro de óleo").'],
  ['W3','𓎱','ḥb','bacia de alabastro','ID','Determinativo ou logograma em ḥb ("festa"), ḥb ("lamentar, prantear").'],
  ['W4','𓎳','ḥb','câmara de festa (a cauda também pode ser vertical \'Grande\': ꜥꜣ)','ID','Determinativo ou logograma em ḥb ("festa"), tp-rnpt ("festa do primeiro dia do ano").'],
  ['W5','𓎴','','','I','Logograma em ẖry-ḥbt ("sacerdote leitor").'],
  ['W6','𓎵','','recipiente de metal','D','Determinativo em wḥt ("caldeirão").'],
  ['W7','𓎶','','tigela de granito','D','Determinativo em ꜣbt ("família"), mꜣṯ ("proclamar").'],
  ['W8','𓎷','','tigela de granito deformada','D','Igual a W7.'],
  ['W9','𓎸','ẖnm','jarro de pedra','P','Fonograma ẖnm.'],
  ['W10','𓎺','ḥnw','taça','PID','Fonograma ḥnw. Em ḥnwt ("senhora"). Determinativo ou logograma em wsḫ ("largo").'],
  ['W11','𓎼','g','suporte de anel / pote de terracota','PID','Fonograma g. Determinativo ou logograma em nst ("trono").'],
  ['W12','𓎽','g','suporte de anel plano','PID','Igual a W11.'],
  ['W13','𓎾','dšrt','pote de terracota','','Igual a N42.'],
  ['W14','𓎿','ḥs','jarra de água','P','Fonograma ḥs. Em ḥst ("jarro de água").'],
  ['W15','𓏁','ḳbb','jarra de água com água vertendo','ID','Determinativo ou logograma em ḳbb, ḳbḥ ("esfriar; libação").'],
  ['W16','𓏂','','jarra de água com água vertendo e suporte de anel','ID','Igual a W15.'],
  ['W17','𓏃','ḫnt','três jarras de água em suporte','P','Fonograma ḫnt. Em ḫntw ("suporte de jarros").'],
  ['W18','𓏅','ḫnt','quatro jarras de água em suporte','P','Igual a W17.'],
  ['W19','𓏇','mỉ','jarro de leite com alça','P','Fonograma mỉ. Em mỉ ("semelhança, como").'],
  ['W20','𓏈','','jarro de leite com tampa','D','Determinativo em ỉrtt ("leite").'],
  ['W21','𓏉','','jarras de vinho','D','Determinativo em ỉrp ("vinho").'],
  ['W22','𓏊','ḥnḳt','jarra de cerveja','ID','Logograma em ḥnḳt ("cerveja"). Determinativo em ḳrḥt ("vaso, recipiente").'],
  ['W23','𓏋','','jarra de cerveja com alças','ID','Igual a W22.'],
  ['W24','𓏌','nw|ỉn|ỉnk','pote','P','Fonograma nw, ỉn, ỉnk.'],
  ['W25','𓏎','ỉn','pote com pernas','P','Fonograma ỉn. Em ỉnỉ ("buscar, trazer").'],
  ['X1','𓏏','t','pão','PI','Fonograma t. Logograma em t ("pão").'],
  ['X2','𓏐','dḥwty','','ID','Determinativo de pão. Em t ("pão"). Logograma em ḏḥwty ("Tot").'],
  ['X3','𓏑','','','ID','Igual a X2.'],
  ['X4','𓏒','','pão enrolado','','Igual a N16.'],
  ['X5','𓏕','','','D','Determinativo em ꜥḳw ("provisões").'],
  ['X6','𓏖','','pão com decoração','D','Determinativo em pꜣt ("pão, bolo").'],
  ['X7','𓏘','','meio pão','D','Determinativo em snw ("oferendas"). Quando duplicado, wnm ("comer").'],
  ['X8','𓏙','dỉ','pão em forma cônica','P','Fonograma dỉ. Em rdỉ ("dar").'],
  ['Y1','𓏛','mḏꜣt','rolo de papiro','PID','Fonograma mḏꜣt. Logograma em mḏꜣt ("rolo de papiro, livro"). Determinativo em rḫ ("saber").'],
  ['Y2','𓏝','mḏꜣt','rolo de papiro aberto','PID','Igual a Y1.'],
  ['Y3','𓏞','sš','utensílios de escriba','ID','Determinativo ou logograma em sš ("escrever"), nꜥꜥ ("alisar").'],
  ['Y4','𓏟','','utensílios de escriba','ID','Igual a Y3.'],
  ['Y5','𓏠','mn','tabuleiro de senet','P','Fonograma mn. Em ỉmn ("Amon"), mn ("permanecer").'],
  ['Y6','𓏡','ỉbꜣ','peça de jogo','ID','Determinativo ou logograma em ỉbꜣ ("peça de jogo", "dança").'],
  ['Y7','𓏢','','harpa','D','Determinativo em bnt ("harpa").'],
  ['Y8','𓏣','','sistro','D','Determinativo em sššt ("sistro").'],
  ['Z1','𓏤','','traço simples','ID','Acompanha ideogramas. Determinativo de wꜥ ("um"). Logograma dos numerais de 1 a 9.'],
  ['Z2','𓏥','','traço de plural (horizontal)','D','Determinativo de pluralidade.'],
  ['Z3','𓏪','','traços de plural (vertical)','D','Igual a Z2.'],
  ['Z4','𓏭','y','traço de dual','D','Determinativo de dualidade.'],
  ['Z5','𓏯','','traço diagonal (do hierático)','','Substituto de sinais complexos ou perigosos, e de figuras humanas.'],
  ['Z6','𓏱','','substituto de várias figuras humanas','','Igual a T7.'],
  ['Z7','𓏲','w','espiral (equivalente hierático)','P','Fonograma w.'],
  ['Z8','𓏳','','oval','D','Determinativo de redondo.'],
  ['Z9','𓏴','swꜣ','bastões diagonais cruzados','P','Fonograma swꜣ. Em swꜣ ("passar").'],
  ['Z10','𓏵','swꜣ','bastões diagonais cruzados','P','Igual a Z9.'],
  ['Z11','𓏶','ỉm','duas tábuas cruzadas e unidas','','Igual a M44.'],
  ['Z12','𓏷','','','',''],
  ['Z13','𓏸','','','',''],
  ['Z14','𓏹','','','',''],
  ['Z15','𓏺','','','',''],
  ['Z16','𓐄','','','',''],
  ['Aa1','𓐍','ḫ','placenta ou peneira','P','Fonograma ḫ.'],
  ['Aa2','𓐎','','pústula','D','Determinativo de tumores ou condições corporais.'],
  ['Aa3','𓐏','','pústula com líquido saindo','D','Igual a Aa2.'],
  ['Aa4','𓐐','bꜣ','','P','Variante de W10a.'],
  ['Aa5','𓐑','ḥp','parte do mecanismo de leme de embarcação','P','Fonograma ḥp.'],
  ['Aa6','𓐒','','','D','Determinativo em tmꜣ ("esteira").'],
  ['Aa7','𓐓','','lâmina de golpe','D','Determinativo em sḳr ("golpear, abater").'],
  ['Aa8','𓐖','ḳn','túneis de irrigação','','Igual a V27.'],
  ['Aa9','𓐗','','','D','Determinativo em ḫwd ("rico").'],
  ['Aa10','𓐘','','','D','Determinativo em drf ("escrita").'],
  ['Aa11','𓐙','mꜣꜥ','','','Igual a Aa14.'],
  ['Aa12','𓐚','','','','Igual a Aa11.'],
  ['Aa13','𓐛','ỉm|m','','P','Fonograma ỉm, m.'],
  ['Aa14','𓐜','ỉm|m','','P','Fonograma ỉm, m.'],
  ['Aa15','𓐝','ỉm|m','','P','Fonograma ỉm, m.'],
  ['Aa16','𓐞','gs','','',''],
  ['Aa17','𓐟','sꜣ','','P','Fonograma sꜣ. Em sꜣ ("costas, dorso").'],
  ['Aa18','𓐠','sꜣ','','P','Igual a Aa17.'],
  ['Aa19','𓐡','','','D','Determinativo em ḥr ("preparar"), ḥryt ("pavor").'],
  ['Aa20','𓐢','ꜥpr','','P','Fonograma ꜥpr. Em ꜥpr ("equipar").'],
  ['Aa21','𓐣','wḏꜥ','','P','Fonograma wḏꜥ. Em wḏꜥ ("julgar").'],
  ['Aa22','𓐤','wḏꜥ','','P','Igual a Aa21.'],
  ['Aa23','𓐥','','','D','Determinativo em mḏd ("perfurar, pressionar, aderir").'],
  ['Aa24','𓐦','','','D','Igual a Aa23.'],
  ['Aa25','𓐧','smꜣ','','I','Logograma em smꜣ ("estolista", título sacerdotal).'],
  ['Aa26','𓐨','','','D','Determinativo em sbỉ ("rebelar-se, rebelde").'],
  ['Aa27','𓐩','nḏ','','P','Fonograma nḏ. Em nḏ ("perguntar, indagar").'],
  ['Aa28','𓐪','ḳd','','P','Fonograma ḳd. Em ḳd ("construir").'],
  ['Aa29','𓐫','ḳd','','P','Igual a Aa28.'],
  ['Aa30','𓐬','','','','Igual a F31.'],
  ['Aa31','𓐭','','','','Igual a Aa30.'],
  ['Aa32','𓐮','','','',''],
];
