window.GARDINER_DATA_EN=[
  ['A1','𓀀','','seated man','D','Det. of man, names; Pronoun1st sing. i, wi, ink, kwi. “I,” “me,” “my.”'],
  ['A2','𓀁','','man with hand to mouth','D','Det. of eat, drink, speak, think.'],
  ['A3','𓀂','','man sitting on heel','D','Det. of sit.'],
  ['A4','𓀃','','seated man with hands raised','D','Det. adoration, hide'],
  ['A5','𓀄','','crouching man hiding behind wall','D','Det. hide'],
  ['A6','𓀆','','seated man under vase from which water flows','D','Det. purity, cleanliness'],
  ['A7','𓀉','','fatigued man','D','Det. weary, weak'],
  ['A8','𓀊','','man performing hnw-rite','D','Det. in hnw “jubilation”'],
  ['A9','𓀋','','man steadying basket on head','D','Det. in 3ṯp “load,” f3i “carry,” k3t “work.”'],
  ['A10','𓀌','','seated man holding oar','D','Det. in sḳdw “sail.”'],
  ['A11','𓀍','','seated man holding scepter of authority and shepherd\'s crook','D','Det. ḫnms “friend.”'],
  ['A12','𓀎','','soldier with bow and quiver','D','Det. mšʿ “army,” soldier.'],
  ['A13','𓀏','','man with arms tied behind his back','D','Det. ḫfty “enemy.”'],
  ['A14','𓀐','','falling man with blood streaming from his head','D','Det. of mwt “die,” enemy.'],
  ['A15','𓀒','','man falling','D','Det. ḫr “fall,” sḫrt “overthrow.”'],
  ['A16','𓀓','','man bowing down','D','Det. ksi “bow.”'],
  ['A17','𓀔','ẖrd','child sitting with hand to mouth','ID','Det. šri “young.” Ideo. ẖrd “child.”'],
  ['A18','𓀖','','child wearing red crown','D','Det. child-king'],
  ['A19','𓀗','','bent man leaning on staff','D','Det. i3w “old,” smsw “eldest,” wr “great one, chief.”'],
  ['A20','𓀘','','man leaning on forked staff','D','Var. of A19.'],
  ['A21','𓀙','sr','man holding staff with handkerchief','ID','Det. and Ideo. sr “official, noble.”'],
  ['A22','𓀚','','statue of man with staff and scepter of authority','D','Det. statue.'],
  ['A23','𓀛','','king with staff and mace with round head','D','Det. ity, “sovereign.”'],
  ['A24','𓀜','nḫt','man striking with both hands','ID','Det. ḥwi, “strike,” nḥm “take away.” Ideo. nḫt strong.'],
  ['A25','𓀝','','man striking, with left arm hanging behind back','D','Det. hwi “strike.”'],
  ['A26','𓀞','','man with one arm pointing forward','ID','Det. nis “call.” Ideo. vocative i, “Oh!”'],
  ['A27','𓀟','ỉn','hastening man','P','Phon. in “by,” agent particle.'],
  ['A28','𓀠','','man with hands raised on either side','D','Det. ḳ3 “high,” ḥʿi “rejoice.”'],
  ['A29','𓀡','','man upside down','D','Det. upside down.'],
  ['A30','𓀢','','man with hands raised in front','D','Det. i3w “praise,” dw3 “adoration.”'],
  ['A31','𓀣','','man with hands raised behind him','D','Det. turn away.'],
  ['A32','𓀤','','man dancing with arms to the back','D','Det. dance.'],
  ['A33','𓀦','','man with stick and bundle on shoulder','D','Det. wander, herdsman.'],
  ['A34','𓀧','','man pounding in a mortar','D','Det. ḫwsi “pound, build.”'],
  ['A35','𓀨','ḳd','man building wall','ID','Det. and Ideo. ḳd “build.”'],
  ['A36','𓀩','ꜥfty','man kneading into vessel','ID','Det. and Ideo. ʿfty “brewer.”'],
  ['A37','𓀪','ꜥfty','man in vessel','ID','Use as A36.'],
  ['A38','𓀫','ḳỉs|ḳsỉ','man holding necks of two emblematic animals with panther heads','I','Ideo. ḳis/ḳsi “”Cusae” (town).'],
  ['A39','𓀬','ḳỉs|ḳsỉ','man on two giraffes','I','Use as A38.'],
  ['A40','𓀭','','seated god','D','Det. god. Replaces A1 as 1st sing pronoun when god speaks. i, wi, ink, kwi.'],
  ['A41','𓀯','','king with uraeus','D','Det. nsw “king,” ḥm “majesty,” nb “lord.”'],
  ['A42','𓀰','','king with uraeus and flagellum','D','Use as A41.'],
  ['A43','𓀲','','king wearing white crown','D','Det. king of Upper Egypt.'],
  ['A44','𓀴','','king wearing white crown with flagellum','D','Use as A43.'],
  ['A45','𓀵','bỉty','king wearing red crown','ID','Det. and Ideo. bity “king of Lower Egypt.”'],
  ['A46','𓀷','bỉty','king wearing red crown with flagellum','ID','Same as A45'],
  ['A47','𓀸','sꜣw','shepherd seated and wrapped in mantle, holding stick','ID','Det. and Ideo. s3w “guard,” mniw “herdsman.”'],
  ['A48','𓀹','','beardless man seated and holding knife','D','Det. iry “relating to.”'],
  ['A49','𓀺','','seated Syrian holding stick','D','Det. foreigner, ʿ3mw “Asiatics.”'],
  ['A50','𓀻','','noble on chair','D','Det. revered person, deceased. Var. A1 for 1st sing. pronoun.'],
  ['A51','𓀼','špsỉ','noble on chair with flagellum','ID','Det. and Ideo. špsi “noble”'],
  ['A52','𓀽','','noble squatting with flagellum','D','Det. revered person, deceased.'],
  ['A53','𓀾','','standing mummy','D','Det. mummy, statue, likeness, form.'],
  ['A54','𓀿','','lying mummy','D','Det. dead.'],
  ['A55','𓁀','','mummy on bed','D','Det. sḏr “lie down,” dead.'],
  ['A56','𓁁','','seated man holding stick','',''],
  ['A57','𓁂','ḥtp-dỉ-nsw','man holding loaf on mat','',''],
  ['A58','𓁃','','man applying hoe to ground','',''],
  ['A59','𓁄','','man threatening with stick','D','Det. drive off.'],
  ['A60','𓁅','stỉ','man sowing seeds','',''],
  ['A61','𓁆','','man looking over his shoulder','',''],
  ['A62','𓁇','','Asiatic','',''],
  ['A63','𓁈','','king on throne holding staff','',''],
  ['A64','𓁉','','man sitting on heels holding forward cup','',''],
  ['A65','𓁊','','man wearing tunic with fringes and holding mace','',''],
  ['A66','𓁋','ỉḥy|nṯr-ꜥꜣ','man holding sistrum','',''],
  ['A67','𓁌','','dwarf','',''],
  ['A68','𓁍','msdmt','man holding up knife','',''],
  ['A69','𓁎','','seated man with raised right arm and left arm hanging down','',''],
  ['A70','𓁏','ḥḥ','seated man with raised arms','',''],
  ['B1','𓁐','','seated woman','D','Det. woman, name. Sometimes for A1 1st sing. pronoun – i'],
  ['B2','𓁑','','pregnant woman','D','Det. pregnant'],
  ['B3','𓁒','msỉ','woman giving birth','ID','Det. and Ideo. msi “give birth, bear.”'],
  ['B4','𓁓','msỉ','combination of woman giving birth and three skins tied together','ID','Use as B3.'],
  ['B5','𓁔','','woman suckling child','D','Det. mnʿt “nurse.”'],
  ['B6','𓁖','','woman on chair with child on lap','D','Det. rnn “nurse.”'],
  ['B7','𓁗','','queen wearing diadem and holding flower','D','Det. queens’ names.'],
  ['B8','𓁘','','woman holding lotus flower','',''],
  ['B9','𓁙','','woman holding sistrum','',''],
  ['C1','𓁚','Rꜥ','god with sun-disk and uraeus','ID','Det. and Ideo. Rʿ “Re, sun-god”'],
  ['C2','𓁛','Rꜥ','god with falcon head and sun-disk holding ankh','ID','Var. C1. Det. and Ideo. Rʿ “Re, sun-god”'],
  ['C3','𓁟','ḏḥwty','god with ibis head','ID','Det. or Ideo. ḏḥwty “Thoth”'],
  ['C4','𓁠','ẖnmw','god with ram head','ID','Det. or Ideo. ẖnmw “Khnum”'],
  ['C5','𓁡','ẖnmw','god with ram head holding ankh','ID','Use as C4.'],
  ['C6','𓁢','ỉnpw','god with jackal head','ID','Det. and Ideo. inpw “Anubis,” wp-w3wt “Wepwawet.”'],
  ['C7','𓁣','Stḫ','god with Seth-animal head','ID','Det. and Ideo. Stḫ “Seth.”'],
  ['C8','𓁤','Mnw','ithyphallic god with two plumes, uplifted arm and flagellum','ID','Det. and Ideo. Mnw “Min.”'],
  ['C9','𓁥','','goddess with horned sun-disk','ID','Det. and Ideo.'],
  ['C10','𓁦','Mꜣꜥt','goddess with feather','ID','Det. and Ideo. M3ʿt “Maat”'],
  ['C11','𓁨','ḥḥ','god with arms supporting the sky and palm branch on head','I','Ideo. ḥḥ “million,” god Heh.'],
  ['C12','𓁩','Imn','god with two plumes and scepter','ID','Det. and Ideo. Imn “Amun.”'],
  ['C13','𓁪','ỉmn','C12 reversed','',''],
  ['C14','𓁫','ỉmn-ḥr-ḫpš.f','god with two plumes and scimitar','',''],
  ['C15','𓁬','ỉmn-ḥr-ḫpš.f','C14 reversed','',''],
  ['C16','𓁭','ỉtmw','god wearing red crown with ankh','',''],
  ['C17','𓁮','','god with falcon head and two plumes','ID','Det. and Ideo Mntw “Montu.”'],
  ['C18','𓁯','tꜣ-ṯnn','squatting god','ID','Det. and Ideo. t3-ṯnnii “Tatjenen.”'],
  ['C19','𓁰','Ptḥ','mummy-shaped god','ID','Det. and Ideo. Ptḥ “Ptah.”'],
  ['C20','𓁱','Ptḥ','mummy-shaped god in shrine','ID','Use as C19'],
  ['C21','𓁲','bs','Bes','',''],
  ['C22','𓁳','ḫnsw','god with falcon head and moon','',''],
  ['C23','𓁴','sḫmt|mnḥyt|mḥyt|bꜣstt','goddess with feline head and sun with uraeus','',''],
  ['C24','𓁵','ỉtmw','god wearing red crown with scepter','',''],
  ['D1','𓁶','tp','head','PID','Phono. tp. Det. or Ideo. for tp “head,” tpy “first, chief.” Det. ḏ3ḏ3“head.”'],
  ['D2','𓁷','ḥr','face','PI','Phon. ḥr. Ideo. for ḥr “face.”'],
  ['D3','𓁸','','hair','D','Det. for šny “hair,” iwn “complexion, nature.” Abbr. for gm wš “found missing.”'],
  ['D4','𓁹','ỉrt','eye','PI','Phono. iri “to do, make.” Ideo. for irt “eye.”'],
  ['D5','𓁺','','eye touched up with paint','D','Det. for actions or conditions of the eye. ex. dgi “look,” šp “blind.”'],
  ['D6','𓁻','','eye with painted upper lid','D','Use as D5.'],
  ['D7','𓁼','','eye with painted lower lid','D','Det. for adorn and in ʿnw ” “Anu” (location).'],
  ['D8','𓁽','','eye enclosed in sandy tract','D','Det. forʿnw “Turah,” ʿn “beautiful.”'],
  ['D9','𓁿','rmỉ','eye with flowing tears','ID','Det. or Ideo. for rmi “weep.”'],
  ['D10','𓂀','wꜣḏt','Eye of Horus','ID','Det. or Ideo. for w3ḏt “wedjat eye.”'],
  ['D11','𓂁','','left part of the eye of Horus','','1/2 ḥeqat measure of grain.'],
  ['D12','𓂂','','pupil','D','Det. for ḏfd “pupil of eye.”'],
  ['D13','𓂃','','eyebrow','','1/8 ḥeqat measure of grain.'],
  ['D14','𓂄','','right part of eye of Horus','','1/16 ḥeqat measure of grain.'],
  ['D15','𓂅','','diagonal marking of eye of Horus','','1/32 ḥeqat measure of grain.'],
  ['D16','𓂆','','vertical marking of eye of Horus','','1/64 ḥeqat measure of grain.'],
  ['D17','𓂇','tỉt','diagonal and vertical markings of eye of Horus','ID','Det. or Ideo. for tit “figure, image.”'],
  ['D18','𓂈','msḏr','ear','ID','Det. or Ideo. for msḏr “ear.”'],
  ['D19','𓂉','fnd','nose, eye and cheek','ID','Det. or Ideo. for fnd “nose.” Det. sn “smell,” rš “rejoice.”'],
  ['D20','𓂊','fnd','nose, eye and cheek (cursive)','ID','Use as D19'],
  ['D21','𓂋','r','mouth','','T31'],
  ['D22','𓂌','rwy','mouth with two strokes','I','Ideo. for rwy “2/3.”'],
  ['D23','𓂍','ḫmt','mouth with three strokes','I','Ideo. for ḫmt rw “3/4.”'],
  ['D24','𓂎','spt','upper lip with teeth','ID','Det. or Ideo. for spt “lip.” Mistakenly used a F42.'],
  ['D25','𓂏','spty','lips','ID','Det. or Ideo. for spty “lips.”'],
  ['D26','𓂐','','liquid issuing from lips','D','Det. for spit, spew. ex. psg “spit,” ḳʿ “spew out.”'],
  ['D27','𓂑','','small breast','D','Det. for breast, suckle. ex. mnḏ “breast”'],
  ['D28','𓂓','kꜣ','two arms upraised','PI','Phono. k3. Ideo. for k3 “soul.”'],
  ['D29','𓂔','kꜣ','combination of hieroglyphs D28 and R12','PI','Use as D28.'],
  ['D30','𓂕','','two arms upraised with tail','D','Det. for nḥb-k3w “Uniter of Attributes, Assigner of Kas,” name of mythical serpent deity.'],
  ['D31','𓂖','ḥm-kꜣ','arms embracing club','I','Ideo. for ḥm-k3 “ka servent.”'],
  ['D32','𓂘','','arms embracing','D','Det. for embrace, open. ex. inḳ “envelop,” ḥpt “embrace.”'],
  ['D33','𓂙','ẖn','arms rowing','PI','Phono. ẖn. Ideo. for ẖni “row.”'],
  ['D34','𓂚','ꜥḥꜣ','armswith shieldand battle axe','I','Ideo. for ʿḥ3 “fight”'],
  ['D35','𓂜','n','arms in gesture of negation','PID','Phono. n. Ideo. for n and nn, “not.” Det. negation.'],
  ['D36','𓂝','ꜥ','forearm (palm upwards)','PI','Phono. ʿ. Ideo. ʿ “arm, hand.”'],
  ['D37','𓂞','dỉ','forearm with bread cone','P','Phono. di in rdi “give.”'],
  ['D38','𓂟','mỉ|m','forearm with rounded loaf','PD','Phono. mi or m. Det. for imi “give.”'],
  ['D39','𓂠','','forearm with bowl','D','Det. for offer, present. ex. ḥnk “present,” drp “offer.”'],
  ['D40','𓂡','hꜣỉ','forearm with stick','ID','Det. for force, effort. ex. nḫt “strong.” Ideo. h3i “evaluate.”'],
  ['D41','𓂢','nỉ','forearm with palm down and bent upper arm','PD','Phono. ni. Det. for arm. ex. rmn “arm, shoulder.”'],
  ['D42','𓂣','mḥ','forearm with palm down and straight upper arm','ID','Det. or Ideo. for mḥ “cubit”'],
  ['D43','𓂤','ḫw','forearm with flail','PI','Phono. ḫw. Ideo. for ḫwi “protect.'],
  ['D44','𓂥','ḫrp','arm with sekhem scepter','ID','Det. and Ideo. for ḫrp “control, be at head of, administer.”'],
  ['D45','𓂦','ḏsr','arm with wand','ID','Det. and Ideo. for ḏsr “clear road, sacred, holy.”'],
  ['D46','𓂧','d','hand','PI','Phono. d. Ideo. for ḏrt “hand.”'],
  ['D47','𓂩','','hand with palm up','PD','Det. for ḏrt “hand” when spelled with Phono.'],
  ['D48','𓂪','šsp','hand without thumb','I','Ideo. šsp “palm, hand-breadth” (measure)'],
  ['D49','𓂬','','fist','D','Det. for grasp. ex. 3mm “grasp,” ḫfʿ “seize.”'],
  ['D50','𓂭','ḏbꜥ','one finger','ID','Ideo. for ḏbʿ “finger,” ḏbʿ “10,000.” Det. for accurate, when doubled.'],
  ['D51','𓂷','','one finger (horizontal)','D','Det. for actions related to finger, fruit, flower. ex. ʿnt “nail,” ḫ3i “measure,” dḳr “fruit.”'],
  ['D52','𓂸','mt','phallus','PID','Phono. mt. Det. for male. ex. ʿ3 “ass,” ṯ3y “male.” Ideo. k3 “bull.”'],
  ['D53','𓂺','','phallus with emission','D','Det. for male, penis. ex. m b3ḥ “in the presence of” ḏr b3ḥ “since,” r b3ḥ “before.”'],
  ['D54','𓂻','ỉw','legs walking','PD','Phono. iw in iwi “come.” Det. for motion.'],
  ['D55','𓂽','','legs walking backwards','D','Det. for backwards. ex. ʿnn “turn back,” ḫtḫt “be reversed.”'],
  ['D56','𓂾','pd','leg','PD','Phono. pd. Det. for leg, foot. ex. rd “leg,” pd “knee.”'],
  ['D57','𓂿','','leg with knife','D','Det. for mutilate. ex. i3ṯ “be mutilated.”'],
  ['D58','𓃀','b','foot','PI','Phono. b. Ideo. for bw “place.”'],
  ['D59','𓃁','ꜥb','foot and forearm','P','Phono. ʿb'],
  ['D60','𓃂','wꜥb','foot under vase from which water flows','I','Ideo. for wʿb “pure, clean.”'],
  ['D61','𓃃','sꜣḥ','three toes oriented leftward','I','Ideo. for s3ḥ “toe”'],
  ['D62','𓃄','sꜣḥ','three toes oriented rightward','I','Use as D61.'],
  ['D63','𓃅','sꜣḥ','two toes oriented leftward','I','Use as D61.'],
  ['D64','𓃆','','hand with palm down','',''],
  ['D65','𓃇','ḥnsḳty','Sidelock of hair','',''],
  ['D66','𓃈','spẖr','arm with reed pen','',''],
  ['D67','𓃉','','one dot','',''],
  ['E1','𓃒','kꜣ','bull','ID','Det. of cattle. ex. ng “bull,” mnmnt “cattle.” Ideo. in k3 “bull.”'],
  ['E2','𓃓','kꜣ','bull charging','ID','Det. in sm3 “fighting bull.” Ideo. in k3 nḫt “victorious bull,” (epithet of Pharaoh.)'],
  ['E3','𓃔','','calf','D','Det. in bḥs “calf”'],
  ['E4','𓃕','','sacred cow','D','Det. in ḥs3t “sacred cow.”'],
  ['E5','𓃖','','cow suckling calf','D','Det. in 3ms “show solicitude.”'],
  ['E6','𓃗','','horse','ID','Ideo. or Det. in ssmt “horse.” Det. in ibr “stallion.”'],
  ['E7','𓃘','','donkey','D','Det. in ʿ3 “donkey.”'],
  ['E8','𓃙','ỉb','kid','PD','Phon. ib, “kid.” Det. in ʿwt “flocks.”'],
  ['E9','𓃛','ỉw','newborn hartebeest','P','Phon. iw. In iwr “conceive.”'],
  ['E10','𓃝','','ram','D','Det. in b3 “ram,” ẖnmw “Khnum,”ʿwt ḥḏt “white flocks, sheep”'],
  ['E11','𓃞','','ram','D','Use as E10'],
  ['E12','𓃟','','pig','D','Det. in rri “pig.”'],
  ['E13','𓃠','','cat','D','Det. in miw “cat.”'],
  ['E14','𓃡','','dog','D','Det. in iw “dog,” ṯsm “hound.”'],
  ['E15','𓃢','Inpw','lying canine','ID','Det. or Ideo. in Inpw, “Anubis.”'],
  ['E16','𓃣','Inpw','lying canine on shrine','ID','Use as E15.'],
  ['E17','𓃥','sꜣb','jackal','ID','Det. or Ideo. in s3b “jackal” and “dignitary.”'],
  ['E18','𓃧','Wp-wꜣwt','wolf on standard','ID','Det. or Ideo. in Wp-w3wt “Opener of ways, Wepwawet.”'],
  ['E19','𓃨','Wp-wꜣwt','wolf on standard with mace','ID','Use as E18'],
  ['E20','𓃩','stẖ','Set-animal','ID','Det. or Ideo. in stẖ, stš “Seth.” Det. in ẖnnw “turmoil,” sh3 “confusion.”'],
  ['E21','𓃫','','lying Set-animal','D','Det. in nšni “storm, rage.”'],
  ['E22','𓃬','mꜣỉ','lion','ID','Det. or Ideo. in m3i “lion”'],
  ['E23','𓃭','rw','lying lion','PID','Phon. rw. Det. or Ideo. in rw “lion.”'],
  ['E24','𓃮','ꜣby','panther','ID','Det. or Ideo. in 3by “panther, leopard.”'],
  ['E25','𓃯','','hippopotamus','D','Det. in db, dib “hippopotamus.”'],
  ['E26','𓃰','ꜣbw','elephant','ID','Det. 3bw “elephant.” Ideo. in 3bw “Elephantine.”'],
  ['E27','𓃱','','giraffe','ID','Det. sr “foretell.” Det. or Ideo in mmi “giraffe.”'],
  ['E28','𓃲','','oryx','D','Det. in m3ḥḏ “oryx.”'],
  ['E29','𓃴','','gazelle','D','Det. in gḥs “gazelle.”'],
  ['E30','𓃵','','ibex','D','Det. in n3w, nr3w, ni3 “ibex.”'],
  ['E31','𓃶','','goat with collar','D','Det. in sʿḥ “rank, privilege.”'],
  ['E32','𓃷','','baboon','D','Det. in iʿn “baboon,” ky “monkey,” qnd “furious.”'],
  ['E33','𓃸','','monkey','D','Det. gf, gif “monkey.”'],
  ['E34','𓃹','wn','hare','P','Phono. wn. wnn “be.”'],
  ['E36','𓃻','ḏḥwty|nswt|nfr|sẖꜣ|sꜣ|ḏd','baboon','',''],
  ['E37','𓃼','šbt','baboon with receptacle and basket','',''],
  ['E38','𓃽','kꜣ','long-horned bull','',''],
  ['F1','𓃾','kꜣ','ox head','I','Ideo. in offering formulas for k3 “cattle.”'],
  ['F2','𓄀','','charging ox head','D','Det. in ḏnd “rage.”'],
  ['F3','𓄁','ꜣt','hippopotamus head','PID','Phono. 3t. Det. or Ideo. in “moment, attack.”'],
  ['F4','𓄂','ḥꜣt','forepart of lion','I','Ideo. in ḥ3t “front,” ḥ3ty “heart.”'],
  ['F5','𓄃','šsꜣ','hartebeest head','PID','Phon. šs3. Det. and Ideo. in šs3 “skilled” and “prayer.”'],
  ['F6','𓄄','šsꜣ','forepart of hartebeest','PID','Use as F5'],
  ['F7','𓄅','šfyt','ram head','ID','Det. in šft “ram’s head.” Det. or Ideo. in šfyt “worth, dignity.”'],
  ['F8','𓄆','šfyt','forepart of ram','ID','Use as F7'],
  ['F9','𓄇','pḥty','leopardhead','ID','Det. or Ideo. in pḥty “strength.”'],
  ['F10','𓄈','','head and neck of animal','D','Det. in ḫḫ “throat,” ʿm “swallow.”'],
  ['F11','𓄉','','head and neck of animal','D','Use as F10'],
  ['F12','𓄊','wsr','head and neck of animal','PI','Phon. wsr. Ideo in wsrt “neck.” In wsr “powerful”'],
  ['F13','𓄋','wp','horns','PI','Phon. wp. Ideo. in wpt “brow, beginning.”'],
  ['F14','𓄍','wpt-rnpt','horns with palm branch','I','Ideo. wpt-rnpt “Opening of the Year.”'],
  ['F15','𓄎','wpt-rnpt','horns with palm branch and sun','I','Use as F14'],
  ['F16','𓄏','ꜥb','horn','PID','Phono. ʿb. Det. or Ideo. in db “horn,” ʿb “horn.” In m-ʿb “together with.”'],
  ['F17','𓄐','ꜥbw','horn and vase from which water flows','ID','Det. or Ideo. in ʿbw “purification.”'],
  ['F18','𓄑','bḥ|ḥw','tusk','PID','Phono. bḥ, ḥw. Det. and Ideo. in ibḥ “tooth.” Det. in sbḥ “cry.”'],
  ['F19','𓄒','','lower jaw-bone of ox','D','Det. in ʿrt “jaw.”'],
  ['F20','𓄓','ns','tongue','PI','Phono. ns. In ns “tongue.” Ideo. in imy-r “overseer.”'],
  ['F21','𓄔','sḏm|ỉdn','ear of bovine','PID','Phono. sḏm, idn. Det. or Ideo. in msḏr “ear. Ideo. sḏm, “hear.”'],
  ['F22','𓄖','pḥwy','hind-quarters of lion','PI','Phono. pḥ in “reach,” pḥty “strength.” Ideo. for pḥwy “end.”'],
  ['F23','𓄗','ḫpš','forelegof ox','ID','Det. or Ideo. in ḫpš “strong arm, leg.”'],
  ['F24','𓄘','ḫpš','F23 reversed','ID','Use as F23.'],
  ['F25','𓄙','wḥm','leg ofox','P','Phono. wḥm in “hoof,” “repeat.”'],
  ['F26','𓄚','ẖn','skin of goat','P','Phono. ẖn. In ẖnw “interior,” ẖn “approach.”'],
  ['F27','𓄛','','skin of cow with bent tail','D','Det. in dḥr “hide,” msk3 “skin.”'],
  ['F28','𓄜','sꜣb','skin of cow with straight tail','P','Phono. s3b.'],
  ['F29','𓄝','st','cow\'s skin pierced by arrow','PID','Phono. st. Det. and Ideo. sti “pierce, shoot.”'],
  ['F30','𓄞','šd','water-skin','P','Phono. šd. In šdi “draw forth,” šdw “water skin.”'],
  ['F31','𓄟','ms','three skins tied together','P','Phono. ms. In msi “give birth.”'],
  ['F32','𓄡','ẖ','animal\'s belly','PI','Phono. ẖ. Ideo. in ẖt “belly, body.”'],
  ['F33','𓄢','sd','tail','PID','Phono. sd. Det. and Ideo in sd “tail.”'],
  ['F34','𓄣','ỉb','heart','','W21'],
  ['F35','𓄤','nfr','heart andwindpipe','P','Phono. nfr. In nfr “good, beautiful.”'],
  ['F36','𓄥','smꜣ','lung and windpipe','','P8'],
  ['F37','𓄦','ỉꜣt','backbone and ribs and spinal cord','ID','Det. or Ideo. in i3t “back.” Det. in psd “back.”'],
  ['F38','𓄨','','backbone and ribs','D','Det. in psd “back.”'],
  ['F39','𓄪','ỉmꜣḫ','backbone and spinal cord','ID','Det. and Ideo. in im3ḫ “spine” and “honor.”'],
  ['F40','𓄫','ꜣw','backbone and spinal cords','P','Phono. 3w.'],
  ['F41','𓄬','','vertebrae','D','Det. in psd “back.”'],
  ['F42','𓄭','spr','rib','','D13'],
  ['F43','𓄮','','ribs','D','Det. in sḥpt “ribs.”'],
  ['F44','𓄯','ỉwꜥ|ỉsw','bone with meat','P','Phono. iwʿ, isw. In iwʿ inherit,” siw “exchange.”'],
  ['F45','𓄰','dỉt','uterus','ID','Det. or Ideo. in dit “vulva, cow.”'],
  ['F46','𓄲','ḳꜣb','intestine','','F49'],
  ['F47','𓄴','ḳꜣb','intestine','','Use as F46.'],
  ['F48','𓄶','ḳꜣb','intestine','','Use as F46.'],
  ['F49','𓄷','ḳꜣb','intestine','','Use as F46.'],
  ['F50','𓄸','spḫr','combination of F46 and S29','P','Phono. spḫr, “write, copy.”'],
  ['F51','𓄹','ỉs|ỉst|ws','piece of flesh','PD','Phono. is, ist, ws. Det. ḥʿ “flesh,” iwf “meat.”'],
  ['F52','𓄽','','excrement','D','Det. in ḥs “excrement.”'],
  ['F53','𓄾','mt','divine rod with ram head','',''],
  ['G1','𓄿','ꜣ','Egyptian vulture','P','Phono. 3. In 3 “vulture.’'],
  ['G2','𓅀','ꜣꜣ','two Egyptian vultures','P','Phono 33. In m33 “see.”'],
  ['G3','𓅁','mꜣ','combination of Egyptian vulture and sickle','P','Phono. in m3. In sm3wy “renew.”'],
  ['G4','𓅂','tyw','buzzard','P','Phono. tyw.'],
  ['G5','𓅃','ḥrw','falcon','I','Ideo. ḥrw “Horus.”'],
  ['G6','𓅄','','combination of falcon and flaggellum','','De.t in bik “falcon.”'],
  ['G7','𓅆','','falcon on standard','D','Det. imn “Amun,” nsw “king,” divine. 1st sing. pro. i, wi, with divine speaker.'],
  ['G8','𓅉','Ḥr|bỉk','falcon on collar of beads','I','Ideo. Hr/bik nbw “Golden Horus/falcon.”'],
  ['G9','𓅊','rꜥ-ḥrw-ꜣḫty','falcon with sun on head','I','Ideo. in rʿ-ḥrw-3ḫty “Re-Horakhty.”'],
  ['G10','𓅋','','falcon in Sokar barque','D','Det. in skr “Sokar,” ḥnw “Sokar bark.”'],
  ['G11','𓅌','','image of falcon','D','Det. in ʿšm, ʿẖm, ʿḫm “divine image,” šnbt “breast.”'],
  ['G12','𓅎','','combination of image of falcon and flagellum','D','Use as G11.'],
  ['G13','𓅏','ḥrw','image of falcon with two plumes','ID','Ideo. ḥrw nḫny “Horus of Hierakonopolis.” Det. in spdw “Sopdu.”'],
  ['G14','𓅐','mwt|mt','vulture','P','Phono. mwt, mt. In mwt “mother.”'],
  ['G15','𓅑','','combination of vulture and flagellum','D','Det. in mwt “Mut.”'],
  ['G16','𓅒','nbty','vulture and cobra each on a basket','I','Ideo. in nbty “Two Ladies” (title of Pharaoh)'],
  ['G17','𓅓','m','owl','P','Phono. m.'],
  ['G18','𓅔','mm','two owls','P','Phono. mm.'],
  ['G19','𓅕','mỉ|m','combination of owl and forearm with conical loaf','P','Phono. mi, m.'],
  ['G20','𓅖','mỉ|m','combination of owl and forearm','P','Use as G19.'],
  ['G21','𓅘','nḥ','guineafowl','P','Phono. nḥ. In nḥḥ “eternity.”'],
  ['G22','𓅙','ḏb|ḏbt','hoopoe','P','Phono. ḏb/ḏbt.'],
  ['G23','𓅚','rḫyt','lapwing','ID','Det. and Ideo. in rḫyt “commoners.”'],
  ['G24','𓅛','rḫyt','lapwing with twisted wings','ID','Use as G23.'],
  ['G25','𓅜','ꜣḫ','northern bald ibis','P','Phono. 3ḫ. In “spirit.”'],
  ['G26','𓅝','','sacred Ibis on standard','D','Det. in ḏḥwty “Thoth.”'],
  ['G27','𓅟','dšr','flamingo','P','Phono. dšr. In dšr “red,” “flamingo.”'],
  ['G28','𓅠','gm','glossy ibis','P','Phono. gm. In gmi “find.”'],
  ['G29','𓅡','bꜣ','saddle-billed stork','P','Phono. b3. In “soul.”'],
  ['G30','𓅢','bꜣw','three saddle-billed storks','I','Ideo. in b3w “spirits, strength.”'],
  ['G31','𓅣','','heron','D','Det. in šnty “heron.”'],
  ['G32','𓅤','bꜥḫỉ','heron on perch','ID','Det. or Ideo. in bʿḫi “inundated.”'],
  ['G33','𓅥','','cattle egret','D','Det. sd3 “tremble.”'],
  ['G34','𓅦','','ostrich','D','Det. in niw “ostrich.”'],
  ['G35','𓅧','ꜥḳ','cormorant','P','Phono. ʿq. In ʿq “enter.”'],
  ['G36','𓅨','wr','swallow','P','Phono. wr. In wr “great.”'],
  ['G37','𓅪','','sparrow','D','Det. in nḏs “small,” bin “bad.”'],
  ['G38','𓅬','gb','goose','PD','Phono. gb. In gb “Geb.” Det. in wf3 “talk,” wsf “idle,” ḥtm “perish.”'],
  ['G39','𓅭','sꜣ','pintail duck','PD','Phono. s3. In s3 “son.” Det. in si “duck.”'],
  ['G40','𓅮','pꜣ','pintail flying','P','Phono. p3. In p3 “the,” “fly.”'],
  ['G41','𓅯','ḫn','pintail alighting','P','Phono. ḫn. In ḫni “alight, halt,” ḫn “speech,” qm3 “throw,” “create.”'],
  ['G42','𓅰','wšꜣ','widgeon','ID','Det. and Ideo. in wš3 “fatten,” ḏf3w “provisions.”'],
  ['G43','𓅱','w','quail chick','P','Phono. w.'],
  ['G44','𓅳','ww','two quail chicks','P','Phono. ww. In pḥww “end.”'],
  ['G45','𓅴','wꜥ','combination of quail chick and forearm','P','Phono wʿ.In wʿw “soldier.”'],
  ['G46','𓅶','mꜣw','combination of quail chick and sickle','P','Phono. m3w.'],
  ['G47','𓅷','ṯꜣ','duckling','P','Phono. ṯ3. In ṯ3y “male.”'],
  ['G48','𓅸','sš','three ducklings in nest','I','Ideo. in sš “nest.”'],
  ['G49','𓅹','sš','three ducklings in pool','ID','Det. or Ideo. in sš “nest.”'],
  ['G50','𓅺','rḫty','two plovers','I','Ideo. for rḫty “washerman.”'],
  ['G51','𓅻','','bird pecking at fish','D','Det. in ḥ3m “catch fish.”'],
  ['G52','𓅼','','goose picking up grain','D','Det. in snm “feed.”'],
  ['G53','𓅽','bꜣ','human-headed bird with bowl with smoke','I','Ideo. in b3 “soul.”'],
  ['G54','𓅾','snḏ','plucked bird','P','Phono. snḏ. In snḏ “fear.”'],
  ['H1','𓅿','ꜣpd','head of pintail','ID','Ideo. in 3pd “bird.” Det. in wšn “wring the neck of birds.”'],
  ['H2','𓆀','mꜣꜥ|wšm|pꜣḳ','head of heron','PD','Phono. m3ʿ, wšm, p3q. Det. in m3ʿ “temple of the head,” “true.”'],
  ['H3','𓆁','pꜣḳ','head of spoonbill','P','Phono. p3q.'],
  ['H4','𓆂','nr','head of vulture','PD','Phono. nr. Det. in nrt “vulture.”'],
  ['H5','𓆃','','wing','D','Det. in ḏnḥ “wing.”'],
  ['H6','𓆄','šw','feather','PID','Phono. šw. Ideo. in šwt “feather.” Det. and Ideo. in m3ʿt “truth.”'],
  ['H7','𓆆','šꜣ|šꜣt','bird foot','P','Phono. š3, š3t. In š3t “Shat” (location).'],
  ['H8','𓆇','sꜣ','egg','ID','Ideo. in s3 “son.” Det. sḥwt “egg.”'],
  ['I1','𓆈','ꜥšꜣ','gecko','PD','Phono. ʿš3. Det. for lizard. ex. ʿš3 “lizard” and ʿš3 “many, numerous.”'],
  ['I2','𓆉','štyw','turtle','ID','Det. or Ideo. for štyw “turtle.”'],
  ['I3','𓆊','','crocodile','ID','Det. or Ideo. for crocodile. ex. msḥ “crocodile,” 3d “agressive.” Ideo. ity “sovereign,” when reduplicated'],
  ['I4','𓆋','','crocodileon shrine','D','Det. sbk “Sobek.”'],
  ['I5','𓆌','','crocodile with curved tail','D','Det. in s3q “collect, gather.”'],
  ['I6','𓆎','km','crocodile scales','','Aa4'],
  ['I7','𓆏','wḥm','frog','ID','Det. in ḥqt “Heqet.” Ideo. wḥm ʿnḫ “repeating life.”'],
  ['I8','𓆐','ḥfn','tadpole','ID','Det. ḥfnr “tadpole.” Ideo. ḥfn “100,000.”'],
  ['I9','𓆑','f','horned viper','PD','Phono. f. Det. in it “father.”'],
  ['I10','𓆓','ḏ','cobra in repose','P','Phono. ḏ.'],
  ['I11','𓆕','ḏḏ','two cobras','P','Phono ḏḏ.'],
  ['I12','𓆗','','cobra erect as on the forehead of the Pharaoh','D','Det. in ʿirt “uraeus.” Det. of goddesses.'],
  ['I13','𓆘','','erect cobra on basket','D','Det. in w3ḏt “Wadjet.”'],
  ['I14','𓆙','','snake','D','Det. ḥf3w “snake, serpent.”'],
  ['I15','𓆚','','snake','D','Use as I14.'],
  ['K1','𓆛','ỉn','tilapia','P','Phono. in. In int “bulti.”'],
  ['K2','𓆜','bw','barbel','P','Phono. bw. In bwt “abomination.”'],
  ['K3','𓆝','ꜥḏ','mullet','P','Phono. ʿḏ. In ʿḏ-mr “district administrator.”'],
  ['K4','𓆞','ẖꜣ','elephant-snout fish','P','Phono. ẖ3. In ẖ3t “oxyrhynchus.”'],
  ['K5','𓆟','bs','Petrocephalus bane','PD','Phono. bs. Det. in bsi “introduce.”'],
  ['K6','𓆠','nšmt','fish scale','ID','Det. and Ideo. in nšmt “fish scale.”'],
  ['K7','𓆡','','puffer','D','Det. špt “discontented.”'],
  ['K8','𓆢','nꜥr','catfish','',''],
  ['L1','𓆣','ḫpr','dung beetle','P','Phono. ḫpr. In ḫpr “being, exist, become.'],
  ['L2','𓆤','bỉty','bee','I','Ideo. for bity “King of Lower Egypt.”'],
  ['L3','𓆦','','fly','D','Det. in ʿff “fly.”'],
  ['L4','𓆧','','locust','D','Det. in snḥm “locust.”'],
  ['L5','𓆨','','centipede','D','Det. sp3 “centipede.”'],
  ['L6','𓆩','','shell','','N33'],
  ['L7','𓆫','srḳt','scorpion','ID','Det. and Ideo. in srqt “Selket.”'],
  ['L8','𓆬','','','',''],
  ['M1','𓆭','ỉmꜣ','tree','PD','Phono. im3. Det. nhwt, mnw “trees.”'],
  ['M2','𓆰','ḥn','plant','PD','Phono. ḥn. In ḥni “rush,” ḥnw “vessel.” Det. in is “tomb.”'],
  ['M3','𓆱','ḫt','branch','P','Phono. ḫt. In ḫt “wood,” ḫtyw “terrace,” nḫt “strong.”'],
  ['M4','𓆳','rnpt','palm branch','ID','Ideo. in rnpt “year,” ḥsbt “regnal year.” Det. in tr “time.”'],
  ['M5','𓆴','tr','combination of palm branch and flat loaf','ID','Det. or Ideo. in tr “time, season.”'],
  ['M6','𓆵','tr','combination of palm branch and mouth','ID','Det. or Ideo. in tr “time, season.”'],
  ['M7','𓆶','rnpỉ','combination of palm branch and stool','ID','Det. or Ideo. in rnpi “young.”'],
  ['M8','𓆷','ꜣḫt','pool with lotus flowers','PI','Phono š3. In š3 “marsh.” Ideo. 3ḫt “Inundation” (season).'],
  ['M9','𓆸','','lotus flower','ID','Det. or Ideo in sšn “lily.”'],
  ['M10','𓆹','','lotus bud with straight stem','D','Det. in nḥbt “lily bud.”'],
  ['M11','𓆻','wdn','flower on long twisted stalk','ID','Det. or Ideo. in wdn “offer.”'],
  ['M12','𓆼','ḫꜣ','one lotus plant','P','Phono. ḫ3. In ḫ3w nw sšn “lily plants” ḫ3 “1,000,” sḫ3 “remember.”'],
  ['M13','𓇅','wꜣḏ|wḏ','papyrusstem','P','Phono. w3ḏ, wḏ.'],
  ['M14','𓇆','wꜣḏ','combination of papyrus and cobra','P','Phono. w3ḏ. In w3ḏ wr “the sea.”'],
  ['M15','𓇇','ꜣḫ','clump of papyrus with buds','PD','Phono. 3ḫ. In 3ḫ-bit “Chemmis.” Det. of Papyrus.'],
  ['M16','𓇉','ḥꜣ','clump of papyrus','PD','Phono. ḥ3 . In ḥ3q “capture.” Det. in “The Delta.”'],
  ['M17','𓇋','ỉ','reed','P','Phono. i. Phono. y, when doubled.'],
  ['M18','𓇍','ỉ','combination of reed and legs walking','P','Phono i. In ii “come.”'],
  ['M19','𓇎','ꜥꜣbt','heaped conical cakes between reed and club','ID','Det. and Ideo. in ʿ3bt “offering.”'],
  ['M20','𓇏','','field of reeds','D','Det. sḫt “marshland,” sm “occupation.”'],
  ['M21','𓇐','','reeds with root','D','Det. in sm “plant,” “help.”'],
  ['M22','𓇑','nḫb','rush','P','Phono. nḫb . Phono. nn, when doubled. In nḫbt “germination,” “Nehkbet.”'],
  ['M23','𓇓','sw','sedge','PI','Phono. sw. Ideo. nswt “king.”'],
  ['M24','𓇔','rsw','combination of sedge and mouth','I','Ideo. rsw “south.”'],
  ['M25','𓇖','rsw','combination of flowering sedge and mouth','I','Use as M24.'],
  ['M26','𓇗','šmꜥ','floweringsedge','PI','Phono. šmʿ. Ideo. šmʿw in “Upper Egypt.”'],
  ['M27','𓇘','šmꜥ','combination of flowering sedge and forearm','P','Phono. šmʿ.'],
  ['M28','𓇙','','combination of flowering sedge and hobble','I','Ideo. in title wr mḏw šmʿw “Greatest of the tens of Upper Egypt.”'],
  ['M29','𓇛','nḏm','Carob seed-pod','P','Phono. nḏm. In nḏm “sweet.'],
  ['M30','𓇜','bnr','root','ID','Det. or Ideo. bnr “sweet.”'],
  ['M31','𓇝','','rhizome','D','Det. in rd “grow.”'],
  ['M32','𓇟','','rhizome','D','Use as M31'],
  ['M33','𓇠','','3 grains horizontally','I','Ideo. in it “barley, corn.”'],
  ['M34','𓇣','btỉ','ear of emmer','ID','Det. or Ideo. in bti “emmer.”'],
  ['M35','𓇤','','stack(of grain)','','X1'],
  ['M36','𓇥','ḏr','bundle of flax','','U30'],
  ['M37','𓇦','ḏr','bundle of flax','P','Phono. ḏr.'],
  ['M38','𓇧','','wide bundle of flax','D','Det. in mḥʿ “flax,” dm3 “bind together.”'],
  ['M39','𓇨','','basket of fruit or grain','D','Det. in rnpt “vegetables.”'],
  ['M40','𓇩','','bundle of reeds','','P11'],
  ['M41','𓇫','','piece of wood','D','Det. in ʿš “cedar.”'],
  ['M42','𓇬','wn','flower','P','Phono. wn. In wnm “eat,” ḥwn “be young.”'],
  ['M43','𓇭','ỉrp','vine on trellis','ID','Det. or Ideo. in irp “wine.”'],
  ['M44','𓇮','','thorn','D','Det. spd “sharp.”'],
  ['N1','𓇯','pt','sky','','N39'],
  ['N2','𓇰','grḥ','sky with sceptre','ID','Det. or Ideo. grḥ “night.”'],
  ['N3','𓇱','grḥ','sky with sceptre','ID','Use as N2.'],
  ['N4','𓇲','šnyt','sky with rain','ID','Det. or Ideo. šnyt “rain,” i3dt “dew.”'],
  ['N5','𓇳','rꜥ','sun','','Aa1'],
  ['N6','𓇴','','sun with uraeus','ID','Det. or ideo in rʿ “sun, Re.”'],
  ['N7','𓇵','','combination of sun and butcher\'s block','D','Det. ẖrt-hrw “daytime.”'],
  ['N8','𓇶','wbn','sunshine','PID','Phono. wbn. Det. or Ideo. 3ḫw “sunshine,” psḏ “shine,” wbn “rise.”'],
  ['N9','𓇷','psḏ','moon with lower half obscured','P','Phono. psḏ. In psḏt “Ennead.”'],
  ['N10','𓇸','psḏ','moon with lower section obscured','P','Use as N9.'],
  ['N11','𓇹','ꜣbd','crescent moon','ID','Ideo. 3bd “month.” Det. iʿḥ “moon.”'],
  ['N12','𓇺','','crescent moon','D','Det. iʿḥ “moon.”'],
  ['N13','𓇻','mḏdỉwnt','combination of crescent moon and star','I','Ideo. mḏdiwnt “half month festival.”'],
  ['N14','𓇼','sbꜣ|dwꜣ','star','PI','Phono. sb3, dw3. In sb3 “star,” dw3 “morning.” Ideo. wnwt “hour.”'],
  ['N15','𓇽','dwꜣt','star in circle','I','Ideo. in dw3t “netherworld.”'],
  ['N16','𓇾','tꜣ','land with grains','PD','Phono. t3. In t3 “land, earth.”Det. in ḏt “eternity.”'],
  ['N17','𓇿','tꜣ','land','PD','Use as N16.'],
  ['N18','𓈀','ỉw','sandy tract','I','Ideo. in iw “island.”'],
  ['N19','𓈃','ꜣḫt','two sandy tracts','I','Ideo. in 3ḫt “horizon,” ḥrw-3ḫty “Horakhty.”'],
  ['N20','𓈄','wḏb','tongue of land','PD','Phono. wḏb. In wḏb “shore.” Det. in ḥ3b-sd “Sed Festival.”'],
  ['N21','𓈅','ỉdb','short tongue of land','I','Ideo. in idb “bank,” idbwy “two banks.”'],
  ['N22','𓈆','','broad tongue of land','D','Det. in ʿḥt “field,” sḫt “field.”'],
  ['N23','𓈇','','irrigation canal','','O45'],
  ['N24','𓈈','spꜣt','irrigation canal system','ID','Det. or Ideo. in sp3t “nome.”'],
  ['N25','𓈉','ḫꜣst','three hills','I','Ideo. in ḫ3st “foreign land, hill country.”'],
  ['N26','𓈋','ḏw','two hills','P','Phono. ḏw “mountain.”'],
  ['N27','𓈌','ꜣḫt','sun over mountain','I','Ideo. in 3ḫt “horizon.”'],
  ['N28','𓈍','ḫꜥ','rays of sun over hill','P','Phono. ḫʿ. In ḫʿ “appear.”'],
  ['N29','𓈎','ḳ','slope of hill','P','Phono. q.'],
  ['N30','𓈏','ỉꜣt','mound of earth','ID','Det. or Ideo. in i3t “mound.”'],
  ['N31','𓈐','wꜣt','road with shrubs','ID','Det. and Ideo. in w3t “road.”'],
  ['N32','𓈑','','lump of clay','D','Det. in sin “clay.”'],
  ['N33','𓈒','','grain','D','Det. in nbw “gold.”'],
  ['N34','𓈔','bỉꜣ','ingot of metal','I','Ideo. in bi3, ḥmt “copper.”'],
  ['N35','𓈖','n','ripple of water','P','Phono. n.'],
  ['N36','𓈘','mr','canal','P','Phono. mr. In mr “canal.”'],
  ['N37','𓈙','š','pool','P','Phono. š. In š “pool.”'],
  ['N38','𓈛','š','deep pool','P','Use as N37.'],
  ['N39','𓈜','š','pool with water','P','Use as N37.'],
  ['N40','𓈝','šm','poolwith legs','P','Phono. šm. In šm “to go.”'],
  ['N41','𓈞','ḥm','well with ripple of water','PD','Phono. ḥm. In ḥmt “wife.” Det. in bi3 “copper.”'],
  ['N42','𓈟','ḥm','well with line of water','PD','Use as N41.'],
  ['O1','𓉐','pr','house','P','Phono. pr. In pr “house,” pri “go.”'],
  ['O2','𓉒','pr-ḥḏ','combination of house and mace with round head','I','Ideo. in pr-ḥḏ “treasury.”'],
  ['O3','𓉓','prt-ḫrw','combination of house, oar, tall loaf and beer jug','I','Ideo. in prt-ḫrw “invocation offering.”'],
  ['O4','𓉔','h','shelter','P','Phono. h.'],
  ['O5','𓉕','nm','winding wall from upper-left corner','P','Phono. nm. In nmi “traverse.”'],
  ['O6','𓉗','ḥwt','enclosure','I','Ideo. in ḥwt “temple, tomb, enclosure.”'],
  ['O7','𓉞','ḥwt','combination of enclosure and flat loaf','I','Use as O6.'],
  ['O8','𓉟','ḥwt-ꜥꜣ','combination of enclosure, flat loaf and wooden column','I','Ideo. in ḥwt-ʿ3 “Great temple, enclosure.”'],
  ['O9','𓉠','nbt-ḥyt','combination of enclosure, flat loaf and basket','I','Ideo. in nbt-ḥyt “Nephthys.”'],
  ['O10','𓉡','ḥwt-ḥrw','combination of enclosure and falcon','I','Ideo. in ḥwt-ḥrw “Hathor.”'],
  ['O11','𓉥','ꜥḥ','palace','',''],
  ['O12','𓉦','ꜥḥ','combination of palace and forearm','I','Ideo. in ʿḥ “palace.”'],
  ['O13','𓉧','','battlemented enclosure','D','Det. in sbḫ “enclose,” sbḫt “gateway.”'],
  ['O14','𓉨','','part of battlemented enclosure','D','Use as O13'],
  ['O15','𓉩','wsḫt','enclosure with cup and flat loaf','I','Ideo. in wsḫt “hall.”'],
  ['O16','𓉪','tꜣyt','gateway with serpents','ID','Det. or Ideo. in t3yt “curtain,” t3yty “he of the curtain” (vizier title).'],
  ['O17','𓉫','tꜣyt','open gateway with serpents','ID','Use as O16'],
  ['O18','𓉬','kꜣr','shrine in profile','ID','Det. or Ideo. in k3r “shrine, chapel.”'],
  ['O19','𓉭','','shrine with fence','D','Det. in pr-wr “Great House.”'],
  ['O20','𓉯','','shrine','D','Det. in itrt “row of sanctuaries,” ḫm “shrine.”'],
  ['O21','𓉱','sḥ-nṯr','façade of shrine','ID','Det. or Ideo. in sḥ-nṯr “divine shrine.”'],
  ['O22','𓉲','sḥ','booth with pole','ID','Det. or Ideo. in sḥ “counsel,” “booth.”'],
  ['O23','𓉳','ḥꜣb-sd','double platform','I','Ideo. in ḥ3b-sd “Sed Festival.”'],
  ['O24','𓉴','','pyramid','D','Det. in mr “pyramid.”'],
  ['O25','𓉶','tḫn','obelisk','ID','Det. or Ideo. in tḫn “obelisk.”'],
  ['O26','𓉸','wḏ','stela','ID','Det. or Ideo. in wḏ “stela.”'],
  ['O27','𓉹','','hall of columns','D','Det. in ḫ3 “office,” ḫ3wy “night.”'],
  ['O28','𓉺','ỉwn','column','P','Phono iwn. In iwnw “Heliopolis,” iwn “column.”'],
  ['O29','𓉻','ꜥꜣ','horizontal wooden column','P','Phono. ʿ3. In ʿ3 “great.”'],
  ['O30','𓉽','sḫnt','support','','F45'],
  ['O31','𓉿','','door','D','Det. in ʿ3 “door,” sn, wn “open.”'],
  ['O32','𓊀','','gateway','D','Det. in sb3 “door,” sbḫt “gateway.”'],
  ['O33','𓊁','','façade of palace','D','Det. in srḫ “banner.”'],
  ['O34','𓊃','s','door bolt','P','Phono. s. In s “bolt.”'],
  ['O35','𓊄','s','combination of bolt and legs','P','Phono. s. In sbi “go,” “perish,” ms “bring.”'],
  ['O36','𓊅','ỉnb','wall','','V29'],
  ['O37','𓊊','','falling wall','D','Det. in whn “overthrow,” gs3 “tilt.”'],
  ['O38','𓊋','ḳnbt','corner of wall','I','Ideo. in qnbt “court, corner, magistrates.”'],
  ['O39','𓊌','','stone','D','Det. in inr “stone,” dbni “deben (weight),” ḏbt “brick.”'],
  ['O40','𓊍','','stair single','D','Det. in rwd “stairwaway,” ḫtyw “terrace.”'],
  ['O41','𓊎','','double stairway','D','Det. in q3y “high place,” iʿr “ascend.”'],
  ['O42','𓊏','šsp','fence','',''],
  ['O43','𓊐','šsp','low fence','','Use as O42'],
  ['O44','𓊑','ỉꜣt','emblem of Min','I','Ideo. in i3t “rank, office.”'],
  ['O45','𓊒','ỉpt','domed building','ID','Det. or Ideo. in ipt “harim.”'],
  ['O46','𓊓','ỉpt','domed building','ID','Use as O45.'],
  ['O47','𓊔','nḫn','enclosed mound','I','Ideo. in nḫn “Hierakonpolis.”'],
  ['O48','𓊕','','enclosed mound','','S10'],
  ['O49','𓊖','nỉwt','village','I','Ideo. in niwt “town.”'],
  ['O50','𓊗','sp','threshing floor','P','Phono. sp. In sp “occasion, time, event,” sp sn “two times.”'],
  ['O51','𓊚','šnwt','pile of grain','ID','Det. or Ideo. in šnwt “granary.”'],
  ['P1','𓊛','','','D','Det. of boats. In dpt “ship,” ḥʿw “ships,” ḫdi “sail downstream.”'],
  ['P2','𓊝','','ship under sail','D','Det. in ḫnti “sail upstream.”'],
  ['P3','𓊞','','sacred barque','D','Det. wi3 “sacred bark,” ḏ3i “cross”'],
  ['P4','𓊠','wḥꜥ','boat with net','P','Phono. wḥʿ. In wḥʿ “fisherman.”'],
  ['P5','𓊡','ṯꜣw','sail','ID','Det. or Ideo. in ṯ3w “wind, breath.” Det. mḥyt “north wind.”'],
  ['P6','𓊢','ꜥḥꜥ','mast','P','Phono. ʿḥʿ. In ʿḥʿ “stand.”'],
  ['P7','𓊣','ꜥḥꜥ','combination of mast and forearm','P','Use as P6.'],
  ['P8','𓊤','ḫrw','oar','P','Phono ḫrw. In m3ʿ ḫrw “justified” ḫrw “voice,” ḫrwy “enemy.”'],
  ['P9','𓊥','','combination of oar and horned viper','I','Ideo for ḫr.fy “says, said.”'],
  ['P10','𓊦','','rudder','D','Det. in ḥmw “steering oar,” ḥmy “steerer”'],
  ['P11','𓊧','','mooringpost','D','Det. in mnit “mooring post.”'],
  ['Q1','𓊨','st|ws','seatthrone','P','Phono. st, ws. In st “seat, place,” wsir “Osiris,” ḥtm “perish.”'],
  ['Q2','𓊩','ws','carryingchair','P','Phono. ws. In wsir “Osiris.”'],
  ['Q3','𓊪','p','stool','','O47'],
  ['Q4','𓊫','','headrest','D','Det. in wrs “headrest.”'],
  ['Q5','𓊬','','chest','D','Det. in hn “box,” ʿfdt “chest.”'],
  ['Q6','𓊭','ḳrs','sarcophagus','ID','Det. or Ideo. in qrs “bury,” qrsw “coffin.”'],
  ['Q7','𓊮','','brazier','D','Det. of fire. In ḫt “fire,” sḏt “flame,” srf “temperature.”'],
  ['R1','𓊯','ḫꜣt','high table with offerings','ID','Det. or Ideo. in ḫ3t, ḫ3wt “offering table.”'],
  ['R2','𓊰','ḫꜣt','table with slices of bread','ID','Use as R1.'],
  ['R3','𓊲','wḥḏw','low table with offerings','ID','Det. or Ideo. in wḥḏw “offering table.”'],
  ['R4','𓊵','ḥtp','loaf on mat','P','Phono. ḥtp. In ḥtp “altar, rest, be pleased.”'],
  ['R5','𓊶','kꜣp','narrow censer','ID','Det. or Ideo. in k3p “fumigate.”'],
  ['R6','𓊷','kꜣp','broad censer','ID','Use as R5'],
  ['R7','𓊸','sntr','bowl with smoke','ID','Det. or Ideo. in sntr “incense.”'],
  ['R8','𓊹','nṯr','Cloth on pole','','T3'],
  ['R9','𓊺','bd','combination of cloth on pole and bag','ID','Det. or Ideo. in bd “incense.”'],
  ['R10','𓊻','ẖrt-nṯr','combination of cloth on pole, butcher\'s block and slope of hill','I','Ideo. in ẖrt-nṯr “necropolis.”'],
  ['R11','𓊽','ḏd','reed column','P','Phono. ḏd. In ḏd “stable,” ḏdw “Busiris.”'],
  ['R12','𓊾','','standard','D','Det. in i3t “standard.”'],
  ['R13','𓊿','ỉmnt','falcon and feather on standard','I','Ideo. in imnt “West,” wnmi “right.”'],
  ['R14','𓋀','ỉmnt','Emblem of the West','I','Ideo. in imnt “West,” wnmi “right.”'],
  ['R15','𓋁','ỉꜣbt','spear, Emblem of the East','I','Ideo. in i3bt “East,” i3by “left.”'],
  ['R16','𓋂','','sceptre with feathers and string','ID','Det. or Ideo in wḫ “Qus emblem.”'],
  ['R17','𓋄','tꜣ-wr','wig on pole','ID','Det. or Ideo. in t3-wr “This,” “nome of Abydos.”'],
  ['R18','𓋅','tꜣ-wr','combination of wig on pole and irrigation canal system','ID','Use as R17'],
  ['R19','𓋆','','scepter with feather','D','Det. in w3st “Thebes.”'],
  ['R20','𓋇','sšt','flower with horns','I','Ideo. in sšt “Seshat.”'],
  ['R21','𓋈','sšt','flower with horns','I','Use as R20.'],
  ['R22','𓋉','ḫm','two narrow belemnites','PI','Phono. ḫm. In ḫm “shrine.” With standard, Ideo. in mnw “Min.”'],
  ['R23','𓋊','ḫm','two broad belemnites','PI','Use as R22'],
  ['R24','𓋋','','two bows tied horizontally','D','Det. in nit “Neith.”'],
  ['R25','𓋌','','two bows tied vertically','D','Use as R24.'],
  ['R26','𓋍','smꜣ-tꜣwy','combination of land, lung and windpipe, lily, and papyrus','',''],
  ['R27','𓋎','nt','two arrows crossed over a shield','',''],
  ['R28','𓋏','bꜣt','Bat','',''],
  ['R29','𓋐','ỉtrt|ỉtrty','niche with serpent','',''],
  ['S1','𓋑','ḥḏt','white crown','ID','Det. or Ideo. in ḥḏt “white crown.”'],
  ['S2','𓋒','ḥḏt','combination of white crown and basket','ID','Det. or Ideo. in ḥḏt “white crown.”'],
  ['S3','𓋔','n','red crown','PID','Phono. n. Det. or Ideo in dšrt “Red Crown.”'],
  ['S4','𓋕','n','combination of red crown and basket','PID','Use as S3.'],
  ['S5','𓋖','sḫmty','Pschent Crown','ID','Det. or Ideo. in sḫmty “double crown.”'],
  ['S6','𓋗','sḫmty','combination of Pschent Crown and basket','ID','Use as S5.'],
  ['S7','𓋙','ḫprš','blue crown','ID','Det. or Ideo. in ḫprš “blue crown.”'],
  ['S8','𓋚','ꜣtf','Atefcrown','ID','Det. or Ideo. in 3tf “atef crown.”'],
  ['S9','𓋛','šwty','shuty-crown (two falcon feathers)]','ID','Det. or Ideo. in šwty “double plumes.”'],
  ['S10','𓋜','mḏḥ','headband','P','Phono mḏḥ. In mḏḥ “fillet.”'],
  ['S11','𓋝','wsḫ','broad collar','','F38'],
  ['S12','𓋞','nbw','collar of beads','ID','Det. or Ideo. in nbw “gold,” ḥḏ “silver.”'],
  ['S13','𓋟','nb','combination of collar of beads and foot','P','Phono. nb.'],
  ['S14','𓋠','ḥḏ','combination of collar of beads and mace with round head','I','Ideo. in ḥḏ “silver.”'],
  ['S15','𓋣','ṯḥn','pectoral','ID','Det. or Ideo. in ṯḥn “sparkle,” ṯḥnt “faience.”'],
  ['S16','𓋤','ṯḥn','','ID','Use as S15.'],
  ['S17','𓋥','ṯḥn','pectoral','ID','Use as S15'],
  ['S18','𓋧','mnỉt','"menatnecklaceandcounterpoise"','ID','Det. or Ideo. in mnit “bead necklace.”'],
  ['S19','𓋨','sḏꜣwty','sealwith necklace','ID','Ideo. in sḏ3wty “treasurer,” sḏ3w “precious.” Det. or Ideo. in ḫtm “seal.”'],
  ['S20','𓋩','ḫtm','necklace with seal','I','Ideo. in ḫtm “seal.”'],
  ['S21','𓋪','','ring','D','Det. in iwʿw, ʿʿw, sšw “ring.”'],
  ['S22','𓋫','sṯ','shoulder-knot','PID','Phono. sṯ. Det. or Ideo. in t3-wr “port.”'],
  ['S23','𓋬','dmḏ','two whipswith shen ring','P','Phono dmḏ. In dmḏ “unite.”'],
  ['S24','𓋭','ṯs','girdle knot','','T11'],
  ['S25','𓋮','ỉꜥꜣw','garment with ties','I','Ideo. in iʿ3w “guide.”'],
  ['S26','𓋯','šndyt','apron','ID','Det. or Ideo. in šndyt “apron.”'],
  ['S27','𓋲','mnḫt','cloth with two strands','ID','Det. or Ideo. in mnḫt “clothing.”'],
  ['S28','𓋳','','cloth with fringe on top and folded cloth','D','Det. in ḥbs “clothing,” ḥ3p “conceal,” kfi “uncover.”'],
  ['S29','𓋴','s','folded cloth','P','Phono. s. In ʿnḫ.(w) (w)ḏ3 snb “may he live, be prosperous, be healthy.” (L.P.H.)'],
  ['S30','𓋵','sf','combination of folded cloth and horned viper','P','Phono. sf. In sf “yesterday.”'],
  ['S31','𓋶','smꜣ','combination of folded cloth and sickle','P','Phono. sm3. In sm3 “fighting bull.”'],
  ['S32','𓋷','sỉꜣ','cloth with fringe on the side','P','Phono. si3. In si3t “fringed cloth.”'],
  ['S33','𓋸','ṯbt','sandal','I','Ideo. in ṯbt “sandal,” ṯbw “sandal maker.”'],
  ['S34','𓋹','ꜥnḫ','lifeankh, possibly representing a sandal-strap','P','Phono. ʿnḫ. In ʿnḫ “live,” ʿnḫ “sandal strap.”'],
  ['S35','𓋺','šwt','sunshade','I','Ideo. in šwt “shadow, shade.”'],
  ['S36','𓋼','šwt','sunshade','I','Use as S35'],
  ['S37','𓋽','ḫw','fan','','R16'],
  ['S38','𓋾','ḥḳꜣ','crook','','T15'],
  ['S39','𓋿','ꜥwt','shepherd\'s crook','P','Phono ʿwt. In ʿwt “flock.”'],
  ['S40','𓌀','wꜣs','wꜣs scepter(uꜣs)','','F10'],
  ['S41','𓌁','ḏꜥm','sceptre','P','Phono. ḏʿm. In ḏʿm “fine gold.”'],
  ['S42','𓌂','sḫm','Sekhemscepter','PID','Phono. sḫm. In sḫm “have power,” sḫm “scepter.” Det. or Ideo. in ḫrp “manage, at head.”'],
  ['S43','𓌃','md','walking stick','P','Phono. md. In mdw “speak.”'],
  ['S44','𓌄','ꜣms','walking stick with flagellum','ID','Det. or Ideo. in 3ms “staff.”'],
  ['S45','𓌅','nḫꜣḫꜣw','flagellum','ID','Det. or Ideo. in nḫ3ḫ3w “flail.”'],
  ['S46','𓌆','k','covering for head and neck','',''],
  ['T1','𓌇','mn','mace with flat head','P','Phono. mn. In mnw “mace.”'],
  ['T2','𓌈','','mace with round head','D','Det. in sqr, sqri “smite.”'],
  ['T3','𓌉','ḥḏ','mace with round head','P','Phono. ḥḏ. In ḥḏ “mace,” ḥḏ “white, bright,” ḥḏi “damage.”'],
  ['T4','𓌋','ḥḏ','mace with strap','P','Use as T3'],
  ['T5','𓌌','ḥḏ','combination of mace with round head and cobra','P','Phono. ḥḏ.'],
  ['T6','𓌍','ḥḏḏ','combination of mace with round head and two cobras','P','Phono. ḥḏḏ.'],
  ['T7','𓌎','','axe','D','Det. in mibt, minb “axe,” mdḥ “hew.”'],
  ['T8','𓌐','tp','dagger','P','Phono. tp. In tpy “first, chief, upon.”'],
  ['T9','𓌒','pd|pḏ','bow','','F32'],
  ['T10','𓌔','pd|pḏ','composite bow','','Use as T9'],
  ['T11','𓌕','swn','arrow','P','Phono. swn. In swn “perish,” swnt “physician.”'],
  ['T12','𓌗','rwd|rwḏ','bowstring','PI','Phono. rwd/rwḏ. In rwd “hard, firm.” Ideo. in d3r “subdue.”'],
  ['T13','𓌘','rs','joined pieces of wood','P','Phono. rs. In rs “wakeful.”'],
  ['T14','𓌙','ꜥꜣm','throw stick vertically','ID','Det. of “foreign.” Ideo. in ʿ3m “Asiatics,” ṯḥnw “Libya.” Det. in qm3 “create,” qm3i “create.”'],
  ['T15','𓌚','ꜥꜣm','throw stick slanted','ID','Use as T14'],
  ['T16','𓌛','','scimitar','D','Det. in ḫpš “scimitar.”'],
  ['T17','𓌝','wrrt','chariot','ID','Det. or Ideo. in wrrt “chariot.”'],
  ['T18','𓌞','šms','crook with package attached','P','Phono. šms. In šms “follow, accompany.”'],
  ['T19','𓌟','ḳs','harpoon head','','R11'],
  ['T20','𓌠','ḳs','harpoon head','','Use as T19'],
  ['T21','𓌡','','harpoon','','U21'],
  ['T22','𓌢','sn','arrowhead','P','Phono. sn. In sn “brother,” sn “smell.”'],
  ['T23','𓌣','sn','arrowhead','P','Use as T22'],
  ['T24','𓌤','ꜥḥ|ỉḥ','fishingnet','P','Phono. ʿḥ/iḥ . In iḥ “net.”'],
  ['T25','𓌥','dbꜣ|ḏbꜣ','float','P','Phono. db3/ḏb3. In ḏb3 “adorn,” db3 “replace.”'],
  ['T26','𓌦','sḫt','birdtrap','ID','Det. or Ideo. in sḫt “trap, snare.”'],
  ['T27','𓌧','sḫt','trap','ID','Use as T26'],
  ['T28','𓌨','ẖr','butcher\'s block','P','Phono. ẖr. In ẖr “under,” ẖrt “portion.”'],
  ['T29','𓌩','nmt','butcher\'s block with knife','I','Ideo. in nmt “place of slaughter.”'],
  ['T30','𓌪','dmt','knife','ID','Ideo. for dmt “knife.” Det. in dm “be sharp.”'],
  ['T31','𓌫','sšm','knife-sharpener','P','Phono sšm. In sšm “guide, lead.”'],
  ['T32','𓌬','sšm','combination of knife-sharpener and legs','P','Phono sšm. In sšm “guide, lead.”'],
  ['T33','𓌮','sšm','knife-sharpener of butcher','I','Ideo. in sšm “butcher.”'],
  ['T34','𓌰','nm','butcher\'s knife','P','Phono. nm. In nm “knife,” ḫnms “friend.”'],
  ['T35','𓌱','','butcher\'s knife','','U32'],
  ['T36','𓌲','','shield','',''],
  ['U1','𓌳','mꜣ','sickle','P','Phono. m3. In m33 “see,” 3sḫ “reap.”'],
  ['U2','𓌴','mꜣ','sickle','P','Use as U1.'],
  ['U3','𓌵','mꜣ','','P','Phono. m3. In m33 “see.”'],
  ['U4','𓌶','mꜣꜥ','mꜣꜥ','P','Phono. m3ʿ. In m3ʿ “true.”'],
  ['U5','𓌷','mꜣꜥ','','P','Use as U4.'],
  ['U6','𓌸','mr','','P','Phono. mr. In mri “love.”'],
  ['U7','𓌻','mr','hoe','P','Use as U6.'],
  ['U8','𓌼','ḥn','','P','Phono. ḥn. In ḥn “hoe.”'],
  ['U9','𓌽','','','D','Det. in bdt “emmer,” ḫ3i “measure,” ḥq3t “hekat measure.”'],
  ['U10','𓌾','','grain measure (with plural, for grain particles)','I','Ideo. in it “barley.”'],
  ['U11','𓌿','ḥḳꜣt','','I','Ideo. in ḥq3t “hekat measure.”'],
  ['U12','𓍀','ḥḳꜣt','','I','Ideo. in ḥq3t “hekat measure.”'],
  ['U13','𓍁','šnꜥ','','P','Phono. šnʿ. In šnʿ “repel.” Phono hb. In hb “plow.”'],
  ['U14','𓍂','šnꜥ','','P','Phono. šnʿ. In šnʿ “repel.”'],
  ['U15','𓍃','tm','sled(sledge)','P','Phono. tm. In tm “be complete,” ḥtm “perish.”'],
  ['U16','𓍄','','sled with jackal head','','O31'],
  ['U17','𓍅','grg','Pick, opening earth','P','Phono. grg. In grg “establish, snare,” grg “falshood, lie.”'],
  ['U18','𓍆','','','','F18'],
  ['U19','𓍇','nw','','P','Phono. nw. In nw “this.”'],
  ['U20','𓍈','nw','','P','Use as U19'],
  ['U21','𓍉','stp|sṯp','adze-on-block','P','Phono. stp/sṯp. In stp “choose.”'],
  ['U22','𓍊','','clapper-(of-bell)tool/instrumentforked-staff, etc.','D','Det. in mnḫ “efficient,” mnḫ “carve.”'],
  ['U23','𓍋','mr','chisel','P','Phono. mr. In mr “ill,” smr “friend.” Phono. 3b. In 3bi “desire.”'],
  ['U24','𓍍','ḥmt','handdrill(hieroglyph)','I','Ideo. in ḥmt “craft, art.”'],
  ['U25','𓍎','ḥmt','version of U24 (hand drill)','I','Use as U24.'],
  ['U26','𓍏','wbꜣ','','','U25'],
  ['U27','𓍐','wbꜣ','','','Use as U26.'],
  ['U28','𓍑','ḏꜣ','fire-drill','P','Phono. ḏ3. In ʿnḫ.(w) (w)ḏ3 snb “may he live, be prosperous, be healthy.” (L.P.H.)'],
  ['U29','𓍒','ḏꜣ','','P','Use as U28.'],
  ['U30','𓍔','tꜣ','kiln','P','Phono. t3. In št3 “hot,” t3 “mysterious.'],
  ['U31','𓍕','rtḥty','','ID','Det. or Ideo. in rtḥty “baker,” rtḥ “restrain.”'],
  ['U32','𓍖','','','D','Det. in smn “press down,” smn “establish.”'],
  ['U33','𓍘','tỉ','\'pestle\'-(curved top)','P','Phono. ti.'],
  ['U34','𓍙','ḫsf','','P','Phono. ḫsf. In ḫsf “repel.”'],
  ['U35','𓍚','ḫsf','','P','Phono. ḫsf.'],
  ['U36','𓍛','ḥm','fuller\'s-club','','M13'],
  ['U37','𓍜','','','D','Det. in ẖʿq “shave.”'],
  ['U38','𓍝','mḫꜣt','scale','ID','Det. or Ideo. in mḫ3t “scale.”'],
  ['U39','𓍞','','','D','Det. in wsṯt “post,” wṯs, ṯsi “raise, lift.”'],
  ['U40','𓍟','','a support-(to lift)','D','Use as U39'],
  ['U41','𓍠','','plummet','D','Det. in tḫ “plumb bob.”'],
  ['U42','𓍡','','pitchfork','',''],
  ['V1','𓍢','šn','','P','Phono. šn. In šnt “dispute,” šni “litigate,” št “hundred.”'],
  ['V2','𓍬','sṯꜣt','','ID','Det. in st3 “drag.” Ideo. in sṯ3t “aurora.”'],
  ['V3','𓍮','r-sṯꜣw','','I','Ideo. in r-sṯ3w “necropolis.”'],
  ['V4','𓍯','wꜣ','lasso','P','Phono. w3. In w3ḥ “endure.”'],
  ['V5','𓍰','snṯ','','ID','Det. or Ideo. in snṯ “plot.”'],
  ['V6','𓍱','šs|šsr','rope-(shape)','P','Phono. šs, šsr.'],
  ['V7','𓍲','šn','rope-(shape)','P','Phono. šn.'],
  ['V8','𓍵','šn','','P','Use as V7'],
  ['V9','𓍶','','shenring','D','Det. in šnw “cartouche.”'],
  ['V10','𓍷','','cartouche','D','Det. in šnw “cartouche,” rn “name.'],
  ['V11','𓍸','','cartouche-(divided)','D','Det. in dni “restrain, dam,” pḫ3 “split.'],
  ['V12','𓍼','','','D','Det. in sšd “headband,” fḫ “loosen,” fḫnw “Phoenicians.'],
  ['V13','𓍿','ṯ','tethering rope','P','Phono. ṯ.'],
  ['V14','𓎀','','','','Use as last.'],
  ['V15','𓎁','ỉṯ','tethering rope w/ walking legs','P','Phono. iṯ. In iṯi “seize.”'],
  ['V16','𓎂','sꜣ','cattlehobble(bil.)','P','Phono. s3. In s3 “protection.”'],
  ['V17','𓎃','sꜣ','lifesaver','','V39'],
  ['V18','𓎄','sꜣ','','','Use as V17'],
  ['V19','𓎅','','','','Aa3'],
  ['V20','𓎆','mḏ','"cattle hobble"','P','Phono. mḏ. In mḏwt “stables,” mḏ “10.”'],
  ['V21','𓎓','mḏ','Fetter + Cobra','P','Phono. mḏ.'],
  ['V22','𓎔','mḥ','whip','P','Phono. mḥ. In mḥ “fill.”'],
  ['V23','𓎕','','','','O34'],
  ['V24','𓎗','wḏ','"command staff" (can also be circular)','P','Phono. wḏ. In wḏ “command, decree.”'],
  ['V25','𓎘','','variant of V24 (can also be circular)','','U34'],
  ['V26','𓎙','ꜥd|ꜥḏ','','P','Phono. ʿd/ʿḏ. In ʿd “good condition.”'],
  ['V27','𓎚','ꜥd|ꜥḏ','','P','Use as V26.'],
  ['V28','𓎛','ḥ','a twisted wick','P','Phono. ḥ.'],
  ['V29','𓎝','wꜣḥ|sk','(fiber)swab(straw broom)','P','Phono. w3ḥ, sk.'],
  ['V30','𓎟','nb','basket(hieroglyph)','','W3'],
  ['V31','𓎡','k','basket-with-handle(hieroglyph)','P','Phono k.'],
  ['V32','𓎣','msn','','','R4'],
  ['V33','𓎤','','','','V8'],
  ['V34','𓎦','','','','Use as V33.'],
  ['V35','𓎧','','','','F51'],
  ['V36','𓎨','ḥn','doubled container(or-added-glyphs)many spellings','P','Phono. ḥn. In ḥnt “occupation.”'],
  ['V37','𓎩','ỉdr','','ID','Det. or Ideo. in idr “bandage, bind,” idr “herd.”'],
  ['V38','𓎫','','','D','Det. in wt “bandage.”'],
  ['V39','𓎬','tỉt','?stylized ankh(for Isis)(?)','I','Ideo. in tit “Isis knot.”'],
  ['V40','𓎭','','','',''],
  ['W1','𓎯','','Oil jar','D','Det. in mḏt “ointment,” mrḥt “oil.”'],
  ['W2','𓎰','bꜣs','Oil-jar without ties','P','Phono. b3s. In b3stt “Bastet,” b3s “oil jar.”'],
  ['W3','𓎱','ḥb','alabasterbasin','ID','Det. or Ideo. in ḥb “feast,” ḥb “mourn.”'],
  ['W4','𓎳','ḥb','festival chamber, (the tail is also vertical \'Great\': ꜥꜣ)','ID','Det. or Ideo. in ḥb “feast,” tp-rnpt “feat of the first of the year.”'],
  ['W5','𓎴','','','I','Ideo in ẖry-ḥbt “lector priest.”'],
  ['W6','𓎵','','metal vessel','D','Det. in wḥt “cauldron.”'],
  ['W7','𓎶','','granite bowl','D','Det. in 3bt “family,” m3ṯ “proclaim.”'],
  ['W8','𓎷','','deformed granite bowl','D','Use as W7.'],
  ['W9','𓎸','ẖnm','stone jug','P','Phono. ẖnm.'],
  ['W10','𓎺','ḥnw','cup','PID','Phono. ḥnw. In ḥnwt “mistress.” Det. or Ideo. in wsḫ “wide.”'],
  ['W11','𓎼','g','ring stand/earthenware pot','PID','Phono. g. Det. or Ideo. in nst “throne.”'],
  ['W12','𓎽','g','flat ring stand','PID','Use as W11.'],
  ['W13','𓎾','dšrt','earthenware pot','','N42'],
  ['W14','𓎿','ḥs','water jar','P','Phono. ḥs. In ḥst “water jar.”'],
  ['W15','𓏁','ḳbb','water jar with water pouring out','ID','Det. or Ideo. in qbb, qbḥ “cool, water.”'],
  ['W16','𓏂','ḳbb','water jar with water pouring out and ring stand','ID','Use as W15.'],
  ['W17','𓏃','ḫnt','three water jars in rack','P','Phono. ḫnt. In ḫntw “jar rack.”'],
  ['W18','𓏅','ḫnt','four water jars in rack','P','Use as W17'],
  ['W19','𓏇','mỉ','Milk jug with handle','P','Phono. mi. In mi “likeness.”'],
  ['W20','𓏈','','Milk jug with cover','D','Det. in irtt “milk.”'],
  ['W21','𓏉','','Wine jars','D','Det. in irp “wine.”'],
  ['W22','𓏊','ḥnḳt','Beer jug','ID','Ideo. in ḥnqt “beer.” Det. in qrḥt “vessel.”'],
  ['W23','𓏋','ḥnḳt','Beer jug with handles','ID','Use as W22.'],
  ['W24','𓏌','nw|ỉn|ỉnk','Pot','P','Phono. nw, in, ink.'],
  ['W25','𓏎','ỉn','Pot with legs','P','Phono. in. In ini “fetch, bring.”'],
  ['X1','𓏏','t','loaf of bread','PI','Phono. t. Ideo. in t “bread.”'],
  ['X2','𓏐','dḥwty','','ID','Det. of bread. In t “bread.” Ideo. in dḥwty “Thoth.”'],
  ['X3','𓏑','dḥwty','','ID','Use as X2'],
  ['X4','𓏒','','roll of bread','','N16'],
  ['X5','𓏕','','','D','Det. in ʿqw “provisions.”'],
  ['X6','𓏖','','loaf with decoration','D','Det. in p3t “loaf.”'],
  ['X7','𓏘','','half-loaf of bread','D','Det. in snw “offerings.” When doubled, wnm “eat.”'],
  ['X8','𓏙','dỉ','cone-shapedbread','P','Phono. di. In rdi “give.”'],
  ['Y1','𓏛','mḏꜣt','papyrusroll','PID','Phono. mḏ3t. Ideo. in mḏ3t “paypyrus roll, book.” Det. in rḫ “know.”'],
  ['Y2','𓏝','mḏꜣt','Papyrus roll-open','PID','Use as Y1'],
  ['Y3','𓏞','sš','Scribe\'s equipment','ID','Det. or Ideo. in sš “write,” nʿʿ “smooth.”'],
  ['Y4','𓏟','sš','Scribe\'s equipment','ID','Use as Y3'],
  ['Y5','𓏠','mn','Senet board','P','Phono. mn. In imn “Amun” mn “remain.”'],
  ['Y6','𓏡','ỉbꜣ','game piece','ID','Det. or Ideo. in ib3 “game piece,” “dance.”'],
  ['Y7','𓏢','','harp','D','Det. in bnt “harp.”'],
  ['Y8','𓏣','','Sistrum','D','Det. in sššt “sistrum.”'],
  ['Z1','𓏤','','Single stroke','ID','Follows Ideograms. Det. wʿ “one.” Ideo. numerals 1-9.'],
  ['Z2','𓏥','','Plural stroke (horizontal)','D','Det. of plurality.'],
  ['Z3','𓏪','','plural strokes (vertical)','D','Same as Z2.'],
  ['Z4','𓏭','y','Dual stroke','D','Det. Duality'],
  ['Z5','𓏯','','Diagonal stroke (from hieratic)','','Replacement for complex or dangerous signs, human figures.'],
  ['Z6','𓏱','','Substitute for various human figures','','T7'],
  ['Z7','𓏲','w','coil(hieratic equivalent)','P','Phono. w.'],
  ['Z8','𓏳','','Oval','D','Det. of round.'],
  ['Z9','𓏴','swꜣ','Crossed diagonal sticks','P','Phono. sw3. In sw3 “pass.”'],
  ['Z10','𓏵','swꜣ','Crossed diagonal sticks','P','Use as Z9.'],
  ['Z11','𓏶','ỉm','two planks crossed and joined','','M44'],
  ['Z12','𓏷','','','',''],
  ['Z13','𓏸','','','',''],
  ['Z14','𓏹','','','',''],
  ['Z15','𓏺','','','',''],
  ['Z16','𓐄','','','',''],
  ['Aa1','𓐍','ḫ','Placenta or sieve','P','Phono. ḫ.'],
  ['Aa2','𓐎','','Pustule','D','Det. in bodily growths or conditions.'],
  ['Aa3','𓐏','','Pustule with liquid issuing from it','D','Use as Aa2.'],
  ['Aa4','𓐐','bꜣ','','P','Var. of W10a.'],
  ['Aa5','𓐑','ḥp','Part of steering gear of a ship','P','Phono. ḥp.'],
  ['Aa6','𓐒','','','D','Det. in tm3 “mat.”'],
  ['Aa7','𓐓','','A Smiting-Blade','D','Det. in sqr “smite.”'],
  ['Aa8','𓐖','ḳn','Irrigation tunnels','','V27'],
  ['Aa9','𓐗','','','D','Det. in ḫwd “rich.”'],
  ['Aa10','𓐘','','','D','Det. in drf “writing.”'],
  ['Aa11','𓐙','mꜣꜥ','','','Aa14'],
  ['Aa12','𓐚','mꜣꜥ','','','Use as Aa11.'],
  ['Aa13','𓐛','ỉm|m','','P','Phono. im, m.'],
  ['Aa14','𓐜','ỉm|m','','P','Phono. im, m.'],
  ['Aa15','𓐝','ỉm|m','','P','Phono. im, m.'],
  ['Aa16','𓐞','gs','','',''],
  ['Aa17','𓐟','sꜣ','','P','Phono. s3. In s3 “back.”'],
  ['Aa18','𓐠','sꜣ','','P','Use as Aa17'],
  ['Aa19','𓐡','','','D','Det. in ḥr “prepare,” ḥryt “dread.”'],
  ['Aa20','𓐢','ꜥpr','','P','Phono. ʿpr. In ʿpr “equip.”'],
  ['Aa21','𓐣','wḏꜥ','','P','Phono. wḏʿ. In wḏʿ “judge.”'],
  ['Aa22','𓐤','wḏꜥ','','P','Use as Aa21.'],
  ['Aa23','𓐥','','','D','Det. in mḏd “puncture, press, adhere.”'],
  ['Aa24','𓐦','','','D','Use as Aa23.'],
  ['Aa25','𓐧','smꜣ','','I','Ideo. in sm3 “stolist” (priestly title).'],
  ['Aa26','𓐨','','','D','Det. in sbi “rebel.”'],
  ['Aa27','𓐩','nḏ','','P','Phono. nḏ. In nḏ “ask, inquire.”'],
  ['Aa28','𓐪','ḳd','','P','Phono. qd. In qd “build.”'],
  ['Aa29','𓐫','ḳd','','P','Use as Aa28.'],
  ['Aa30','𓐬','','','','F31'],
  ['Aa31','𓐭','','','','Use as Aa30.'],
  ['Aa32','𓐮','','','',''],
];
