window.GARDINER_DATA_EN=[
  ['A1','𓀀','','seated man','D','Determinative of man, names; Pronoun1st sing. i, wi, ink, kwi. “I,” “me,” “my.”'],
  ['A2','𓀁','','man with hand to mouth','D','Determinative of eat, drink, speak, think.'],
  ['A3','𓀂','','man sitting on heel','D','Determinative of sit.'],
  ['A4','𓀃','','man with hands raised','D','Determinative adoration, hide'],
  ['A5','𓀄','','man hiding behind wall','D','Determinative hide'],
  ['A6','𓀆','','seated man under vase from which water flows','D','Determinative purity, cleanliness'],
  ['A7','𓀉','','fatigued man','D','Determinative weary, weak'],
  ['A8','𓀊','','man performing hnw','D','Determinative in hnw “jubilation”'],
  ['A9','𓀋','','man with basket on head','D','Determinative in ꜣṯp “load,” fꜣi “carry,” kꜣt “work.”'],
  ['A10','𓀌','','man with oar','D','Determinative in sḳdw “sail.”'],
  ['A11','𓀍','','man with scepter and crook','D','Determinative ḫnms “friend.”'],
  ['A12','𓀎','','soldier','D','Determinative mšꜥ “army,” soldier.'],
  ['A13','𓀏','','prisoner','D','Determinative ḫfty “enemy.”'],
  ['A14','𓀐','','wounded man','D','Determinative of mwt “die,” enemy.'],
  ['A15','𓀒','','man falling','D','Determinative ḫr “fall,” sḫrt “overthrow.”'],
  ['A16','𓀓','','man bowing','D','Determinative ksi “bow.”'],
  ['A17','𓀔','ẖrd','child','ID','Determinative šri “young.” Logogram ẖrd “child.”'],
  ['A18','𓀖','','child with Red Crown','D','Determinative child-king'],
  ['A19','𓀗','','old man with staff','D','Determinative iꜣw “old,” smsw “eldest,” wr “great one, chief.”'],
  ['A20','𓀘','','old man with forked staff','D','Variant of A19.'],
  ['A21','𓀙','sr','dignitary','ID','Determinative and Logogram sr “official, noble.”'],
  ['A22','𓀚','','statue on base','D','Determinative statue.'],
  ['A23','𓀛','','king','D','Determinative ity, “sovereign.”'],
  ['A24','𓀜','nḫt','man striking','ID','Determinative ḥwi, “strike,” nḥm “take away.” Logogram nḫt strong.'],
  ['A25','𓀝','','man striking','D','Determinative hwi “strike.”'],
  ['A26','𓀞','','man beckoning','ID','Determinative nis “call.” Logogram vocative i, “Oh!”'],
  ['A27','𓀟','ỉn','man running','P','Phonogram in “by,” agent particle.'],
  ['A28','𓀠','','excited man','D','Determinative ḳꜣ “high,” ḥꜥi “rejoice.”'],
  ['A29','𓀡','','man upside down','D','Determinative upside down.'],
  ['A30','𓀢','','man worshipping','D','Determinative iꜣw “praise,” dwꜣ “adoration.”'],
  ['A31','𓀣','','man shunning','D','Determinative turn away.'],
  ['A32','𓀤','','man dancing','D','Determinative dance.'],
  ['A33','𓀦','','man with stick and bundle','D','Determinative wander, herdsman.'],
  ['A34','𓀧','','man pounding','D','Determinative ḫwsi “pound, build.”'],
  ['A35','𓀨','ḳd','man building a wall','ID','Determinative and Logogram ḳd “build.”'],
  ['A36','𓀩','ꜥfty','man kneading into vessel','ID','Determinative and Logogram ꜥfty “brewer.”'],
  ['A37','𓀪','ꜥfty','man in vat','ID','Use as A36.'],
  ['A38','𓀫','ḳỉs|ḳsỉ','man with two animals','I','Logogram ḳis/ḳsi “”Cusae” (town).'],
  ['A39','𓀬','ḳỉs|ḳsỉ','man on two giraffes','I','Use as A38.'],
  ['A40','𓀭','','seated god','D','Determinative god. Replaces A1 as 1st sing pronoun when god speaks. i, wi, ink, kwi.'],
  ['A41','𓀯','','seated king','D','Determinative nsw “king,” ḥm “majesty,” nb “lord.”'],
  ['A42','𓀰','','king with uraeus and flagellum','D','Use as A41.'],
  ['A43','𓀲','','king with White Crown','D','Determinative king of Upper Egypt.'],
  ['A44','𓀴','','king wearing white crown with flagellum','D','Use as A43.'],
  ['A45','𓀵','bỉty','king with Red Crown','ID','Determinative and Logogram bity “king of Lower Egypt.”'],
  ['A46','𓀷','bỉty','king wearing red crown with flagellum','ID','Same as A45'],
  ['A47','𓀸','sꜣw','shepherd seated','ID','Determinative and Logogram sꜣw “guard,” mniw “herdsman.”'],
  ['A48','𓀹','','seated man with knife','D','Determinative iry “relating to.”'],
  ['A49','𓀺','','foreigner with stick','D','Determinative foreigner, ꜥꜣmw “Asiatics.”'],
  ['A50','𓀻','','noble on chair','D','Determinative revered person, deceased. Variant A1 for 1st sing. pronoun.'],
  ['A51','𓀼','špsỉ','noble on chair, with flail','ID','Determinative and Logogram špsi “noble”'],
  ['A52','𓀽','','seated noble with flail','D','Determinative revered person, deceased.'],
  ['A53','𓀾','','mummy standing','D','Determinative mummy, statue, likeness, form.'],
  ['A54','𓀿','','mummy recumbent','D','Determinative dead.'],
  ['A55','𓁀','','mummy on bed','D','Determinative sḏr “lie down,” dead.'],
  ['A56','𓁁','','seated man holding stick','',''],
  ['A57','𓁂','ḥtp-dỉ-nsw','man holding loaf on mat','',''],
  ['A58','𓁃','','man applying hoe to ground','',''],
  ['A59','𓁄','','man threatening','D','Determinative drive off.'],
  ['A60','𓁅','stỉ','man sowing seeds','',''],
  ['A61','𓁆','','man looking over his shoulder','',''],
  ['A62','𓁇','','Asiatic','',''],
  ['A63','𓁈','','king on throne holding staff','',''],
  ['A64','𓁉','','man sitting on heels holding forward cup','',''],
  ['A65','𓁊','','man wearing tunic with fringes and holding mace','',''],
  ['A66','𓁋','ỉḥy|nṯr-ꜥꜣ','man holding sistrum','',''],
  ['A67','𓁌','','dwarf','',''],
  ['A68','𓁍','msdmt','man holding up knife','',''],
  ['A69','𓁎','','seated man with raised right arm and left arm hanging down','',''],
  ['A70','𓁏','ḥḥ','seated man with raised arms','',''],
  ['B1','𓁐','','seated woman','D','Determinative of woman, names of women. Variant of A1 for the first person singular when the speaker is a woman.'],
  ['B2','𓁑','','pregnant woman','D','Determinative pregnant'],
  ['B3','𓁒','msỉ','woman giving birth','ID','Determinative and Logogram msi “give birth, bear.”'],
  ['B4','𓁓','msỉ','combination of woman giving birth and three skins tied together','ID','Use as B3.'],
  ['B5','𓁔','','woman nursing','D','Determinative mnꜥt “nurse.”'],
  ['B6','𓁖','','nurse with child','D','Determinative rnn “nurse.”'],
  ['B7','𓁗','','seated queen','D','Determinative queens’ names.'],
  ['B8','𓁘','','woman holding lotus flower','',''],
  ['B9','𓁙','','woman holding sistrum','',''],
  ['C1','𓁚','Rꜥ','god with sun-disk','ID','Determinative and Logogram Rꜥ “Re, sun-god”'],
  ['C2','𓁛','Rꜥ','god with falcon head and sun-disk holding ankh','ID','Variant C1. Determinative and Logogram Rꜥ “Re, sun-god”'],
  ['C3','𓁟','ḏḥwty','ibis-headed','ID','Determinative or Logogram ḏḥwty “Thoth”'],
  ['C4','𓁠','ẖnmw','ram-headed','ID','Determinative or Logogram ẖnmw “Khnum”'],
  ['C5','𓁡','ẖnmw','god with ram head holding ankh','ID','Use as C4.'],
  ['C6','𓁢','ỉnpw','jackal-headed','ID','Determinative and Logogram inpw “Anubis,” wp-wꜣwt “Wepwawet.”'],
  ['C7','𓁣','Stḫ','Seth-animal-headed','ID','Determinative and Logogram Stḫ “Seth.”'],
  ['C8','𓁤','Mnw','Min figure','ID','Determinative and Logogram Mnw “Min.”'],
  ['C9','𓁥','','goddess with horned disk','ID','Determinative and Logogram'],
  ['C10','𓁦','Mꜣꜥt','goddess with feather','ID','Determinative and Logogram Mꜣꜥt “Maat”'],
  ['C11','𓁨','ḥḥ','ḥḥ-figure','I','Logogram ḥḥ “million,” god Heh.'],
  ['C12','𓁩','Imn','Amun figure','ID','Determinative and Logogram Imn “Amun.”'],
  ['C13','𓁪','ỉmn','C12 reversed','',''],
  ['C14','𓁫','ỉmn-ḥr-ḫpš.f','god with two plumes and scimitar','',''],
  ['C15','𓁬','ỉmn-ḥr-ḫpš.f','C14 reversed','',''],
  ['C16','𓁭','ỉtmw','god wearing red crown with ankh','',''],
  ['C17','𓁮','','Montu figure','ID','Determinative and Ideo Mntw “Montu.”'],
  ['C18','𓁯','tꜣ-ṯnn','Tatjenen figure','ID','Determinative and Logogram tꜣ-ṯnnii “Tatjenen.”'],
  ['C19','𓁰','Ptḥ','Ptah figure','ID','Determinative and Logogram Ptḥ “Ptah.”'],
  ['C20','𓁱','Ptḥ','mummy-shaped god in shrine','ID','Use as C19'],
  ['C21','𓁲','bs','Bes','',''],
  ['C22','𓁳','ḫnsw','god with falcon head and moon','',''],
  ['C23','𓁴','sḫmt|mnḥyt|mḥyt|bꜣstt','goddess with feline head and sun with uraeus','',''],
  ['C24','𓁵','ỉtmw','god wearing red crown with scepter','',''],
  ['D1','𓁶','tp','head','PID','Phonogram tp. Determinative or Logogram for tp “head,” tpy “first, chief.” Determinative ḏꜣḏꜣ“head.”'],
  ['D2','𓁷','ḥr','face','PI','Phonogram ḥr. Logogram for ḥr “face.”'],
  ['D3','𓁸','','hair','D','Determinative for šny “hair,” iwn “complexion, nature.” Abbr. for gm wš “found missing.”'],
  ['D4','𓁹','ỉrt','eye','PI','Phonogram iri “to do, make.” Logogram for irt “eye.”'],
  ['D5','𓁺','','eye with paint','D','Determinative for actions or conditions of the eye. ex. dgi “look,” šp “blind.”'],
  ['D6','𓁻','','eye with painted upper lid','D','Use as D5.'],
  ['D7','𓁼','','eye with paint','D','Determinative for adorn and in ꜥnw ” “Anu” (location).'],
  ['D8','𓁽','','eye enclosed','D','Determinative forꜥnw “Turah,” ꜥn “beautiful.”'],
  ['D9','𓁿','rmỉ','eye weeping','ID','Determinative or Logogram for rmi “weep.”'],
  ['D10','𓂀','wḏꜣt','eye with falcon markings','ID','Determinative or Logogram for wḏꜣt “wedjat eye.”'],
  ['D11','𓂁','','left part of the eye of Horus','','1/2 ḥeqat measure of grain.'],
  ['D12','𓂂','','pupil','D','Determinative for ḏfd “pupil of eye.”'],
  ['D13','𓂃','','eyebrow','','1/8 ḥeqat measure of grain.'],
  ['D14','𓂄','','right part of eye of Horus','','1/16 ḥeqat measure of grain.'],
  ['D15','𓂅','','diagonal marking of eye of Horus','','1/32 ḥeqat measure of grain.'],
  ['D16','𓂆','','vertical marking of eye of Horus','','1/64 ḥeqat measure of grain.'],
  ['D17','𓂇','tỉt','diagonal and vertical markings of eye of Horus','ID','Determinative or Logogram for tit “figure, image.”'],
  ['D18','𓂈','msḏr','ear','ID','Determinative or Logogram for msḏr “ear.”'],
  ['D19','𓂉','fnd','face in profile','ID','Determinative or Logogram for fnd “nose.” Determinative sn “smell,” rš “rejoice.”'],
  ['D20','𓂊','fnd','nose, eye and cheek (cursive)','ID','Use as D19'],
  ['D21','𓂋','r','mouth','PI','Phonogram r. Logogram for r (“mouth”).'],
  ['D22','𓂌','rwy','mouth plus 2 strokes','I','Logogram for rwy “2/3.”'],
  ['D23','𓂍','ḫmt','mouth plus 3 strokes','I','Logogram for ḫmt rw “3/4.”'],
  ['D24','𓂎','spt','lip with teeth','ID','Determinative or Logogram for spt “lip.” Mistakenly used a F42.'],
  ['D25','𓂏','spty','two lips and teeth','ID','Determinative or Logogram for spty “lips.”'],
  ['D26','𓂐','','lips and water','D','Determinative for spit, spew. ex. psg “spit,” ḳꜥ “spew out.”'],
  ['D27','𓂑','','breast','D','Determinative for breast, suckle. ex. mnḏ “breast”'],
  ['D28','𓂓','kꜣ','two arms','PI','Phonogram kꜣ. Logogram for kꜣ “soul.”'],
  ['D29','𓂔','kꜣ','combination of hieroglyphs D28 and R12','PI','Use as D28.'],
  ['D30','𓂕','','two arms and tail','D','Determinative for nḥb-kꜣw “Uniter of Attributes, Assigner of Kas,” name of mythical serpent deity.'],
  ['D31','𓂖','ḥm-kꜣ','arms embracing club','I','Logogram for ḥm-kꜣ “ka servent.”'],
  ['D32','𓂘','','two arms embracing','D','Determinative for embrace, open. ex. inḳ “envelop,” ḥpt “embrace.”'],
  ['D33','𓂙','ẖn','arms and oar','PI','Phonogram ẖn. Logogram for ẖni “row.”'],
  ['D34','𓂚','ꜥḥꜣ','armswith shieldand battle axe','I','Logogram for ꜥḥꜣ “fight”'],
  ['D35','𓂜','n','gesture of negation','PID','Phonogram n. Logogram for n and nn, “not.” Determinative negation.'],
  ['D36','𓂝','ꜥ','forearm','PI','Phonogram ꜥ. Logogram ꜥ “arm, hand.”'],
  ['D37','𓂞','dỉ','forearm with X8','P','Phonogram di in rdi “give.”'],
  ['D38','𓂟','mỉ|m','forearm with bread','PD','Phonogram mi or m. Determinative for imi “give.”'],
  ['D39','𓂠','','forearm with pot','D','Determinative for offer, present. ex. ḥnk “present,” drp “offer.”'],
  ['D40','𓂡','hꜣỉ','forearm with stick','ID','Determinative for force, effort. ex. nḫt “strong.” Logogram hꜣi “evaluate.”'],
  ['D41','𓂢','nỉ','forearm with palm down','PD','Phonogram ni. Determinative for arm. ex. rmn “arm, shoulder.”'],
  ['D42','𓂣','mḥ','forearm with palm down','ID','Determinative or Logogram for mḥ “cubit”'],
  ['D43','𓂤','ḫw','forearm with flail','PI','Phonogram ḫw. Logogram for ḫwi “protect.'],
  ['D44','𓂥','ḫrp','forearm with scepter','ID','Determinative and Logogram for ḫrp “control, be at head of, administer.”'],
  ['D45','𓂦','ḏsr','forearm with brush','ID','Determinative and Logogram for ḏsr “clear road, sacred, holy.”'],
  ['D46','𓂧','d','hand','PI','Phonogram d. Logogram for ḏrt “hand.”'],
  ['D47','𓂩','','hand','PD','Determinative for ḏrt “hand” when spelled with Phonogram'],
  ['D48','𓂪','šsp','hand without thumb','I','Logogram šsp “palm, hand-breadth” (measure)'],
  ['D49','𓂬','','fist','D','Determinative for grasp. ex. ꜣmm “grasp,” ḫfꜥ “seize.”'],
  ['D50','𓂭','ḏbꜥ','finger','ID','Logogram for ḏbꜥ “finger,” ḏbꜥ “10,000.” Determinative for accurate, when doubled.'],
  ['D51','𓂷','','finger','D','Determinative for actions related to finger, fruit, flower. ex. ꜥnt “nail,” ḫꜣi “measure,” dḳr “fruit.”'],
  ['D52','𓂸','mt','penis','PID','Phonogram mt. Determinative for male. ex. ꜥꜣ “ass,” ṯꜣy “male.” Logogram kꜣ “bull.”'],
  ['D53','𓂺','','penis with fluid','D','Determinative for male, penis. ex. m bꜣḥ “in the presence of” ḏr bꜣḥ “since,” r bꜣḥ “before.”'],
  ['D54','𓂻','ỉw','walking legs','PD','Phonogram iw in iwi “come.” Determinative for motion.'],
  ['D55','𓂽','','legs walking backwards','D','Determinative for backwards. ex. ꜥnn “turn back,” ḫtḫt “be reversed.”'],
  ['D56','𓂾','pd','leg','PD','Phonogram pd. Determinative for leg, foot. ex. rd “leg,” pd “knee.”'],
  ['D57','𓂿','','leg with knife','D','Determinative for mutilate. ex. iꜣṯ “be mutilated.”'],
  ['D58','𓃀','b','foot','PI','Phonogram b. Logogram for bw “place.”'],
  ['D59','𓃁','ꜥb','foot and forearm','P','Phonogram ꜥb'],
  ['D60','𓃂','wꜥb','foot under vase from which water flows','I','Logogram for wꜥb “pure, clean.”'],
  ['D61','𓃃','sꜣḥ','stylized toes','I','Logogram for sꜣḥ “toe”'],
  ['D62','𓃄','sꜣḥ','three toes oriented rightward','I','Use as D61.'],
  ['D63','𓃅','sꜣḥ','two toes oriented leftward','I','Use as D61.'],
  ['D64','𓃆','','hand with palm down','',''],
  ['D65','𓃇','ḥnsḳty','Sidelock of hair','',''],
  ['D66','𓃈','spẖr','arm with reed pen','',''],
  ['D67','𓃉','','one dot','',''],
  ['E1','𓃒','kꜣ','bull','ID','Determinative of cattle. ex. ng “bull,” mnmnt “cattle.” Logogram in kꜣ “bull.”'],
  ['E2','𓃓','kꜣ','bull charging','ID','Determinative in smꜣ “fighting bull.” Logogram in kꜣ nḫt “victorious bull,” (epithet of Pharaoh.)'],
  ['E3','𓃔','','calf','D','Determinative in bḥs “calf”'],
  ['E4','𓃕','','sacred cow','D','Determinative in ḥsꜣt “sacred cow.”'],
  ['E5','𓃖','','cow and calf','D','Determinative in ꜣms “show solicitude.”'],
  ['E6','𓃗','','horse','ID','Logogram or Determinative in ssmt “horse.” Determinative in ibr “stallion.”'],
  ['E7','𓃘','','donkey','D','Determinative in ꜥꜣ “donkey.”'],
  ['E8','𓃙','ỉb','kid','PD','Phonogram ib, “kid.” Determinative in ꜥwt “flocks.”'],
  ['E9','𓃛','ỉw','newborn bubalis','P','Phonogram iw. In iwr “conceive.”'],
  ['E10','𓃝','','bearded ram','D','Determinative in bꜣ “ram,” ẖnmw “Khnum,”ꜥwt ḥḏt “white flocks, sheep”'],
  ['E11','𓃞','','ram','D','Use as E10'],
  ['E12','𓃟','','pig','D','Determinative in rri “pig.”'],
  ['E13','𓃠','','cat','D','Determinative in miw “cat.”'],
  ['E14','𓃡','','dog (saluki)','D','Determinative in iw “dog,” ṯsm “hound.”'],
  ['E15','𓃢','Ỉnpw','jackal recumbent','ID','Determinative or Logogram in Ỉnpw, “Anubis.”'],
  ['E16','𓃣','Inpw','lying canine on shrine','ID','Use as E15.'],
  ['E17','𓃥','sꜣb','jackal','ID','Determinative or Logogram in sꜣb “jackal” and “dignitary.”'],
  ['E18','𓃧','Wp-wꜣwt','jackal on standard','ID','Determinative or Logogram in Wp-wꜣwt “Opener of ways, Wepwawet.”'],
  ['E19','𓃨','Wp-wꜣwt','wolf on standard with mace','ID','Use as E18'],
  ['E20','𓃩','stẖ','Seth animal','ID','Determinative or Logogram in stẖ, stš “Seth.” Determinative in ẖnnw “turmoil,” shꜣ “confusion.”'],
  ['E21','𓃫','','lying Set-animal','D','Determinative in nšni “storm, rage.”'],
  ['E22','𓃬','mꜣỉ','lion','ID','Determinative or Logogram in mꜣi “lion”'],
  ['E23','𓃭','rw','lion recumbent','PID','Phonogram rw. Determinative or Logogram in rw “lion.”'],
  ['E24','𓃮','ꜣby','panther or leopard','ID','Determinative or Logogram in ꜣby “panther, leopard.”'],
  ['E25','𓃯','','hippopotamus','D','Determinative in db, dib “hippopotamus.”'],
  ['E26','𓃰','ꜣbw','elephant','ID','Determinative ꜣbw “elephant.” Logogram in ꜣbw “Elephantine.”'],
  ['E27','𓃱','','giraffe','ID','Determinative sr “foretell.” Determinative or Ideo in mmi “giraffe.”'],
  ['E28','𓃲','','oryx','D','Determinative in mꜣḥḏ “oryx.”'],
  ['E29','𓃴','','gazelle','D','Determinative in gḥs “gazelle.”'],
  ['E30','𓃵','','ibex','D','Determinative in nꜣw, nrꜣw, niꜣ “ibex.”'],
  ['E31','𓃶','','goat with collar','D','Determinative in sꜥḥ “rank, privilege.”'],
  ['E32','𓃷','','baboon','D','Determinative in iꜥn “baboon,” ky “monkey,” qnd “furious.”'],
  ['E33','𓃸','','monkey','D','Determinative gf, gif “monkey.”'],
  ['E34','𓃹','wn','hare','P','Phonogram wn. wnn “be.”'],
  ['E36','𓃻','ḏḥwty|nswt|nfr|sẖꜣ|sꜣ|ḏd','baboon','',''],
  ['E37','𓃼','šbt','baboon with receptacle and basket','',''],
  ['E38','𓃽','kꜣ','long-horned bull','',''],
  ['F1','𓃾','kꜣ','head of ox','I','Logogram in offering formulas for kꜣ “cattle.”'],
  ['F2','𓄀','','head of charging bull','D','Determinative in ḏnd “rage.”'],
  ['F3','𓄁','ꜣt','head of hippopotamus','PID','Phonogram ꜣt. Determinative or Logogram in “moment, attack.”'],
  ['F4','𓄂','ḥꜣt','forepart of lion','I','Logogram in ḥꜣt “front,” ḥꜣty “heart.”'],
  ['F5','𓄃','šsꜣ','head of bubalis','PID','Phonogram šsꜣ. Determinative and Logogram in šsꜣ “skilled” and “prayer.”'],
  ['F6','𓄄','šsꜣ','forepart of hartebeest','PID','Use as F5'],
  ['F7','𓄅','šfyt','head of ram','ID','Determinative in šft “ram’s head.” Determinative or Logogram in šfyt “worth, dignity.”'],
  ['F8','𓄆','šfyt','forepart of ram','ID','Use as F7'],
  ['F9','𓄇','pḥty','head of leopard','ID','Determinative or Logogram in pḥty “strength.”'],
  ['F10','𓄈','','head and neck of animal','D','Determinative in ḫḫ “throat,” ꜥm “swallow.”'],
  ['F11','𓄉','','head and neck of animal','D','Use as F10'],
  ['F12','𓄊','wsr','head and neck of jackal','PI','Phonogram wsr. Ideo in wsrt “neck.” In wsr “powerful”'],
  ['F13','𓄋','wp','horns','PI','Phonogram wp. Logogram in wpt “brow, beginning.”'],
  ['F14','𓄍','wpt-rnpt','horns with palm branch','I','Logogram wpt-rnpt “Opening of the Year.”'],
  ['F15','𓄎','wpt-rnpt','horns with palm branch and sun','I','Use as F14'],
  ['F16','𓄏','ꜥb','horn','PID','Phonogram ꜥb. Determinative or Logogram in db “horn,” ꜥb “horn.” In m-ꜥb “together with.”'],
  ['F17','𓄐','ꜥbw','horn and vase from which water flows','ID','Determinative or Logogram in ꜥbw “purification.”'],
  ['F18','𓄑','bḥ|ḥw','tusk','PID','Phonogram bḥ, ḥw. Determinative and Logogram in ibḥ “tooth.” Determinative in sbḥ “cry.”'],
  ['F19','𓄒','','jawbone of ox','D','Determinative in ꜥrt “jaw.”'],
  ['F20','𓄓','ns','tongue','PI','Phonogram ns. In ns “tongue.” Logogram in imy-r “overseer.”'],
  ['F21','𓄔','sḏm|ỉdn','ear of bovine','PID','Phonogram sḏm, idn. Determinative or Logogram in msḏr “ear. Logogram sḏm, “hear.”'],
  ['F22','𓄖','pḥwy','hindquarters of feline','PI','Phonogram pḥ in “reach,” pḥty “strength.” Logogram for pḥwy “end.”'],
  ['F23','𓄗','ḫpš','foreleg of ox','ID','Determinative or Logogram in ḫpš “strong arm, leg.”'],
  ['F24','𓄘','ḫpš','F23 reversed','ID','Use as F23.'],
  ['F25','𓄙','wḥm','leg and hoof of ox','P','Phonogram wḥm in “hoof,” “repeat.”'],
  ['F26','𓄚','ẖn','goatskin','P','Phonogram ẖn. In ẖnw “interior,” ẖn “approach.”'],
  ['F27','𓄛','','cowskin','D','Determinative in dḥr “hide,” mskꜣ “skin.”'],
  ['F28','𓄜','sꜣb','cowskin','P','Phonogram sꜣb.'],
  ['F29','𓄝','st','cowskin with arrow','PID','Phonogram st. Determinative and Logogram sti “pierce, shoot.”'],
  ['F30','𓄞','šd','water-skin','P','Phonogram šd. In šdi “draw forth,” šdw “water skin.”'],
  ['F31','𓄟','ms','three fox-skins','P','Phonogram ms. In msi “give birth.”'],
  ['F32','𓄡','ẖ','animal’s belly and udder','PI','Phonogram ẖ. Logogram in ẖt “belly, body.”'],
  ['F33','𓄢','sd','tail','PID','Phonogram sd. Determinative and Ideo in sd “tail.”'],
  ['F34','𓄣','ỉb','heart','ID','Logogram for ỉb (“heart, mind”). Determinative in ḥꜣty (“heart”).'],
  ['F35','𓄤','nfr','heart and windpipe','P','Phonogram nfr. In nfr “good, beautiful.”'],
  ['F36','𓄥','smꜣ','lung and windpipe','P','Phonogram smꜣ. In smꜣ (“unite, join”).'],
  ['F37','𓄦','ỉꜣt','spine and ribs','ID','Determinative or Logogram in iꜣt “back.” Determinative in psd “back.”'],
  ['F38','𓄨','','backbone and ribs','D','Determinative in psd “back.”'],
  ['F39','𓄪','ỉmꜣḫ','spine and spinal cord','ID','Determinative and Logogram in imꜣḫ “spine” and “honor.”'],
  ['F40','𓄫','ꜣw','spine and spinal cord','P','Phonogram ꜣw.'],
  ['F41','𓄬','','vertebrae','D','Determinative in psd “back.”'],
  ['F42','𓄭','spr','rib','PID','Phonogram spr. In spr (“arrive, appeal”); determinative or logogram in spr (“rib”).'],
  ['F43','𓄮','','ribs','D','Determinative in sḥpt “ribs.”'],
  ['F44','𓄯','ỉwꜥ|ỉsw','joint of meat','P','Phonogram iwꜥ, isw. In iwꜥ inherit,” siw “exchange.”'],
  ['F45','𓄰','dỉt','cow uterus','ID','Determinative or Logogram in dit “vulva, cow.”'],
  ['F46','𓄲','ḳꜣb','intestine','ID','Determinative or logogram in ḳꜣb (“intestine, midst”). Determinative in pẖr (“go around, turn”).'],
  ['F47','𓄴','ḳꜣb','intestine','ID','Use as F46.'],
  ['F48','𓄶','ḳꜣb','intestine','ID','Use as F46.'],
  ['F49','𓄷','ḳꜣb','intestine','ID','Use as F46.'],
  ['F50','𓄸','spḫr','combination of F46 and S29','P','Phonogram spḫr, “write, copy.”'],
  ['F51','𓄹','ỉs|ỉst|ws','piece of meat','PD','Phonogram is, ist, ws. Determinative ḥꜥ “flesh,” iwf “meat.”'],
  ['F52','𓄽','','excrement','D','Determinative in ḥs “excrement.”'],
  ['F53','𓄾','mt','divine rod with ram head','',''],
  ['G1','𓄿','ꜣ','Egyptian vulture','P','Phonogram 3. In 3 “vulture.’'],
  ['G2','𓅀','ꜣꜣ','two vultures','P','Phono 33. In mꜣꜣ “see.”'],
  ['G3','𓅁','mꜣ','combination of Egyptian vulture and sickle','P','Phonogram in mꜣ. In smꜣwy “renew.”'],
  ['G4','𓅂','tyw','buzzard','P','Phonogram tyw.'],
  ['G5','𓅃','ḥrw','falcon','I','Logogram ḥrw “Horus.”'],
  ['G6','𓅄','','falcon with flail','','De.t in bik “falcon.”'],
  ['G7','𓅆','','falcon on standard','D','Determinative imn “Amun,” nsw “king,” divine. 1st sing. pro. i, wi, with divine speaker.'],
  ['G8','𓅉','Ḥr|bỉk','falcon on collar of beads','I','Logogram Hr/bik nbw “Golden Horus/falcon.”'],
  ['G9','𓅊','rꜥ-ḥrw-ꜣḫty','falcon with sundisk','I','Logogram in rꜥ-ḥrw-ꜣḫty “Re-Horakhty.”'],
  ['G10','𓅋','','falcon in Sokar bark','D','Determinative in skr “Sokar,” ḥnw “Sokar bark.”'],
  ['G11','𓅌','','falcon image','D','Determinative in ꜥšm, ꜥẖm, ꜥḫm “divine image,” šnbt “breast.”'],
  ['G12','𓅎','','combination of image of falcon and flagellum','D','Use as G11.'],
  ['G13','𓅏','ḥrw','falcon image with plumes','ID','Logogram ḥrw nḫny “Horus of Hierakonopolis.” Determinative in spdw “Sopdu.”'],
  ['G14','𓅐','mwt|mt','vulture','P','Phonogram mwt, mt. In mwt “mother.”'],
  ['G15','𓅑','','vulture with flail','D','Determinative in mwt “Mut.”'],
  ['G16','𓅒','nbty','vulture and cobra each on a basket','I','Logogram in nbty “Two Ladies” (title of Pharaoh)'],
  ['G17','𓅓','m','owl','P','Phonogram m.'],
  ['G18','𓅔','mm','two owls','P','Phonogram mm.'],
  ['G19','𓅕','mỉ|m','combination of owl and forearm with conical loaf','P','Phonogram mi, m.'],
  ['G20','𓅖','mỉ|m','combination of owl and forearm','P','Use as G19.'],
  ['G21','𓅘','nḥ','guinea-fowl','P','Phonogram nḥ. In nḥḥ “eternity.”'],
  ['G22','𓅙','ḏb|ḏbt','hoopoe','P','Phonogram ḏb/ḏbt.'],
  ['G23','𓅚','rḫyt','lapwing','ID','Determinative and Logogram in rḫyt “commoners.”'],
  ['G24','𓅛','rḫyt','lapwing with twisted wings','ID','Use as G23.'],
  ['G25','𓅜','ꜣḫ','crested ibis','P','Phonogram ꜣḫ. In “spirit.”'],
  ['G26','𓅝','','ibis on standard','D','Determinative in ḏḥwty “Thoth.”'],
  ['G27','𓅟','dšr','flamingo','P','Phonogram dšr. In dšr “red,” “flamingo.”'],
  ['G28','𓅠','gm','black ibis','P','Phonogram gm. In gmi “find.”'],
  ['G29','𓅡','bꜣ','jabiru','P','Phonogram bꜣ. In “soul.”'],
  ['G30','𓅢','bꜣw','three jabirus','I','Logogram in bꜣw “spirits, strength.”'],
  ['G31','𓅣','','heron','D','Determinative in šnty “heron.”'],
  ['G32','𓅤','bꜥḫỉ','heron on a perch','ID','Determinative or Logogram in bꜥḫi “inundated.”'],
  ['G33','𓅥','','egret','D','Determinative sdꜣ “tremble.”'],
  ['G34','𓅦','','ostrich','D','Determinative in niw “ostrich.”'],
  ['G35','𓅧','ꜥḳ','cormorant','P','Phonogram ꜥq. In ꜥq “enter.”'],
  ['G36','𓅨','wr','forktailed swallow','P','Phonogram wr. In wr “great.”'],
  ['G37','𓅪','','sparrow','D','Determinative in nḏs “small,” bin “bad.”'],
  ['G38','𓅬','gb','goose','PD','Phonogram gb. In gb “Geb.” Determinative in wfꜣ “talk,” wsf “idle,” ḥtm “perish.”'],
  ['G39','𓅭','sꜣ','pintail duck','PD','Phonogram sꜣ. In sꜣ “son.” Determinative in si “duck.”'],
  ['G40','𓅮','pꜣ','pintail duck flying','P','Phonogram pꜣ. In pꜣ “the,” “fly.”'],
  ['G41','𓅯','ḫn','pintail duck landing','P','Phonogram ḫn. In ḫni “alight, halt,” ḫn “speech,” qmꜣ “throw,” “create.”'],
  ['G42','𓅰','wšꜣ','fattened bird','ID','Determinative and Logogram in wšꜣ “fatten,” ḏfꜣw “provisions.”'],
  ['G43','𓅱','w','quail chick','P','Phonogram w.'],
  ['G44','𓅳','ww','two quail chicks','P','Phonogram ww. In pḥww “end.”'],
  ['G45','𓅴','wꜥ','combination of quail chick and forearm','P','Phono wꜥ.In wꜥw “soldier.”'],
  ['G46','𓅶','mꜣw','combination of quail chick and sickle','P','Phonogram mꜣw.'],
  ['G47','𓅷','ṯꜣ','duckling','P','Phonogram ṯꜣ. In ṯꜣy “male.”'],
  ['G48','𓅸','sš','ducklings in nest','I','Logogram in sš “nest.”'],
  ['G49','𓅹','sš','three ducklings in pool','ID','Determinative or Logogram in sš “nest.”'],
  ['G50','𓅺','rḫty','two plovers','I','Logogram for rḫty “washerman.”'],
  ['G51','𓅻','','bird and fish','D','Determinative in ḥꜣm “catch fish.”'],
  ['G52','𓅼','','bird picking up grain','D','Determinative in snm “feed.”'],
  ['G53','𓅽','bꜣ','human-headed bird','I','Logogram in bꜣ “soul.”'],
  ['G54','𓅾','snḏ','plucked bird','P','Phonogram snḏ. In snḏ “fear.”'],
  ['H1','𓅿','ꜣpd','head of duck','ID','Logogram in ꜣpd “bird.” Determinative in wšn “wring the neck of birds.”'],
  ['H2','𓆀','mꜣꜥ|wšm|pꜣḳ','head of a crested bird','PD','Phonogram mꜣꜥ, wšm, pꜣq. Determinative in mꜣꜥ “temple of the head,” “true.”'],
  ['H3','𓆁','pꜣḳ','head of spoonbill','P','Phonogram pꜣq.'],
  ['H4','𓆂','nr','head of vulture','PD','Phonogram nr. Determinative in nrt “vulture.”'],
  ['H5','𓆃','','wing','D','Determinative in ḏnḥ “wing.”'],
  ['H6','𓆄','šw','feather','PID','Phonogram šw. Logogram in šwt “feather.” Determinative and Logogram in mꜣꜥt “truth.”'],
  ['H7','𓆆','šꜣ|šꜣt','claw','P','Phonogram šꜣ, šꜣt. In šꜣt “Shat” (location).'],
  ['H8','𓆇','sꜣ','egg','ID','Logogram in sꜣ “son.” Determinative sḥwt “egg.”'],
  ['I1','𓆈','ꜥšꜣ','gecko','PD','Phonogram ꜥšꜣ. Determinative for lizard. ex. ꜥšꜣ “lizard” and ꜥšꜣ “many, numerous.”'],
  ['I2','𓆉','štyw','turtle','ID','Determinative or Logogram for štyw “turtle.”'],
  ['I3','𓆊','','crocodile','ID','Determinative or Logogram for crocodile. ex. msḥ “crocodile,” ꜣd “agressive.” Logogram ity “sovereign,” when reduplicated'],
  ['I4','𓆋','','crocodile on shrine','D','Determinative sbk “Sobek.”'],
  ['I5','𓆌','','crocodile with curved tail','D','Determinative in sꜣq “collect, gather.”'],
  ['I6','𓆎','km','crocodile scales','P','Phonogram km. In km (“black”) and kmt (“the Black Land”, Egypt).'],
  ['I7','𓆏','wḥm','frog','ID','Determinative in ḥqt “Heqet.” Logogram wḥm ꜥnḫ “repeating life.”'],
  ['I8','𓆐','ḥfn','tadpole','ID','Determinative ḥfnr “tadpole.” Logogram ḥfn “100,000.”'],
  ['I9','𓆑','f','horned viper','PD','Phonogram f. Determinative in it “father.”'],
  ['I10','𓆓','ḏ','cobra','P','Phonogram ḏ.'],
  ['I11','𓆕','ḏḏ','two cobras','P','Phono ḏḏ.'],
  ['I12','𓆗','','erect cobra','D','Determinative in ꜥirt “uraeus.” Determinative of goddesses.'],
  ['I13','𓆘','','cobra on basket','D','Determinative in wꜣḏt “Wadjet.”'],
  ['I14','𓆙','','snake','D','Determinative ḥfꜣw “snake, serpent.”'],
  ['I15','𓆚','','snake','D','Use as I14.'],
  ['K1','𓆛','ỉn','tilapia','P','Phonogram in. In int “bulti.”'],
  ['K2','𓆜','bw','barbel','P','Phonogram bw. In bwt “abomination.”'],
  ['K3','𓆝','ꜥḏ','mullet','P','Phonogram ꜥḏ. In ꜥḏ-mr “district administrator.”'],
  ['K4','𓆞','ẖꜣ','oxyrhynchus','P','Phonogram ẖꜣ. In ẖꜣt “oxyrhynchus.”'],
  ['K5','𓆟','bs','pike','PD','Phonogram bs. Determinative in bsi “introduce.”'],
  ['K6','𓆠','nšmt','fish scale','ID','Determinative and Logogram in nšmt “fish scale.”'],
  ['K7','𓆡','','blowfish','D','Determinative špt “discontented.”'],
  ['K8','𓆢','nꜥr','catfish','',''],
  ['L1','𓆣','ḫpr','scarab beetle','P','Phonogram ḫpr. In ḫpr “being, exist, become.'],
  ['L2','𓆤','bỉty','bee or wasp','I','Logogram for bity “King of Lower Egypt.”'],
  ['L3','𓆦','','fly','D','Determinative in ꜥff “fly.”'],
  ['L4','𓆧','','locust','D','Determinative in snḥm “locust.”'],
  ['L5','𓆨','','centipede','D','Determinative spꜣ “centipede.”'],
  ['L6','𓆩','ḫꜣ','shell','P','Phonogram ḫꜣ. In ḫꜣwt (“offering table”).'],
  ['L7','𓆫','srḳt','emblematic scorpion','ID','Determinative and Logogram in srqt “Selket.”'],
  ['L8','𓆬','','','',''],
  ['M1','𓆭','ỉmꜣ','tree','PD','Phonogram imꜣ. Determinative nhwt, mnw “trees.”'],
  ['M2','𓆰','ḥn','plant','PD','Phonogram ḥn. In ḥni “rush,” ḥnw “vessel.” Determinative in is “tomb.”'],
  ['M3','𓆱','ḫt','stick','P','Phonogram ḫt. In ḫt “wood,” ḫtyw “terrace,” nḫt “strong.”'],
  ['M4','𓆳','rnpt','rib of palm branch','ID','Logogram in rnpt “year,” ḥsbt “regnal year.” Determinative in tr “time.”'],
  ['M5','𓆴','tr','combination of palm branch and flat loaf','ID','Determinative or Logogram in tr “time, season.”'],
  ['M6','𓆵','tr','combination of palm branch and mouth','ID','Determinative or Logogram in tr “time, season.”'],
  ['M7','𓆶','rnpỉ','combination of palm branch and stool','ID','Determinative or Logogram in rnpi “young.”'],
  ['M8','𓆷','ꜣḫt','pool with water-lilies','PI','Phono šꜣ. In šꜣ “marsh.” Logogram ꜣḫt “Inundation” (season).'],
  ['M9','𓆸','','lotus (water-lily)','ID','Determinative or Ideo in sšn “lily.”'],
  ['M10','𓆹','','lotus bud','D','Determinative in nḥbt “lily bud.”'],
  ['M11','𓆻','wdn','flower on long twisted stalk','ID','Determinative or Logogram in wdn “offer.”'],
  ['M12','𓆼','ḫꜣ','lotus plant','P','Phonogram ḫꜣ. In ḫꜣw nw sšn “lily plants” ḫꜣ “1,000,” sḫꜣ “remember.”'],
  ['M13','𓇅','wꜣḏ|wḏ','papyrus','P','Phonogram wꜣḏ, wḏ.'],
  ['M14','𓇆','wꜣḏ','combination of papyrus and cobra','P','Phonogram wꜣḏ. In wꜣḏ wr “the sea.”'],
  ['M15','𓇇','ꜣḫ','clump of papyrus with buds','PD','Phonogram ꜣḫ. In ꜣḫ-bit “Chemmis.” Determinative of Papyrus.'],
  ['M16','𓇉','ḥꜣ','clump of papyrus','PD','Phonogram ḥꜣ . In ḥꜣq “capture.” Determinative in “The Delta.”'],
  ['M17','𓇋','ỉ','reed','P','Phonogram i. Phonogram y, when doubled.'],
  ['M18','𓇍','ỉ','combination of reed and legs walking','P','Phono i. In ii “come.”'],
  ['M19','𓇎','ꜥꜣbt','emblem for offerings','ID','Determinative and Logogram in ꜥꜣbt “offering.”'],
  ['M20','𓇏','','field of reeds','D','Determinative sḫt “marshland,” sm “occupation.”'],
  ['M21','𓇐','','reeds with root','D','Determinative in sm “plant,” “help.”'],
  ['M22','𓇑','nḫb','rush','P','Phonogram nḫb . Phonogram nn, when doubled. In nḫbt “germination,” “Nehkbet.”'],
  ['M23','𓇓','sw','sedge','PI','Phonogram sw. Logogram nswt “king.”'],
  ['M24','𓇔','rsw','combination of sedge and mouth','I','Logogram rsw “south.”'],
  ['M25','𓇖','rsw','combination of flowering sedge and mouth','I','Use as M24.'],
  ['M26','𓇗','šmꜥ','flowering sedge','PI','Phonogram šmꜥ. Logogram šmꜥw in “Upper Egypt.”'],
  ['M27','𓇘','šmꜥ','combination of flowering sedge and forearm','P','Phonogram šmꜥ.'],
  ['M28','𓇙','','combination of flowering sedge and hobble','I','Logogram in title wr mḏw šmꜥw “Greatest of the tens of Upper Egypt.”'],
  ['M29','𓇛','nḏm','pod','P','Phonogram nḏm. In nḏm “sweet.'],
  ['M30','𓇜','bnr','root','ID','Determinative or Logogram bnr “sweet.”'],
  ['M31','𓇝','','rhizome','D','Determinative in rd “grow.”'],
  ['M32','𓇟','','rhizome','D','Use as M31'],
  ['M33','𓇠','','grain','I','Logogram in it “barley, corn.”'],
  ['M34','𓇣','btỉ','sheaf of emmer','ID','Determinative or Logogram in bti “emmer.”'],
  ['M35','𓇤','','heap of grain','D','Determinative of heap.'],
  ['M36','𓇥','ḏr','bundle of flax','P','Phonogram ḏr. In ḏr (“limit, end; since”).'],
  ['M37','𓇦','ḏr','bundle of flax','P','Phonogram ḏr.'],
  ['M38','𓇧','','bundle of flax','D','Determinative in mḥꜥ “flax,” dmꜣ “bind together.”'],
  ['M39','𓇨','','basket of fruit or grain','D','Determinative in rnpt “vegetables.”'],
  ['M40','𓇩','ỉs','bundle of reeds','P','Phonogram ỉs. In ỉs (“tomb”) and ỉst (“crew, gang”).'],
  ['M41','𓇫','','piece of wood','D','Determinative in ꜥš “cedar.”'],
  ['M42','𓇬','wn','rosette','P','Phonogram wn. In wnm “eat,” ḥwn “be young.”'],
  ['M43','𓇭','ỉrp','grapes on trellis','ID','Determinative or Logogram in irp “wine.”'],
  ['M44','𓇮','','thorn','D','Determinative spd “sharp.”'],
  ['N1','𓇯','pt','sky','ID','Logogram for pt (“sky, heaven”). Determinative of sky, above; in ḥry (“upper”).'],
  ['N2','𓇰','grḥ','sky with scepter','ID','Determinative or Logogram grḥ “night.”'],
  ['N3','𓇱','grḥ','sky with sceptre','ID','Use as N2.'],
  ['N4','𓇲','šnyt','sky with rain','ID','Determinative or Logogram šnyt “rain,” iꜣdt “dew.”'],
  ['N5','𓇳','rꜥ','sun','ID','Logogram for rꜥ (“sun, Re”), hrw (“day”) and sw (“day”, in dates). Determinative of sun, day, time.'],
  ['N6','𓇴','','sun with uraeus','ID','Determinative or ideo in rꜥ “sun, Re.”'],
  ['N7','𓇵','','combination of sun and butcher\'s block','D','Determinative ẖrt-hrw “daytime.”'],
  ['N8','𓇶','wbn','sun with rays','PID','Phonogram wbn. Determinative or Logogram ꜣḫw “sunshine,” psḏ “shine,” wbn “rise.”'],
  ['N9','𓇷','psḏ','moon','P','Phonogram psḏ. In psḏt “Ennead.”'],
  ['N10','𓇸','psḏ','moon with lower section obscured','P','Use as N9.'],
  ['N11','𓇹','ꜣbd','crescent moon','ID','Logogram ꜣbd “month.” Determinative iꜥḥ “moon.”'],
  ['N12','𓇺','','crescent moon','D','Determinative iꜥḥ “moon.”'],
  ['N13','𓇻','mḏdỉwnt','combination of crescent moon and star','I','Logogram mḏdiwnt “half month festival.”'],
  ['N14','𓇼','sbꜣ|dwꜣ','star','PI','Phonogram sbꜣ, dwꜣ. In sbꜣ “star,” dwꜣ “morning.” Logogram wnwt “hour.”'],
  ['N15','𓇽','dwꜣt','star in circle','I','Logogram in dwꜣt “netherworld.”'],
  ['N16','𓇾','tꜣ','strip of land with sand','PD','Phonogram tꜣ. In tꜣ “land, earth.”Determinative in ḏt “eternity.”'],
  ['N17','𓇿','tꜣ','land','PD','Use as N16.'],
  ['N18','𓈀','ỉw','strip of land','I','Logogram in iw “island.”'],
  ['N19','𓈃','ꜣḫt','two strips of land','I','Logogram in ꜣḫt “horizon,” ḥrw-ꜣḫty “Horakhty.”'],
  ['N20','𓈄','wḏb','tongue of land','PD','Phonogram wḏb. In wḏb “shore.” Determinative in ḥꜣb-sd “Sed Festival.”'],
  ['N21','𓈅','ỉdb','tongue of land','I','Logogram in idb “bank,” idbwy “two banks.”'],
  ['N22','𓈆','','broad tongue of land','D','Determinative in ꜥḥt “field,” sḫt “field.”'],
  ['N23','𓈇','','irrigation canal','ID','Determinative of land, especially irrigated land. Logogram for gbb (“Geb”).'],
  ['N24','𓈈','spꜣt','irrigation canal system','ID','Determinative or Logogram in spꜣt “nome.”'],
  ['N25','𓈉','ḫꜣst','three hills','I','Logogram in ḫꜣst “foreign land, hill country.”'],
  ['N26','𓈋','ḏw','mountain','P','Phonogram ḏw “mountain.”'],
  ['N27','𓈌','ꜣḫt','sun rising above mountain','I','Logogram in ꜣḫt “horizon.”'],
  ['N28','𓈍','ḫꜥ','sun’s rays above hill','P','Phonogram ḫꜥ. In ḫꜥ “appear.”'],
  ['N29','𓈎','ḳ','sandy slope','P','Phonogram q.'],
  ['N30','𓈏','ỉꜣt','hill with shrubs','ID','Determinative or Logogram in iꜣt “mound.”'],
  ['N31','𓈐','wꜣt','path with shrubs','ID','Determinative and Logogram in wꜣt “road.”'],
  ['N32','𓈑','','lump of clay','D','Determinative in sin “clay.”'],
  ['N33','𓈒','','grain of sand','D','Determinative in nbw “gold.”'],
  ['N34','𓈔','bỉꜣ','ingot of metal','I','Logogram in biꜣ, ḥmt “copper.”'],
  ['N35','𓈖','n','ripple of water','P','Phonogram n.'],
  ['N36','𓈘','mr','canal','P','Phonogram mr. In mr “canal.”'],
  ['N37','𓈙','š','depression','P','Phonogram š. In š “pool.”'],
  ['N38','𓈛','š','deep pool','P','Use as N37.'],
  ['N39','𓈜','š','pool with water','P','Use as N37.'],
  ['N40','𓈝','šm','poolwith legs','P','Phonogram šm. In šm “to go.”'],
  ['N41','𓈞','ḥm','well with water','PD','Phonogram ḥm. In ḥmt “wife.” Determinative in biꜣ “copper.”'],
  ['N42','𓈟','ḥm','well with line of water','PD','Use as N41.'],
  ['O1','𓉐','pr','schematic house plan','P','Phonogram pr. In pr “house,” pri “go.”'],
  ['O2','𓉒','pr-ḥḏ','combination of house and mace with round head','I','Logogram in pr-ḥḏ “treasury.”'],
  ['O3','𓉓','prt-ḫrw','combination of house, oar, tall loaf and beer jug','I','Logogram in prt-ḫrw “invocation offering.”'],
  ['O4','𓉔','h','reed shelter','P','Phonogram h.'],
  ['O5','𓉕','nm','winding wall','P','Phonogram nm. In nmi “traverse.”'],
  ['O6','𓉗','ḥwt','plan of enclosure','I','Logogram in ḥwt “temple, tomb, enclosure.”'],
  ['O7','𓉞','ḥwt','combination of enclosure and flat loaf','I','Use as O6.'],
  ['O8','𓉟','ḥwt-ꜥꜣ','combination of enclosure, flat loaf and wooden column','I','Logogram in ḥwt-ꜥꜣ “Great temple, enclosure.”'],
  ['O9','𓉠','nbt-ḥyt','combination of enclosure, flat loaf and basket','I','Logogram in nbt-ḥyt “Nephthys.”'],
  ['O10','𓉡','ḥwt-ḥrw','combination of enclosure and falcon','I','Logogram in ḥwt-ḥrw “Hathor.”'],
  ['O11','𓉥','ꜥḥ','palace plan with battlements','',''],
  ['O12','𓉦','ꜥḥ','combination of palace and forearm','I','Logogram in ꜥḥ “palace.”'],
  ['O13','𓉧','','enclosure with battlements','D','Determinative in sbḫ “enclose,” sbḫt “gateway.”'],
  ['O14','𓉨','','part of battlemented enclosure','D','Use as O13'],
  ['O15','𓉩','wsḫt','enclosure with cup and flat loaf','I','Logogram in wsḫt “hall.”'],
  ['O16','𓉪','tꜣyt','cornice with cobras','ID','Determinative or Logogram in tꜣyt “curtain,” tꜣyty “he of the curtain” (vizier title).'],
  ['O17','𓉫','tꜣyt','open gateway with serpents','ID','Use as O16'],
  ['O18','𓉬','kꜣr','shrine in profile','ID','Determinative or Logogram in kꜣr “shrine, chapel.”'],
  ['O19','𓉭','','shrine with poles','D','Determinative in pr-wr “Great House.”'],
  ['O20','𓉯','','shrine','D','Determinative in itrt “row of sanctuaries,” ḫm “shrine.”'],
  ['O21','𓉱','sḥ-nṯr','shrine façade','ID','Determinative or Logogram in sḥ-nṯr “divine shrine.”'],
  ['O22','𓉲','sḥ','booth with pole','ID','Determinative or Logogram in sḥ “counsel,” “booth.”'],
  ['O23','𓉳','ḥꜣb-sd','double pavilion','I','Logogram in ḥꜣb-sd “Sed Festival.”'],
  ['O24','𓉴','','pyramid and enclosure wall','D','Determinative in mr “pyramid.”'],
  ['O25','𓉶','tḫn','obelisk','ID','Determinative or Logogram in tḫn “obelisk.”'],
  ['O26','𓉸','wḏ','stela','ID','Determinative or Logogram in wḏ “stela.”'],
  ['O27','𓉹','','columned hall','D','Determinative in ḫꜣ “office,” ḫꜣwy “night.”'],
  ['O28','𓉺','ỉwn','column with tenon','P','Phono iwn. In iwnw “Heliopolis,” iwn “column.”'],
  ['O29','𓉻','ꜥꜣ','wood column','P','Phonogram ꜥꜣ. In ꜥꜣ “great.”'],
  ['O30','𓉽','sḫnt','support','ID','Determinative or logogram in sḫnt (“support, pillar”).'],
  ['O31','𓉿','','door leaf','D','Determinative in ꜥꜣ “door,” sn, wn “open.”'],
  ['O32','𓊀','','gateway','D','Determinative in sbꜣ “door,” sbḫt “gateway.”'],
  ['O33','𓊁','','palace façade','D','Determinative in srḫ “banner.”'],
  ['O34','𓊃','s','doorbolt','P','Phonogram s. In s “bolt.”'],
  ['O35','𓊄','s','combination of bolt and legs','P','Phonogram s. In sbi “go,” “perish,” ms “bring.”'],
  ['O36','𓊅','ỉnb','wall','ID','Determinative of wall. Logogram for ỉnb (“wall”).'],
  ['O37','𓊊','','wall falling','D','Determinative in whn “overthrow,” gsꜣ “tilt.”'],
  ['O38','𓊋','ḳnbt','corner','I','Logogram in qnbt “court, corner, magistrates.”'],
  ['O39','𓊌','','stone block or brick','D','Determinative in inr “stone,” dbni “deben (weight),” ḏbt “brick.”'],
  ['O40','𓊍','','stairs','D','Determinative in rwd “stairwaway,” ḫtyw “terrace.”'],
  ['O41','𓊎','','double stairs','D','Determinative in qꜣy “high place,” iꜥr “ascend.”'],
  ['O42','𓊏','šsp','fence','',''],
  ['O43','𓊐','šsp','fence','','Use as O42'],
  ['O44','𓊑','ỉꜣt','emblem of Min','I','Logogram in iꜣt “rank, office.”'],
  ['O45','𓊒','ỉpt','domed structure','ID','Determinative or Logogram in ipt “harim.”'],
  ['O46','𓊓','ỉpt','domed building','ID','Use as O45.'],
  ['O47','𓊔','nḫn','enclosed mound','I','Logogram in nḫn “Hierakonpolis.”'],
  ['O48','𓊕','nḫn','enclosed mound','I','Variant of O47. Logogram for nḫn (“Hierakonpolis”).'],
  ['O49','𓊖','nỉwt','area with intersection','I','Logogram in niwt “town.”'],
  ['O50','𓊗','sp','threshing floor with grain','P','Phonogram sp. In sp “occasion, time, event,” sp sn “two times.”'],
  ['O51','𓊚','šnwt','pile of grain','ID','Determinative or Logogram in šnwt “granary.”'],
  ['P1','𓊛','','boat on water','D','Determinative of boats. In dpt “ship,” ḥꜥw “ships,” ḫdi “sail downstream.”'],
  ['P2','𓊝','','boat under sail','D','Determinative in ḫnti “sail upstream.”'],
  ['P3','𓊞','','sacred boat','D','Determinative wiꜣ “sacred bark,” ḏꜣi “cross”'],
  ['P4','𓊠','wḥꜥ','boat with net','P','Phonogram wḥꜥ. In wḥꜥ “fisherman.”'],
  ['P5','𓊡','ṯꜣw','mast with sail','ID','Determinative or Logogram in ṯꜣw “wind, breath.” Determinative mḥyt “north wind.”'],
  ['P6','𓊢','ꜥḥꜥ','mast','P','Phonogram ꜥḥꜥ. In ꜥḥꜥ “stand.”'],
  ['P7','𓊣','ꜥḥꜥ','combination of mast and forearm','P','Use as P6.'],
  ['P8','𓊤','ḫrw','oar','P','Phono ḫrw. In mꜣꜥ ḫrw “justified” ḫrw “voice,” ḫrwy “enemy.”'],
  ['P9','𓊥','','combination of oar and horned viper','I','Ideo for ḫr.fy “says, said.”'],
  ['P10','𓊦','','steering oar with rope','D','Determinative in ḥmw “steering oar,” ḥmy “steerer”'],
  ['P11','𓊧','','mooring stake','D','Determinative in mnit “mooring post.”'],
  ['Q1','𓊨','st|ws','seat','P','Phonogram st, ws. In st “seat, place,” wsir “Osiris,” ḥtm “perish.”'],
  ['Q2','𓊩','ws','portable seat','P','Phonogram ws. In wsir “Osiris.”'],
  ['Q3','𓊪','p','stool','P','Phonogram p.'],
  ['Q4','𓊫','','headrest','D','Determinative in wrs “headrest.”'],
  ['Q5','𓊬','','chest','D','Determinative in hn “box,” ꜥfdt “chest.”'],
  ['Q6','𓊭','ḳrs','coffin','ID','Determinative or Logogram in qrs “bury,” qrsw “coffin.”'],
  ['Q7','𓊮','','brazier with flame','D','Determinative of fire. In ḫt “fire,” sḏt “flame,” srf “temperature.”'],
  ['R1','𓊯','ḫꜣt','table with offerings','ID','Determinative or Logogram in ḫꜣt, ḫꜣwt “offering table.”'],
  ['R2','𓊰','ḫꜣt','table with slices of bread','ID','Use as R1.'],
  ['R3','𓊲','wḥḏw','low table with offerings','ID','Determinative or Logogram in wḥḏw “offering table.”'],
  ['R4','𓊵','ḥtp','bread loaf on mat','P','Phonogram ḥtp. In ḥtp “altar, rest, be pleased.”'],
  ['R5','𓊶','kꜣp','censer','ID','Determinative or Logogram in kꜣp “fumigate.”'],
  ['R6','𓊷','kꜣp','broad censer','ID','Use as R5'],
  ['R7','𓊸','sntr','bowl with smoke','ID','Determinative or Logogram in sntr “incense.”'],
  ['R8','𓊹','nṯr','cloth wound on pole','PI','Logogram and phonogram nṯr (“god”). A pole wrapped in cloth, an emblem of divinity.'],
  ['R9','𓊺','bd','combination of cloth on pole and bag','ID','Determinative or Logogram in bd “incense.”'],
  ['R10','𓊻','ẖrt-nṯr','combination of cloth on pole, butcher\'s block and slope of hill','I','Logogram in ẖrt-nṯr “necropolis.”'],
  ['R11','𓊽','ḏd','reed column','P','Phonogram ḏd. In ḏd “stable,” ḏdw “Busiris.”'],
  ['R12','𓊾','','carrying standard','D','Determinative in iꜣt “standard.”'],
  ['R13','𓊿','ỉmnt','falcon and feather on standard','I','Logogram in imnt “West,” wnmi “right.”'],
  ['R14','𓋀','ỉmnt','feather on standard','I','Logogram in imnt “West,” wnmi “right.”'],
  ['R15','𓋁','ỉꜣbt','spear emblem','I','Logogram in iꜣbt “East,” iꜣby “left.”'],
  ['R16','𓋂','','scepter with feathers','ID','Determinative or Ideo in wḫ “Qus emblem.”'],
  ['R17','𓋄','tꜣ-wr','wig with feathers on pole','ID','Determinative or Logogram in tꜣ-wr “This,” “nome of Abydos.”'],
  ['R18','𓋅','tꜣ-wr','combination of wig on pole and irrigation canal system','ID','Use as R17'],
  ['R19','𓋆','','scepter with feather','D','Determinative in wꜣst “Thebes.”'],
  ['R20','𓋇','sšt','Seshat emblem','I','Logogram in sšt “Seshat.”'],
  ['R21','𓋈','sšt','flower with horns','I','Use as R20.'],
  ['R22','𓋉','ḫm','Min emblem','PI','Phonogram ḫm. In ḫm “shrine.” With standard, Logogram in mnw “Min.”'],
  ['R23','𓋊','ḫm','two broad belemnites','PI','Use as R22'],
  ['R24','𓋋','','Neith emblem','D','Determinative in nit “Neith.”'],
  ['R25','𓋌','','two bows tied vertically','D','Use as R24.'],
  ['R26','𓋍','smꜣ-tꜣwy','combination of land, lung and windpipe, lily, and papyrus','',''],
  ['R27','𓋎','nt','two arrows crossed over a shield','',''],
  ['R28','𓋏','bꜣt','Bat','',''],
  ['R29','𓋐','ỉtrt|ỉtrty','niche with serpent','',''],
  ['S1','𓋑','ḥḏt','white crown','ID','Determinative or Logogram in ḥḏt “white crown.”'],
  ['S2','𓋒','ḥḏt','combination of white crown and basket','ID','Determinative or Logogram in ḥḏt “white crown.”'],
  ['S3','𓋔','n','red crown','PID','Phonogram n. Determinative or Ideo in dšrt “Red Crown.”'],
  ['S4','𓋕','n','combination of red crown and basket','PID','Use as S3.'],
  ['S5','𓋖','sḫmty','Double Crown','ID','Determinative or Logogram in sḫmty “double crown.”'],
  ['S6','𓋗','sḫmty','combination of Pschent Crown and basket','ID','Use as S5.'],
  ['S7','𓋙','ḫprš','blue crown','ID','Determinative or Logogram in ḫprš “blue crown.”'],
  ['S8','𓋚','ꜣtf','Atef Crown','ID','Determinative or Logogram in ꜣtf “atef crown.”'],
  ['S9','𓋛','šwty','double plumes','ID','Determinative or Logogram in šwty “double plumes.”'],
  ['S10','𓋜','mḏḥ','headband','P','Phono mḏḥ. In mḏḥ “fillet.”'],
  ['S11','𓋝','wsḫ','broad collar','PID','Phonogram wsḫ. Determinative or logogram in wsḫ (“broad collar”).'],
  ['S12','𓋞','nbw','bead collar','ID','Determinative or Logogram in nbw “gold,” ḥḏ “silver.”'],
  ['S13','𓋟','nb','combination of collar of beads and foot','P','Phonogram nb.'],
  ['S14','𓋠','ḥḏ','combination of collar of beads and mace with round head','I','Logogram in ḥḏ “silver.”'],
  ['S15','𓋣','ṯḥn','faience pectoral','ID','Determinative or Logogram in ṯḥn “sparkle,” ṯḥnt “faience.”'],
  ['S16','𓋤','ṯḥn','','ID','Use as S15.'],
  ['S17','𓋥','ṯḥn','pectoral','ID','Use as S15'],
  ['S18','𓋧','mnỉt','bead necklace','ID','Determinative or Logogram in mnit “bead necklace.”'],
  ['S19','𓋨','sḏꜣwty','seal on necklace','ID','Logogram in sḏꜣwty “treasurer,” sḏꜣw “precious.” Determinative or Logogram in ḫtm “seal.”'],
  ['S20','𓋩','ḫtm','seal on necklace','I','Logogram in ḫtm “seal.”'],
  ['S21','𓋪','','ring','D','Determinative in iwꜥw, ꜥꜥw, sšw “ring.”'],
  ['S22','𓋫','sṯ','shoulder-knot','PID','Phonogram sṯ. Determinative or Logogram in tꜣ-wr “port.”'],
  ['S23','𓋬','dmḏ','knotted cloth','P','Phono dmḏ. In dmḏ “unite.”'],
  ['S24','𓋭','ṯs','knotted belt','PI','Phonogram ṯs. In ṯs (“tie, knot”); logogram for ṯst (“knot, vertebra”).'],
  ['S25','𓋮','ỉꜥꜣw','garment with ties','I','Logogram in iꜥꜣw “guide.”'],
  ['S26','𓋯','šndyt','kilt','ID','Determinative or Logogram in šndyt “apron.”'],
  ['S27','𓋲','mnḫt','cloth with two threads','ID','Determinative or Logogram in mnḫt “clothing.”'],
  ['S28','𓋳','','cloth with fringe on top and folded cloth','D','Determinative in ḥbs “clothing,” ḥꜣp “conceal,” kfi “uncover.”'],
  ['S29','𓋴','s','folded cloth','P','Phonogram s. In ꜥnḫ.(w) (w)ḏꜣ snb “may he live, be prosperous, be healthy.” (L.P.H.)'],
  ['S30','𓋵','sf','combination of folded cloth and horned viper','P','Phonogram sf. In sf “yesterday.”'],
  ['S31','𓋶','smꜣ','combination of folded cloth and sickle','P','Phonogram smꜣ. In smꜣ “fighting bull.”'],
  ['S32','𓋷','sỉꜣ','cloth with fringe','P','Phonogram siꜣ. In siꜣt “fringed cloth.”'],
  ['S33','𓋸','ṯbt','sandal','I','Logogram in ṯbt “sandal,” ṯbw “sandal maker.”'],
  ['S34','𓋹','ꜥnḫ','sandal strap','P','Phonogram ꜥnḫ. In ꜥnḫ “live,” ꜥnḫ “sandal strap.”'],
  ['S35','𓋺','šwt','sunshade or fan','I','Logogram in šwt “shadow, shade.”'],
  ['S36','𓋼','šwt','sunshade','I','Use as S35'],
  ['S37','𓋽','ḫw','fan','ID','Determinative or logogram in ḫw (“fan”).'],
  ['S38','𓋾','ḥḳꜣ','crook','P','Phonogram ḥḳꜣ. The heqa-scepter (the crook); in ḥḳꜣ (“ruler, to rule”).'],
  ['S39','𓋿','ꜥwt','shepherd’s crook','P','Phono ꜥwt. In ꜥwt “flock.”'],
  ['S40','𓌀','wꜣs','animal-headed staff','P','Phonogram wꜣs. The was-scepter, a symbol of dominion and well-being; in wꜣs (“dominion”).'],
  ['S41','𓌁','ḏꜥm','animal-headed staff','P','Phonogram ḏꜥm. In ḏꜥm “fine gold.”'],
  ['S42','𓌂','sḫm','scepter','PID','Phonogram sḫm. In sḫm “have power,” sḫm “scepter.” Determinative or Logogram in ḫrp “manage, at head.”'],
  ['S43','𓌃','md','staff','P','Phonogram md. In mdw “speak.”'],
  ['S44','𓌄','ꜣms','staff with flail','ID','Determinative or Logogram in ꜣms “staff.”'],
  ['S45','𓌅','nḫꜣḫꜣw','flail','ID','Determinative or Logogram in nḫꜣḫꜣw “flail.”'],
  ['S46','𓌆','k','covering for head and neck','',''],
  ['T1','𓌇','mn','mace with flat head','P','Phonogram mn. In mnw “mace.”'],
  ['T2','𓌈','','mace with round head','D','Determinative in sqr, sqri “smite.”'],
  ['T3','𓌉','ḥḏ','mace with round head','P','Phonogram ḥḏ. In ḥḏ “mace,” ḥḏ “white, bright,” ḥḏi “damage.”'],
  ['T4','𓌋','ḥḏ','mace with strap','P','Use as T3'],
  ['T5','𓌌','ḥḏ','combination of mace with round head and cobra','P','Phonogram ḥḏ.'],
  ['T6','𓌍','ḥḏḏ','combination of mace with round head and two cobras','P','Phonogram ḥḏḏ.'],
  ['T7','𓌎','','axe','D','Determinative in mibt, minb “axe,” mdḥ “hew.”'],
  ['T8','𓌐','tp','dagger','P','Phonogram tp. In tpy “first, chief, upon.”'],
  ['T9','𓌒','pḏ','bow','PID','Phonogram pḏ. Determinative or logogram in pḏt (“bow”).'],
  ['T10','𓌔','pd|pḏ','composite bow','PID','Use as T9'],
  ['T11','𓌕','swn','arrow','P','Phonogram swn. In swn “perish,” swnt “physician.”'],
  ['T12','𓌗','rwd|rwḏ','bowstring','PI','Phonogram rwd/rwḏ. In rwd “hard, firm.” Logogram in dꜣr “subdue.”'],
  ['T13','𓌘','rs','pieces of wood tied','P','Phonogram rs. In rs “wakeful.”'],
  ['T14','𓌙','ꜥꜣm','throw-stick','ID','Determinative of “foreign.” Logogram in ꜥꜣm “Asiatics,” ṯḥnw “Libya.” Determinative in qmꜣ “create,” qmꜣi “create.”'],
  ['T15','𓌚','ꜥꜣm','throw stick slanted','ID','Use as T14'],
  ['T16','𓌛','','scimitar','D','Determinative in ḫpš “scimitar.”'],
  ['T17','𓌝','wrrt','chariot','ID','Determinative or Logogram in wrrt “chariot.”'],
  ['T18','𓌞','šms','crook with package attached','P','Phonogram šms. In šms “follow, accompany.”'],
  ['T19','𓌟','ḳs','bone harpoon head','PD','Phonogram ḳs. In ḳs (“bone”); determinative in ḳrs (“bury”).'],
  ['T20','𓌠','ḳs','harpoon head','PD','Use as T19'],
  ['T21','𓌡','wꜥ','harpoon','P','Phonogram wꜥ. In wꜥ (“one”).'],
  ['T22','𓌢','sn','arrowhead','P','Phonogram sn. In sn “brother,” sn “smell.”'],
  ['T23','𓌣','sn','arrowhead','P','Use as T22'],
  ['T24','𓌤','ꜥḥ|ỉḥ','fishing net','P','Phonogram ꜥḥ/iḥ . In iḥ “net.”'],
  ['T25','𓌥','dbꜣ|ḏbꜣ','reed float','P','Phonogram dbꜣ/ḏbꜣ. In ḏbꜣ “adorn,” dbꜣ “replace.”'],
  ['T26','𓌦','sḫt','birdtrap','ID','Determinative or Logogram in sḫt “trap, snare.”'],
  ['T27','𓌧','sḫt','bird trap','ID','Use as T26'],
  ['T28','𓌨','ẖr','butcher’s block','P','Phonogram ẖr. In ẖr “under,” ẖrt “portion.”'],
  ['T29','𓌩','nmt','butcher\'s block with knife','I','Logogram in nmt “place of slaughter.”'],
  ['T30','𓌪','dmt','knife or saw','ID','Logogram for dmt “knife.” Determinative in dm “be sharp.”'],
  ['T31','𓌫','sšm','knife-sharpener','P','Phono sšm. In sšm “guide, lead.”'],
  ['T32','𓌬','sšm','combination of knife-sharpener and legs','P','Phono sšm. In sšm “guide, lead.”'],
  ['T33','𓌮','sšm','knife-sharpener of butcher','I','Logogram in sšm “butcher.”'],
  ['T34','𓌰','nm','butcher\'s knife','P','Phonogram nm. In nm “knife,” ḫnms “friend.”'],
  ['T35','𓌱','nm','butcher knife','PID','Phonogram nm. Determinative or logogram in nm (“butcher\'s knife”).'],
  ['T36','𓌲','','shield','',''],
  ['U1','𓌳','mꜣ','sickle','P','Phonogram mꜣ. In mꜣꜣ “see,” ꜣsḫ “reap.”'],
  ['U2','𓌴','mꜣ','sickle','P','Use as U1.'],
  ['U3','𓌵','mꜣ','','P','Phonogram mꜣ. In mꜣꜣ “see.”'],
  ['U4','𓌶','mꜣꜥ','mꜣꜥ','P','Phonogram mꜣꜥ. In mꜣꜥ “true.”'],
  ['U5','𓌷','mꜣꜥ','','P','Use as U4.'],
  ['U6','𓌸','mr','hoe','P','Phonogram mr. In mri “love.”'],
  ['U7','𓌻','mr','hoe','P','Use as U6.'],
  ['U8','𓌼','ḥn','hoe','P','Phonogram ḥn. In ḥn “hoe.”'],
  ['U9','𓌽','','grain-measure with grain','D','Determinative in bdt “emmer,” ḫꜣi “measure,” ḥqꜣt “hekat measure.”'],
  ['U10','𓌾','','grain measure (with plural, for grain particles)','I','Logogram in it “barley.”'],
  ['U11','𓌿','ḥḳꜣt','','I','Logogram in ḥqꜣt “hekat measure.”'],
  ['U12','𓍀','ḥḳꜣt','','I','Logogram in ḥqꜣt “hekat measure.”'],
  ['U13','𓍁','šnꜥ','plow','P','Phonogram šnꜥ. In šnꜥ “repel.” Phono hb. In hb “plow.”'],
  ['U14','𓍂','šnꜥ','','P','Phonogram šnꜥ. In šnꜥ “repel.”'],
  ['U15','𓍃','tm','sled','P','Phonogram tm. In tm “be complete,” ḥtm “perish.”'],
  ['U16','𓍄','bỉꜣ','loaded sled with jackal’s head','ID','Determinative or logogram in bỉꜣ (“marvel, wonder”). Determinative of sled.'],
  ['U17','𓍅','grg','pick and depression','P','Phonogram grg. In grg “establish, snare,” grg “falshood, lie.”'],
  ['U18','𓍆','grg','pick and depression','P','Variant of U17. Phonogram grg. In grg (“found, establish”).'],
  ['U19','𓍇','nw','adze','P','Phonogram nw. In nw “this.”'],
  ['U20','𓍈','nw','','P','Use as U19'],
  ['U21','𓍉','stp|sṯp','adze and block of wood','P','Phonogram stp/sṯp. In stp “choose.”'],
  ['U22','𓍊','','chisel','D','Determinative in mnḫ “efficient,” mnḫ “carve.”'],
  ['U23','𓍋','mr','chisel','P','Phonogram mr. In mr “ill,” smr “friend.” Phonogram ꜣb. In ꜣbi “desire.”'],
  ['U24','𓍍','ḥmt','handdrill(hieroglyph)','I','Logogram in ḥmt “craft, art.”'],
  ['U25','𓍎','ḥmt','drill for stone','I','Use as U24.'],
  ['U26','𓍏','wbꜣ','drill for beads','ID','Determinative or logogram in wbꜣ (“open up, drill”).'],
  ['U27','𓍐','wbꜣ','','ID','Use as U26.'],
  ['U28','𓍑','ḏꜣ','fire-drill','P','Phonogram ḏꜣ. In ꜥnḫ.(w) (w)ḏꜣ snb “may he live, be prosperous, be healthy.” (L.P.H.)'],
  ['U29','𓍒','ḏꜣ','fire-drill','P','Use as U28.'],
  ['U30','𓍔','tꜣ','kiln','P','Phonogram tꜣ. In štꜣ “hot,” tꜣ “mysterious.'],
  ['U31','𓍕','rtḥty','baker’s rake','ID','Determinative or Logogram in rtḥty “baker,” rtḥ “restrain.”'],
  ['U32','𓍖','','pestle and mortar','D','Determinative in smn “press down,” smn “establish.”'],
  ['U33','𓍘','tỉ','pestle','P','Phonogram ti.'],
  ['U34','𓍙','ḫsf','spindle','P','Phonogram ḫsf. In ḫsf “repel.”'],
  ['U35','𓍚','ḫsf','','P','Phonogram ḫsf.'],
  ['U36','𓍛','ḥm','launderer’s club','P','Phonogram ḥm. In ḥm (“majesty”) and ḥm-nṯr (“god\'s servant”, priest).'],
  ['U37','𓍜','','razor','D','Determinative in ẖꜥq “shave.”'],
  ['U38','𓍝','mḫꜣt','scale','ID','Determinative or Logogram in mḫꜣt “scale.”'],
  ['U39','𓍞','','upright of scale','D','Determinative in wsṯt “post,” wṯs, ṯsi “raise, lift.”'],
  ['U40','𓍟','','a support-(to lift)','D','Use as U39'],
  ['U41','𓍠','','plumb bob','D','Determinative in tḫ “plumb bob.”'],
  ['U42','𓍡','','pitchfork','',''],
  ['V1','𓍢','šn','coil of rope','P','Phonogram šn. In šnt “dispute,” šni “litigate,” št “hundred.”'],
  ['V2','𓍬','sṯꜣt','','ID','Determinative in stꜣ “drag.” Logogram in sṯꜣt “aurora.”'],
  ['V3','𓍮','r-sṯꜣw','','I','Logogram in r-sṯꜣw “necropolis.”'],
  ['V4','𓍯','wꜣ','lasso','P','Phonogram wꜣ. In wꜣḥ “endure.”'],
  ['V5','𓍰','snṯ','looped rope','ID','Determinative or Logogram in snṯ “plot.”'],
  ['V6','𓍱','šs|šsr','cord with ends up','P','Phonogram šs, šsr.'],
  ['V7','𓍲','šn','cord with ends down','P','Phonogram šn.'],
  ['V8','𓍵','šn','','P','Use as V7'],
  ['V9','𓍶','','round cartouche','D','Determinative in šnw “cartouche.”'],
  ['V10','𓍷','','cartouche','D','Determinative in šnw “cartouche,” rn “name.'],
  ['V11','𓍸','','cartouche-(divided)','D','Determinative in dni “restrain, dam,” pḫꜣ “split.'],
  ['V12','𓍼','','string','D','Determinative in sšd “headband,” fḫ “loosen,” fḫnw “Phoenicians.'],
  ['V13','𓍿','ṯ','hobble','P','Phonogram ṯ.'],
  ['V14','𓎀','','','','Use as last.'],
  ['V15','𓎁','ỉṯ','tethering rope w/ walking legs','P','Phonogram iṯ. In iṯi “seize.”'],
  ['V16','𓎂','sꜣ','hobble for cattle','P','Phonogram sꜣ. In sꜣ “protection.”'],
  ['V17','𓎃','sꜣ','rolled-up tent','I','Logogram for sꜣ (“protection”). Variant of V16.'],
  ['V18','𓎄','sꜣ','','I','Use as V17'],
  ['V19','𓎅','','hobble for cattle','D','Determinative in ḫꜣr (“sack”, a measure), tmꜣ (“mat”) and mḏt (“stable”).'],
  ['V20','𓎆','mḏ','"cattle hobble"','P','Phonogram mḏ. In mḏwt “stables,” mḏ “10.”'],
  ['V21','𓎓','mḏ','Fetter + Cobra','P','Phonogram mḏ.'],
  ['V22','𓎔','mḥ','whip','P','Phonogram mḥ. In mḥ “fill.”'],
  ['V23','𓎕','mḥ','whip','P','Variant of V22. Phonogram mḥ. In mḥ (“fill”) and mḥ (“cubit”).'],
  ['V24','𓎗','wḏ','cord wound on stick','P','Phonogram wḏ. In wḏ “command, decree.”'],
  ['V25','𓎘','wḏ','cord wound on stick','P','Variant of V24. Phonogram wḏ. In wḏ (“command, decree”).'],
  ['V26','𓎙','ꜥd|ꜥḏ','spool with thread','P','Phonogram ꜥd/ꜥḏ. In ꜥd “good condition.”'],
  ['V27','𓎚','ꜥd|ꜥḏ','','P','Use as V26.'],
  ['V28','𓎛','ḥ','wick','P','Phonogram ḥ.'],
  ['V29','𓎝','wꜣḥ|sk','swab','P','Phonogram wꜣḥ, sk.'],
  ['V30','𓎟','nb','basket','P','Phonogram nb. A basket; in nb (“lord”) and nb (“all, every”).'],
  ['V31','𓎡','k','basket with handle','P','Phono k.'],
  ['V32','𓎣','msn','wicker satchel','PD','Determinative in gꜣwt (“bundle”) and gꜣw (“lack, absence”). Phonogram msn.'],
  ['V33','𓎤','','bag','ID','Determinative in ꜥrf (“enclose, pack”), sṯỉ (“scent”) and šs (“linen”). Logogram for sšrw (“grain”).'],
  ['V34','𓎦','','','ID','Use as V33.'],
  ['V35','𓎧','','bag (variant of V33)','D','Variant of V33. Determinative of linen, packing.'],
  ['V36','𓎨','ḥn','receptacle of cloth','P','Phonogram ḥn. In ḥnt “occupation.”'],
  ['V37','𓎩','ỉdr','bandage','ID','Determinative or Logogram in idr “bandage, bind,” idr “herd.”'],
  ['V38','𓎫','','bandage','D','Determinative in wt “bandage.”'],
  ['V39','𓎬','tỉt','tie','I','Logogram in tit “Isis knot.”'],
  ['V40','𓎭','','','',''],
  ['W1','𓎯','','Oil jar','D','Determinative in mḏt “ointment,” mrḥt “oil.”'],
  ['W2','𓎰','bꜣs','Oil-jar without ties','P','Phonogram bꜣs. In bꜣstt “Bastet,” bꜣs “oil jar.”'],
  ['W3','𓎱','ḥb','alabaster basin','ID','Determinative or Logogram in ḥb “feast,” ḥb “mourn.”'],
  ['W4','𓎳','ḥb','festival chamber, (the tail is also vertical \'Great\': ꜥꜣ)','ID','Determinative or Logogram in ḥb “feast,” tp-rnpt “feat of the first of the year.”'],
  ['W5','𓎴','','','I','Ideo in ẖry-ḥbt “lector priest.”'],
  ['W6','𓎵','','metal vessel','D','Determinative in wḥt “cauldron.”'],
  ['W7','𓎶','','granite bowl','D','Determinative in ꜣbt “family,” mꜣṯ “proclaim.”'],
  ['W8','𓎷','','deformed granite bowl','D','Use as W7.'],
  ['W9','𓎸','ẖnm','stone jug','P','Phonogram ẖnm.'],
  ['W10','𓎺','ḥnw','cup','PID','Phonogram ḥnw. In ḥnwt “mistress.” Determinative or Logogram in wsḫ “wide.”'],
  ['W11','𓎼','g','ring stand/earthenware pot','PID','Phonogram g. Determinative or Logogram in nst “throne.”'],
  ['W12','𓎽','g','jar stand','PID','Use as W11.'],
  ['W13','𓎾','dšrt','pot','ID','Determinative or logogram in dšrt (“red pot, red ware”).'],
  ['W14','𓎿','ḥs','water jar','P','Phonogram ḥs. In ḥst “water jar.”'],
  ['W15','𓏁','ḳbb','water jar with water','ID','Determinative or Logogram in qbb, qbḥ “cool, water.”'],
  ['W16','𓏂','ḳbb','water jar with water pouring out and ring stand','ID','Use as W15.'],
  ['W17','𓏃','ḫnt','three water jars in rack','P','Phonogram ḫnt. In ḫntw “jar rack.”'],
  ['W18','𓏅','ḫnt','water jars in a rack','P','Use as W17'],
  ['W19','𓏇','mỉ','Milk jug with handle','P','Phonogram mi. In mi “likeness.”'],
  ['W20','𓏈','','Milk jug with cover','D','Determinative in irtt “milk.”'],
  ['W21','𓏉','','Wine jars','D','Determinative in irp “wine.”'],
  ['W22','𓏊','ḥnḳt','Beer jug','ID','Logogram in ḥnqt “beer.” Determinative in qrḥt “vessel.”'],
  ['W23','𓏋','ḥnḳt','Beer jug with handles','ID','Use as W22.'],
  ['W24','𓏌','nw|ỉn|ỉnk','Pot','P','Phonogram nw, in, ink.'],
  ['W25','𓏎','ỉn','Pot with legs','P','Phonogram in. In ini “fetch, bring.”'],
  ['X1','𓏏','t','flat loaf of bread','PI','Phonogram t. Logogram in t “bread.”'],
  ['X2','𓏐','dḥwty','tall loaf of bread','ID','Determinative of bread. In t “bread.” Logogram in dḥwty “Thoth.”'],
  ['X3','𓏑','dḥwty','','ID','Use as X2'],
  ['X4','𓏒','','bread roll','D','Determinative of bread, food; in words with sn (from snw, “food offerings”).'],
  ['X5','𓏕','','','D','Determinative in ꜥqw “provisions.”'],
  ['X6','𓏖','','round loaf of bread','D','Determinative in pꜣt “loaf.”'],
  ['X7','𓏘','','half-loaf of bread','D','Determinative in snw “offerings.” When doubled, wnm “eat.”'],
  ['X8','𓏙','dỉ','bread mold','P','Phonogram di. In rdi “give.”'],
  ['Y1','𓏛','mḏꜣt','papyrus scroll','PID','Phonogram mḏꜣt. Logogram in mḏꜣt “paypyrus roll, book.” Determinative in rḫ “know.”'],
  ['Y2','𓏝','mḏꜣt','Papyrus roll-open','PID','Use as Y1'],
  ['Y3','𓏞','sš','scribe’s kit','ID','Determinative or Logogram in sš “write,” nꜥꜥ “smooth.”'],
  ['Y4','𓏟','sš','Scribe\'s equipment','ID','Use as Y3'],
  ['Y5','𓏠','mn','game board and pieces','P','Phonogram mn. In imn “Amun” mn “remain.”'],
  ['Y6','𓏡','ỉbꜣ','game piece','ID','Determinative or Logogram in ibꜣ “game piece,” “dance.”'],
  ['Y7','𓏢','','harp','D','Determinative in bnt “harp.”'],
  ['Y8','𓏣','','Sistrum','D','Determinative in sššt “sistrum.”'],
  ['Z1','𓏤','','stroke','ID','Follows Ideograms. Determinative wꜥ “one.” Logogram numerals 1-9.'],
  ['Z2','𓏥','','three strokes','D','Determinative of plurality.'],
  ['Z3','𓏪','','plural strokes (vertical)','D','Same as Z2.'],
  ['Z4','𓏭','y','two strokes','D','Determinative Duality'],
  ['Z5','𓏯','','Diagonal stroke (from hieratic)','','Replacement for complex or dangerous signs, human figures.'],
  ['Z6','𓏱','','Substitute for various human figures','D','Hieratic substitute for A13 and A14. Determinative of death, enemy.'],
  ['Z7','𓏲','w','from hieratic variant of G43','P','Phonogram w.'],
  ['Z8','𓏳','','Oval','D','Determinative of round.'],
  ['Z9','𓏴','swꜣ','crossed sticks','P','Phonogram swꜣ. In swꜣ “pass.”'],
  ['Z10','𓏵','swꜣ','Crossed diagonal sticks','P','Use as Z9.'],
  ['Z11','𓏶','ỉm','crossed planks','P','Phonogram ỉm. In ỉmỉ (“who is in”). Variant of M42.'],
  ['Z12','𓏷','','','',''],
  ['Z13','𓏸','','','',''],
  ['Z14','𓏹','','','',''],
  ['Z15','𓏺','','','',''],
  ['Z16','𓐄','','','',''],
  ['Aa1','𓐍','ḫ','Placenta or sieve','P','Phonogram ḫ.'],
  ['Aa2','𓐎','','pustule or gland','D','Determinative in bodily growths or conditions.'],
  ['Aa3','𓐏','','Pustule with liquid issuing from it','D','Use as Aa2.'],
  ['Aa4','𓐐','bꜣ','pot','P','Variant of W10a.'],
  ['Aa5','𓐑','ḥp','Part of steering gear of a ship','P','Phonogram ḥp.'],
  ['Aa6','𓐒','','','D','Determinative in tmꜣ “mat.”'],
  ['Aa7','𓐓','','A Smiting-Blade','D','Determinative in sqr “smite.”'],
  ['Aa8','𓐖','ḳn','irrigation channel?','PD','Phonogram ḳn. In ḳnỉ (“brave, capable”); determinative in spꜣt (“district, estate”).'],
  ['Aa9','𓐗','','','D','Determinative in ḫwd “rich.”'],
  ['Aa10','𓐘','','reed pen?','D','Determinative in drf “writing.”'],
  ['Aa11','𓐙','mꜣꜥ','platform','P','Phonogram mꜣꜥ. In mꜣꜥ (“true, correct”).'],
  ['Aa12','𓐚','mꜣꜥ','','P','Use as Aa11.'],
  ['Aa13','𓐛','ỉm|m','','P','Phonogram im, m.'],
  ['Aa14','𓐜','ỉm|m','','P','Phonogram im, m.'],
  ['Aa15','𓐝','ỉm|m','','P','Phonogram im, m.'],
  ['Aa16','𓐞','gs','front half of Aa13','',''],
  ['Aa17','𓐟','sꜣ','lid of a chest','P','Phonogram sꜣ. In sꜣ “back.”'],
  ['Aa18','𓐠','sꜣ','','P','Use as Aa17'],
  ['Aa19','𓐡','','','D','Determinative in ḥr “prepare,” ḥryt “dread.”'],
  ['Aa20','𓐢','ꜥpr','bag for clothing','P','Phonogram ꜥpr. In ꜥpr “equip.”'],
  ['Aa21','𓐣','wḏꜥ','','P','Phonogram wḏꜥ. In wḏꜥ “judge.”'],
  ['Aa22','𓐤','wḏꜥ','','P','Use as Aa21.'],
  ['Aa23','𓐥','','','D','Determinative in mḏd “puncture, press, adhere.”'],
  ['Aa24','𓐦','','warp between stakes','D','Use as Aa23.'],
  ['Aa25','𓐧','smꜣ','','I','Logogram in smꜣ “stolist” (priestly title).'],
  ['Aa26','𓐨','','','D','Determinative in sbi “rebel.”'],
  ['Aa27','𓐩','nḏ','spindle','P','Phonogram nḏ. In nḏ “ask, inquire.”'],
  ['Aa28','𓐪','ḳd','builder’s level','P','Phonogram qd. In qd “build.”'],
  ['Aa29','𓐫','ḳd','','P','Use as Aa28.'],
  ['Aa30','𓐬','ẖkr','frieze ornament','ID','Determinative or logogram in ẖkr (“adorn; ornament”).'],
  ['Aa31','𓐭','ẖkr','frieze element','ID','Use as Aa30.'],
  ['Aa32','𓐮','','bow','',''],
];
